/*
Generated by UnityTwine on 04/28/2016 01:59:16
https://github.com/daterre/UnityTwine
*/
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UnityTwine;

public class dinner: TwineStory
{
	public override TwineVar this[string name]
	{
		get
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
		set
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
	}


	void Awake() {
		base.Init();
		passageInit_0();
		passageInit_1();
		passageInit_2();
		passageInit_3();
		passageInit_4();
		passageInit_5();
		passageInit_6();
		passageInit_7();
		passageInit_8();
		passageInit_9();
		passageInit_10();
		passageInit_11();
		passageInit_12();
		passageInit_13();
		passageInit_14();
		passageInit_15();
		passageInit_16();
		passageInit_17();
		passageInit_18();
		passageInit_19();
		passageInit_20();
		passageInit_21();
		passageInit_22();
		passageInit_23();
		passageInit_24();
		passageInit_25();
		passageInit_26();
		passageInit_27();
		passageInit_28();
		passageInit_29();
		passageInit_30();
		passageInit_31();
		passageInit_32();
		passageInit_33();
		passageInit_34();
		passageInit_35();
		passageInit_36();
		passageInit_37();
		passageInit_38();
		passageInit_39();
		passageInit_40();
		passageInit_41();
	}
    
	// .............
	// #0: Start

	void passageInit_0()
	{
		this.Passages["Start"] = new TwinePassage("Start", new string[]{  }, passageExecute_0);
	}

	IEnumerable<TwineOutput> passageExecute_0()
	{
		yield return new TwineText(@"%1, <beau>, <center>, <smile>%");
		yield return new TwineText(@"BEAUREGARD: I'm so sorry to interrupt, but it's time for dinner, sire! ");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: Oh, how the time flies! Who woud you like to dine with this evening, sire?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Noelle.", @"Noelle.", @"Noelle.", null, null);
		yield return new TwineLink(@"Jane.", @"Jane.", @"Jane.", null, null);
		yield return new TwineLink(@"Patrice.", @"Patrice.", @"Patrice.", null, null);
		yield return new TwineLink(@"Lucille.", @"Lucille.", @"Lucille.", null, null);
		yield return new TwineLink(@"Henrietta.", @"Henrietta.", @"Henrietta.", null, null);	
	}
    
	// .............
	// #1: No one.

	void passageInit_1()
	{
		this.Passages["No one."] = new TwinePassage("No one.", new string[]{  }, passageExecute_1);
	}

	IEnumerable<TwineOutput> passageExecute_1()
	{
		yield return new TwineText(@"%1, <beau>, <center>, <frown>%");
		yield return new TwineText(@"BEAUREGARD: Oh, yes. Ha ha. Very funny, sire. As if I would let you squander an opportunity like this!");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: Now, choose a dining companion or I'll do it for you!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Noelle.", @"Noelle.", @"Noelle.", null, null);
		yield return new TwineLink(@"Jane.", @"Jane.", @"Jane.", null, null);
		yield return new TwineLink(@"Patrice.", @"Patrice.", @"Patrice.", null, null);
		yield return new TwineLink(@"Lucille.", @"Lucille.", @"Lucille.", null, null);
		yield return new TwineLink(@"Henrietta.", @"Henrietta.", @"Henrietta.", null, null);	
	}
    
	// .............
	// #2: Henrietta.

	void passageInit_2()
	{
		this.Passages["Henrietta."] = new TwinePassage("Henrietta.", new string[]{  }, passageExecute_2);
	}

	IEnumerable<TwineOutput> passageExecute_2()
	{
		yield return new TwineText(@"#hen_dinner, +1#");
		yield return new TwineText(@"%1, <beau>, <center>, <frown>%");
		yield return new TwineText(@"BEAUREGARD: Oh. The...lovely Miss Henrietta. Right. ");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <beau>, <center>, <neutral>%");
		yield return new TwineText(@"BEAUREGARD: Well, I'll, um. I suppose I'll set out some...hay? And remove the chair from the other end of the table...Oh, goodness.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"%hen_dinner, 0, 0%<i>The table is set.</i>", @"%hen_dinner, 0, 0%<i>The table is set.</i>", @"hen1", null, null);
		yield return new TwineLink(@"%hen_dinner, 1, 1%<i>The table is set.</i>", @"%hen_dinner, 1, 1%<i>The table is set.</i>", @"hen2", null, null);
		yield return new TwineLink(@"%hen_dinner, 2, 2%<i>The table is set.</i>", @"%hen_dinner, 2, 2%<i>The table is set.</i>", @"hen3", null, null);
		yield return new TwineLink(@"%hen_dinner, 3, 3%<i>The table is set.</i>", @"%hen_dinner, 3, 3%<i>The table is set.</i>", @"hen4", null, null);
		yield return new TwineLink(@"%hen_dinner, 4, 4%<i>The table is set.</i>", @"%hen_dinner, 4, 4%<i>The table is set.</i>", @"hen5", null, null);
		yield return new TwineLink(@"%hen_dinner, 5, 5%<i>The table is set.</i>", @"%hen_dinner, 5, 5%<i>The table is set.</i>", @"hen6", null, null);
		yield return new TwineLink(@"%hen_dinner, 6, 6%<i>The table is set.</i>", @"%hen_dinner, 6, 6%<i>The table is set.</i>", @"hen7", null, null);	
	}
    
	// .............
	// #3: Lucille.

	void passageInit_3()
	{
		this.Passages["Lucille."] = new TwinePassage("Lucille.", new string[]{  }, passageExecute_3);
	}

	IEnumerable<TwineOutput> passageExecute_3()
	{
		yield return new TwineText(@"#lucy_dinner, +1#");
		yield return new TwineText(@"%1, <beau>, <center>, <neutral>%");
		yield return new TwineText(@"BEAUREGARD: Miss Lucille. Well. That's certainly an...interesting choice.");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: I'll be sure to provide the table with plenty of wine tonight, sire. I hope the evening proves pleasant.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"%lucy_dinner, 0, 0%<i>The table is set.</i>", @"%lucy_dinner, 0, 0%<i>The table is set.</i>", @"lucy1", null, null);
		yield return new TwineLink(@"%lucy_dinner, 1, 1%<i>The table is set.</i>", @"%lucy_dinner, 1, 1%<i>The table is set.</i>", @"lucy2", null, null);
		yield return new TwineLink(@"%lucy_dinner, 2, 2%<i>The table is set.</i>", @"%lucy_dinner, 2, 2%<i>The table is set.</i>", @"lucy3", null, null);
		yield return new TwineLink(@"%lucy_dinner, 3, 3%<i>The table is set.</i>", @"%lucy_dinner, 3, 3%<i>The table is set.</i>", @"lucy4", null, null);
		yield return new TwineLink(@"%lucy_dinner, 4, 4%<i>The table is set.</i>", @"%lucy_dinner, 4, 4%<i>The table is set.</i>", @"lucy5", null, null);
		yield return new TwineLink(@"%lucy_dinner, 5, 5%<i>The table is set.</i>", @"%lucy_dinner, 5, 5%<i>The table is set.</i>", @"lucy6", null, null);
		yield return new TwineLink(@"%lucy_dinner, 6, 6%<i>The table is set.</i>", @"%lucy_dinner, 6, 6%<i>The table is set.</i>", @"lucy7", null, null);	
	}
    
	// .............
	// #4: Noelle.

	void passageInit_4()
	{
		this.Passages["Noelle."] = new TwinePassage("Noelle.", new string[]{  }, passageExecute_4);
	}

	IEnumerable<TwineOutput> passageExecute_4()
	{
		yield return new TwineText(@"#noelle_dinner, +1#");
		yield return new TwineText(@"%1, <beau>, <center>, <smile>%");
		yield return new TwineText(@"BEAUREGARD: Ah, Miss Noelle. Perfect.");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: I'll get everything ready for you two. I'm sure it will be a perfectly pleasant evening!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"%noelle_dinner, 0, 0%<i>The table is set.</i>", @"%noelle_dinner, 0, 0%<i>The table is set.</i>", @"noe1", null, null);
		yield return new TwineLink(@"%noelle_dinner, 1, 1%<i>The table is set.</i>", @"%noelle_dinner, 1, 1%<i>The table is set.</i>", @"noe2", null, null);
		yield return new TwineLink(@"%noelle_dinner, 2, 2%<i>The table is set.</i>", @"%noelle_dinner, 2, 2%<i>The table is set.</i>", @"noe3", null, null);
		yield return new TwineLink(@"%noelle_dinner, 3, 3%<i>The table is set.</i>", @"%noelle_dinner, 3, 3%<i>The table is set.</i>", @"noe4", null, null);
		yield return new TwineLink(@"%noelle_dinner, 4, 4%<i>The table is set.</i>", @"%noelle_dinner, 4, 4%<i>The table is set.</i>", @"noe5", null, null);
		yield return new TwineLink(@"%noelle_dinner, 5, 5%<i>The table is set.</i>", @"%noelle_dinner, 5, 5%<i>The table is set.</i>", @"noe6", null, null);
		yield return new TwineLink(@"%noelle_dinner, 6, 6%<i>The table is set.</i>", @"%noelle_dinner, 6, 6%<i>The table is set.</i>", @"noe7", null, null);	
	}
    
	// .............
	// #5: Patrice.

	void passageInit_5()
	{
		this.Passages["Patrice."] = new TwinePassage("Patrice.", new string[]{  }, passageExecute_5);
	}

	IEnumerable<TwineOutput> passageExecute_5()
	{
		yield return new TwineText(@"#pat_dinner, +1#");
		yield return new TwineText(@"%1, <beau>, <center>, <smile>%");
		yield return new TwineText(@"BEAUREGARD: Miss Patrice. A fine choice, sire.");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: I'll make sure everything is just perfect for this evening!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"%pat_dinner, 0, 0%<i>The table is set.</i>", @"%pat_dinner, 0, 0%<i>The table is set.</i>", @"pat1", null, null);
		yield return new TwineLink(@"%pat_dinner, 1, 1%<i>The table is set.</i>", @"%pat_dinner, 1, 1%<i>The table is set.</i>", @"pat2", null, null);
		yield return new TwineLink(@"%pat_dinner, 2, 2%<i>The table is set.</i>", @"%pat_dinner, 2, 2%<i>The table is set.</i>", @"pat3", null, null);
		yield return new TwineLink(@"%pat_dinner, 3, 3%<i>The table is set.</i>", @"%pat_dinner, 3, 3%<i>The table is set.</i>", @"pat4", null, null);
		yield return new TwineLink(@"%pat_dinner, 4, 4%<i>The table is set.</i>", @"%pat_dinner, 4, 4%<i>The table is set.</i>", @"pat5", null, null);
		yield return new TwineLink(@"%pat_dinner, 5, 5%<i>The table is set.</i>", @"%pat_dinner, 5, 5%<i>The table is set.</i>", @"pat6", null, null);
		yield return new TwineLink(@"%pat_dinner, 6, 6%<i>The table is set.</i>", @"%pat_dinner, 6, 6%<i>The table is set.</i>", @"pat7", null, null);	
	}
    
	// .............
	// #6: Jane.

	void passageInit_6()
	{
		this.Passages["Jane."] = new TwinePassage("Jane.", new string[]{  }, passageExecute_6);
	}

	IEnumerable<TwineOutput> passageExecute_6()
	{
		yield return new TwineText(@"#john_dinner, +1#");
		yield return new TwineText(@"%1, <beau>, <center>, <smile>%");
		yield return new TwineText(@"BEAUREGARD: Miss Jane! Lovely.");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: You dinner for two will be ready momentarily, sire!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"%john_dinner, 0, 0%<i>The table is set.</i>", @"%john_dinner, 0, 0%<i>The table is set.</i>", @"john1", null, null);
		yield return new TwineLink(@"%john_dinner, 1, 1%<i>The table is set.</i>", @"%john_dinner, 1, 1%<i>The table is set.</i>", @"john2", null, null);
		yield return new TwineLink(@"%john_dinner, 2, 2%<i>The table is set.</i>", @"%john_dinner, 2, 2%<i>The table is set.</i>", @"john3", null, null);
		yield return new TwineLink(@"%john_dinner, 3, 3%<i>The table is set.</i>", @"%john_dinner, 3, 3%<i>The table is set.</i>", @"john4", null, null);
		yield return new TwineLink(@"%john_dinner, 4, 4%<i>The table is set.</i>", @"%john_dinner, 4, 4%<i>The table is set.</i>", @"john5", null, null);
		yield return new TwineLink(@"%john_dinner, 5, 5%<i>The table is set.</i>", @"%john_dinner, 5, 5%<i>The table is set.</i>", @"john6", null, null);
		yield return new TwineLink(@"%john_dinner, 6, 6%<i>The table is set.</i>", @"%john_dinner, 6, 6%<i>The table is set.</i>", @"john7", null, null);	
	}
    
	// .............
	// #7: hen1

	void passageInit_7()
	{
		this.Passages["hen1"] = new TwinePassage("hen1", new string[]{  }, passageExecute_7);
	}

	IEnumerable<TwineOutput> passageExecute_7()
	{
		yield return new TwineText(@"#hen_approval, +5#");
		yield return new TwineText(@"%1, <hen>, <center>, <neutral>%");
		yield return new TwineText(@"<i>The evening is calm, and pleasant. The dining room's comfortable silence is broken only by the rhythmic sounds of a cow chewing her cud.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>You might be imagining it, but there seems to be a happy gleam to Miss Henrietta's eyes.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>You walk Henrietta back to the pastures outside as gallantly as a beast walking alongside a cow  can.</i>");	
	}
    
	// .............
	// #8: lucy1

	void passageInit_8()
	{
		this.Passages["lucy1"] = new TwinePassage("lucy1", new string[]{  }, passageExecute_8);
	}

	IEnumerable<TwineOutput> passageExecute_8()
	{
		yield return new TwineText(@"#lucy_approval, +5#");
		yield return new TwineText(@"%1, <lucy>, <center>, <smile>%");
		yield return new TwineText(@"<i>It's a good thing Beauregard provided plenty of wine--Lucille goes straight for the glass bottles and starts knocking back drink after drink.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>As expected, her conversation is dry and acerbic--at least, it is at the start of the night. </i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>As the courses progress, you find that her comments have lost their biting edge. </i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Maybe it's just the wine that loosens the tight corners of her mouth, but you dare to think it might actually be your company.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>When you part ways for the night, her insults sound almost fond to your ears.</i>");	
	}
    
	// .............
	// #9: noe1

	void passageInit_9()
	{
		this.Passages["noe1"] = new TwinePassage("noe1", new string[]{  }, passageExecute_9);
	}

	IEnumerable<TwineOutput> passageExecute_9()
	{
		yield return new TwineText(@"#noelle_approval, +5#");
		yield return new TwineText(@"%1, <noelle>, <center>, <smile>%");
		yield return new TwineText(@"<i>As usual, the lady Noelle is the very picture of grace and poise. She handles herself with the air of one graciously bestowing her presence upon unworthy surroundings.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Nevertheless, you can't help but think she seems to become more comfortable over the course of the night.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>But then, you suppose making idle conversation about harmless topics while maintaining a comfortable physical distance would put anyone at ease. </i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>At the end of the night, you bid her a gallant farewell, and her smile appears almost genuine.</i>");	
	}
    
	// .............
	// #10: pat1

	void passageInit_10()
	{
		this.Passages["pat1"] = new TwinePassage("pat1", new string[]{  }, passageExecute_10);
	}

	IEnumerable<TwineOutput> passageExecute_10()
	{
		yield return new TwineText(@"#pat_approval, +5#");
		yield return new TwineText(@"%1, <pat>, <center>, <smile>%");
		yield return new TwineText(@"<i>Pat is as kind and complimentary as always. Each course seems to amaze her more than the last, and it's clear that her pleased exclamations are sincere.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Pat always seems weighed down by something, distanced from the present by a problem no one else knows about. But tonight, bit by bit, her shoulders lift, and her expression lightens. </i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>When Beauregard's fancifully prepared dessert course makes her clap her hands and laugh delightedly, she looks years younger.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>You bow to her before she leaves for bed, and the smile she gives you is that of a bashful young girl.</i>");	
	}
    
	// .............
	// #11: john1

	void passageInit_11()
	{
		this.Passages["john1"] = new TwinePassage("john1", new string[]{  }, passageExecute_11);
	}

	IEnumerable<TwineOutput> passageExecute_11()
	{
		yield return new TwineText(@"#john_approval, +5#");
		yield return new TwineText(@"%1, <john>, <center>, <smile>%");
		yield return new TwineText(@"<i>Jane has the uncanny ability to make even the smallest of things into grand jokes, and over the course of the evening, this ability starts to rub off on you. </i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Eating with your ungainly claws becomes a source of laughter rather than embarrassment. </i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Your struggle with a spoonful of soup makes both ends of the table turn red in the face from laughing--not that your skin is really visible under all the fur.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>You're still laughing as you part ways.</i>");	
	}
    
	// .............
	// #12: hen2

	void passageInit_12()
	{
		this.Passages["hen2"] = new TwinePassage("hen2", new string[]{  }, passageExecute_12);
	}

	IEnumerable<TwineOutput> passageExecute_12()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #13: lucy2

	void passageInit_13()
	{
		this.Passages["lucy2"] = new TwinePassage("lucy2", new string[]{  }, passageExecute_13);
	}

	IEnumerable<TwineOutput> passageExecute_13()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #14: noe2

	void passageInit_14()
	{
		this.Passages["noe2"] = new TwinePassage("noe2", new string[]{  }, passageExecute_14);
	}

	IEnumerable<TwineOutput> passageExecute_14()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #15: pat2

	void passageInit_15()
	{
		this.Passages["pat2"] = new TwinePassage("pat2", new string[]{  }, passageExecute_15);
	}

	IEnumerable<TwineOutput> passageExecute_15()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #16: john2

	void passageInit_16()
	{
		this.Passages["john2"] = new TwinePassage("john2", new string[]{  }, passageExecute_16);
	}

	IEnumerable<TwineOutput> passageExecute_16()
	{
		yield return new TwineText(@"#john_approval, +5#");
		yield return new TwineText(@"%1, <john>, <center>, <smile>%");
		yield return new TwineText(@"<i>Jane has the uncanny ability to make even the smallest of things into grand jokes, and over the course of the evening, this ability starts to rub off on you. </i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Eating with your ungainly claws becomes a source of laughter rather than embarrassment. </i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Your struggle with a spoonful of soup makes both ends of the table turn red in the face from laughing--not that your skin is really visible under all the fur.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>You're still laughing as you part ways.</i>");	
	}
    
	// .............
	// #17: hen3

	void passageInit_17()
	{
		this.Passages["hen3"] = new TwinePassage("hen3", new string[]{  }, passageExecute_17);
	}

	IEnumerable<TwineOutput> passageExecute_17()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #18: lucy3

	void passageInit_18()
	{
		this.Passages["lucy3"] = new TwinePassage("lucy3", new string[]{  }, passageExecute_18);
	}

	IEnumerable<TwineOutput> passageExecute_18()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #19: noe3

	void passageInit_19()
	{
		this.Passages["noe3"] = new TwinePassage("noe3", new string[]{  }, passageExecute_19);
	}

	IEnumerable<TwineOutput> passageExecute_19()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #20: pat3

	void passageInit_20()
	{
		this.Passages["pat3"] = new TwinePassage("pat3", new string[]{  }, passageExecute_20);
	}

	IEnumerable<TwineOutput> passageExecute_20()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #21: john3

	void passageInit_21()
	{
		this.Passages["john3"] = new TwinePassage("john3", new string[]{  }, passageExecute_21);
	}

	IEnumerable<TwineOutput> passageExecute_21()
	{
		yield return new TwineText(@"#john_approval, +5#");
		yield return new TwineText(@"%1, <john>, <center>, <smile>%");
		yield return new TwineText(@"<i>Jane has the uncanny ability to make even the smallest of things into grand jokes, and over the course of the evening, this ability starts to rub off on you. </i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Eating with your ungainly claws becomes a source of laughter rather than embarrassment. </i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Your struggle with a spoonful of soup makes both ends of the table turn red in the face from laughing--not that your skin is really visible under all the fur.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>You're still laughing as you part ways.</i>");	
	}
    
	// .............
	// #22: hen4

	void passageInit_22()
	{
		this.Passages["hen4"] = new TwinePassage("hen4", new string[]{  }, passageExecute_22);
	}

	IEnumerable<TwineOutput> passageExecute_22()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #23: lucy4

	void passageInit_23()
	{
		this.Passages["lucy4"] = new TwinePassage("lucy4", new string[]{  }, passageExecute_23);
	}

	IEnumerable<TwineOutput> passageExecute_23()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #24: noe4

	void passageInit_24()
	{
		this.Passages["noe4"] = new TwinePassage("noe4", new string[]{  }, passageExecute_24);
	}

	IEnumerable<TwineOutput> passageExecute_24()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #25: pat4

	void passageInit_25()
	{
		this.Passages["pat4"] = new TwinePassage("pat4", new string[]{  }, passageExecute_25);
	}

	IEnumerable<TwineOutput> passageExecute_25()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #26: john4

	void passageInit_26()
	{
		this.Passages["john4"] = new TwinePassage("john4", new string[]{  }, passageExecute_26);
	}

	IEnumerable<TwineOutput> passageExecute_26()
	{
		yield return new TwineText(@"#john_approval, +5#");
		yield return new TwineText(@"%1, <john>, <center>, <smile>%");
		yield return new TwineText(@"<i>Jane has the uncanny ability to make even the smallest of things into grand jokes, and over the course of the evening, this ability starts to rub off on you. </i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Eating with your ungainly claws becomes a source of laughter rather than embarrassment. </i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Your struggle with a spoonful of soup makes both ends of the table turn red in the face from laughing--not that your skin is really visible under all the fur.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>You're still laughing as you part ways.</i>");	
	}
    
	// .............
	// #27: hen5

	void passageInit_27()
	{
		this.Passages["hen5"] = new TwinePassage("hen5", new string[]{  }, passageExecute_27);
	}

	IEnumerable<TwineOutput> passageExecute_27()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #28: lucy5

	void passageInit_28()
	{
		this.Passages["lucy5"] = new TwinePassage("lucy5", new string[]{  }, passageExecute_28);
	}

	IEnumerable<TwineOutput> passageExecute_28()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #29: pat5

	void passageInit_29()
	{
		this.Passages["pat5"] = new TwinePassage("pat5", new string[]{  }, passageExecute_29);
	}

	IEnumerable<TwineOutput> passageExecute_29()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #30: noe5

	void passageInit_30()
	{
		this.Passages["noe5"] = new TwinePassage("noe5", new string[]{  }, passageExecute_30);
	}

	IEnumerable<TwineOutput> passageExecute_30()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #31: john5

	void passageInit_31()
	{
		this.Passages["john5"] = new TwinePassage("john5", new string[]{  }, passageExecute_31);
	}

	IEnumerable<TwineOutput> passageExecute_31()
	{
		yield return new TwineText(@"#john_approval, +5#");
		yield return new TwineText(@"%1, <john>, <center>, <smile>%");
		yield return new TwineText(@"<i>Jane has the uncanny ability to make even the smallest of things into grand jokes, and over the course of the evening, this ability starts to rub off on you. </i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Eating with your ungainly claws becomes a source of laughter rather than embarrassment. </i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Your struggle with a spoonful of soup makes both ends of the table turn red in the face from laughing--not that your skin is really visible under all the fur.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>You're still laughing as you part ways.</i>");	
	}
    
	// .............
	// #32: hen6

	void passageInit_32()
	{
		this.Passages["hen6"] = new TwinePassage("hen6", new string[]{  }, passageExecute_32);
	}

	IEnumerable<TwineOutput> passageExecute_32()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #33: pat6

	void passageInit_33()
	{
		this.Passages["pat6"] = new TwinePassage("pat6", new string[]{  }, passageExecute_33);
	}

	IEnumerable<TwineOutput> passageExecute_33()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #34: lucy6

	void passageInit_34()
	{
		this.Passages["lucy6"] = new TwinePassage("lucy6", new string[]{  }, passageExecute_34);
	}

	IEnumerable<TwineOutput> passageExecute_34()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #35: noe6

	void passageInit_35()
	{
		this.Passages["noe6"] = new TwinePassage("noe6", new string[]{  }, passageExecute_35);
	}

	IEnumerable<TwineOutput> passageExecute_35()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #36: john6

	void passageInit_36()
	{
		this.Passages["john6"] = new TwinePassage("john6", new string[]{  }, passageExecute_36);
	}

	IEnumerable<TwineOutput> passageExecute_36()
	{
		yield return new TwineText(@"#john_approval, +5#");
		yield return new TwineText(@"%1, <john>, <center>, <smile>%");
		yield return new TwineText(@"<i>Jane has the uncanny ability to make even the smallest of things into grand jokes, and over the course of the evening, this ability starts to rub off on you. </i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Eating with your ungainly claws becomes a source of laughter rather than embarrassment. </i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Your struggle with a spoonful of soup makes both ends of the table turn red in the face from laughing--not that your skin is really visible under all the fur.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>You're still laughing as you part ways.</i>");	
	}
    
	// .............
	// #37: hen7

	void passageInit_37()
	{
		this.Passages["hen7"] = new TwinePassage("hen7", new string[]{  }, passageExecute_37);
	}

	IEnumerable<TwineOutput> passageExecute_37()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #38: lucy7

	void passageInit_38()
	{
		this.Passages["lucy7"] = new TwinePassage("lucy7", new string[]{  }, passageExecute_38);
	}

	IEnumerable<TwineOutput> passageExecute_38()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #39: noe7

	void passageInit_39()
	{
		this.Passages["noe7"] = new TwinePassage("noe7", new string[]{  }, passageExecute_39);
	}

	IEnumerable<TwineOutput> passageExecute_39()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #40: pat7

	void passageInit_40()
	{
		this.Passages["pat7"] = new TwinePassage("pat7", new string[]{  }, passageExecute_40);
	}

	IEnumerable<TwineOutput> passageExecute_40()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #41: john7

	void passageInit_41()
	{
		this.Passages["john7"] = new TwinePassage("john7", new string[]{  }, passageExecute_41);
	}

	IEnumerable<TwineOutput> passageExecute_41()
	{
		yield return new TwineText(@"#john_approval, +5#");
		yield return new TwineText(@"%1, <john>, <center>, <smile>%");
		yield return new TwineText(@"<i>Jane has the uncanny ability to make even the smallest of things into grand jokes, and over the course of the evening, this ability starts to rub off on you. </i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Eating with your ungainly claws becomes a source of laughter rather than embarrassment. </i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Your struggle with a spoonful of soup makes both ends of the table turn red in the face from laughing--not that your skin is really visible under all the fur.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>You're still laughing as you part ways.</i>");	
	}

}