/*
Generated by UnityTwine on 4/29/2016 12:14:29 AM
https://github.com/daterre/UnityTwine
*/
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UnityTwine;

public class dinner: TwineStory
{
	public override TwineVar this[string name]
	{
		get
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
		set
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
	}


	void Awake() {
		base.Init();
		passageInit_0();
		passageInit_1();
		passageInit_2();
		passageInit_3();
		passageInit_4();
		passageInit_5();
		passageInit_6();
		passageInit_7();
		passageInit_8();
		passageInit_9();
		passageInit_10();
		passageInit_11();
		passageInit_12();
		passageInit_13();
		passageInit_14();
		passageInit_15();
		passageInit_16();
		passageInit_17();
		passageInit_18();
		passageInit_19();
		passageInit_20();
		passageInit_21();
		passageInit_22();
		passageInit_23();
		passageInit_24();
		passageInit_25();
		passageInit_26();
		passageInit_27();
	}
    
	// .............
	// #0: Start

	void passageInit_0()
	{
		this.Passages["Start"] = new TwinePassage("Start", new string[]{  }, passageExecute_0);
	}

	IEnumerable<TwineOutput> passageExecute_0()
	{
		yield return new TwineText(@"%1, <beau>, <center>, <smile>%");
		yield return new TwineText(@"BEAUREGARD: I'm so sorry to interrupt, but it's time for dinner, sire! ");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: Oh, how the time flies! Who woud you like to dine with this evening, sire?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"%noelle_approval, -30, 150%Noelle.", @"%noelle_approval, -30, 150%Noelle.", @"Noelle.", null, null);
		yield return new TwineLink(@"%jane_approval, -30, 150%Jane.", @"%jane_approval, -30, 150%Jane.", @"Jane.", null, null);
		yield return new TwineLink(@"%pat_approval, -30, 150%Patrice.", @"%pat_approval, -30, 150%Patrice.", @"Patrice.", null, null);
		yield return new TwineLink(@"%lucy_approval, -30, 150%Lucille.", @"%lucy_approval, -30, 150%Lucille.", @"Lucille.", null, null);
		yield return new TwineLink(@"%hen_approval, -30, 150%Henrietta.", @"%hen_approval, -30, 150%Henrietta.", @"Henrietta.", null, null);	
	}
    
	// .............
	// #1: No one.

	void passageInit_1()
	{
		this.Passages["No one."] = new TwinePassage("No one.", new string[]{  }, passageExecute_1);
	}

	IEnumerable<TwineOutput> passageExecute_1()
	{
		yield return new TwineText(@"%1, <beau>, <center>, <frown>%");
		yield return new TwineText(@"BEAUREGARD: Oh, yes. Ha ha. Very funny, sire. As if I would let you squander an opportunity like this!");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: Now, choose a dining companion or I'll do it for you!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Noelle.", @"Noelle.", @"Noelle.", null, null);
		yield return new TwineLink(@"Jane.", @"Jane.", @"Jane.", null, null);
		yield return new TwineLink(@"Patrice.", @"Patrice.", @"Patrice.", null, null);
		yield return new TwineLink(@"Lucille.", @"Lucille.", @"Lucille.", null, null);
		yield return new TwineLink(@"Henrietta.", @"Henrietta.", @"Henrietta.", null, null);	
	}
    
	// .............
	// #2: Henrietta.

	void passageInit_2()
	{
		this.Passages["Henrietta."] = new TwinePassage("Henrietta.", new string[]{  }, passageExecute_2);
	}

	IEnumerable<TwineOutput> passageExecute_2()
	{
		yield return new TwineText(@"%1, <beau>, <center>, <frown>%");
		yield return new TwineText(@"BEAUREGARD: Oh. The...lovely Miss Henrietta. Right. ");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <beau>, <center>, <neutral>%");
		yield return new TwineText(@"BEAUREGARD: Well, I'll, um. I suppose I'll set out some...hay? And remove the chair from the other end of the table...Oh, goodness.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"%hen_dinner, 0, 0%<i>The table is set.</i>", @"%hen_dinner, 0, 0%<i>The table is set.</i>", @"hen1", null, null);
		yield return new TwineLink(@"%hen_dinner, 1, 1%<i>The table is set.</i>", @"%hen_dinner, 1, 1%<i>The table is set.</i>", @"hen2", null, null);
		yield return new TwineLink(@"%hen_dinner, 2, 2%<i>The table is set.</i>", @"%hen_dinner, 2, 2%<i>The table is set.</i>", @"hen3", null, null);
		yield return new TwineLink(@"%hen_dinner, 3, 3%<i>The table is set.</i>", @"%hen_dinner, 3, 3%<i>The table is set.</i>", @"hen4", null, null);	
	}
    
	// .............
	// #3: Lucille.

	void passageInit_3()
	{
		this.Passages["Lucille."] = new TwinePassage("Lucille.", new string[]{  }, passageExecute_3);
	}

	IEnumerable<TwineOutput> passageExecute_3()
	{
		yield return new TwineText(@"%1, <beau>, <center>, <neutral>%");
		yield return new TwineText(@"BEAUREGARD: Miss Lucille. Well. That's certainly an...interesting choice.");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: I'll be sure to provide the table with plenty of wine tonight, sire. I hope the evening proves pleasant.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"%lucy_dinner, 0, 0%<i>The table is set.</i>", @"%lucy_dinner, 0, 0%<i>The table is set.</i>", @"lucy1", null, null);
		yield return new TwineLink(@"%lucy_dinner, 1, 1%<i>The table is set.</i>", @"%lucy_dinner, 1, 1%<i>The table is set.</i>", @"lucy2", null, null);
		yield return new TwineLink(@"%lucy_dinner, 2, 2%<i>The table is set.</i>", @"%lucy_dinner, 2, 2%<i>The table is set.</i>", @"lucy3", null, null);
		yield return new TwineLink(@"%lucy_dinner, 3, 3%<i>The table is set.</i>", @"%lucy_dinner, 3, 3%<i>The table is set.</i>", @"lucy4", null, null);	
	}
    
	// .............
	// #4: Noelle.

	void passageInit_4()
	{
		this.Passages["Noelle."] = new TwinePassage("Noelle.", new string[]{  }, passageExecute_4);
	}

	IEnumerable<TwineOutput> passageExecute_4()
	{
		yield return new TwineText(@"%1, <beau>, <center>, <smile>%");
		yield return new TwineText(@"BEAUREGARD: Ah, Miss Noelle. Perfect.");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: I'll get everything ready for you two. I'm sure it will be a perfectly pleasant evening!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"%noelle_dinner, 0, 0%<i>The table is set.</i>", @"%noelle_dinner, 0, 0%<i>The table is set.</i>", @"noe1", null, null);
		yield return new TwineLink(@"%noelle_dinner, 1, 1%<i>The table is set.</i>", @"%noelle_dinner, 1, 1%<i>The table is set.</i>", @"noe2", null, null);
		yield return new TwineLink(@"%noelle_dinner, 2, 2%<i>The table is set.</i>", @"%noelle_dinner, 2, 2%<i>The table is set.</i>", @"noe3", null, null);
		yield return new TwineLink(@"%noelle_dinner, 3, 3%<i>The table is set.</i>", @"%noelle_dinner, 3, 3%<i>The table is set.</i>", @"noe4", null, null);	
	}
    
	// .............
	// #5: Patrice.

	void passageInit_5()
	{
		this.Passages["Patrice."] = new TwinePassage("Patrice.", new string[]{  }, passageExecute_5);
	}

	IEnumerable<TwineOutput> passageExecute_5()
	{
		yield return new TwineText(@"%1, <beau>, <center>, <smile>%");
		yield return new TwineText(@"BEAUREGARD: Miss Patrice. A fine choice, sire.");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: I'll make sure everything is just perfect for this evening!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"%pat_dinner, 0, 0%<i>The table is set.</i>", @"%pat_dinner, 0, 0%<i>The table is set.</i>", @"pat1", null, null);
		yield return new TwineLink(@"%pat_dinner, 1, 1%<i>The table is set.</i>", @"%pat_dinner, 1, 1%<i>The table is set.</i>", @"pat2", null, null);
		yield return new TwineLink(@"%pat_dinner, 2, 2%<i>The table is set.</i>", @"%pat_dinner, 2, 2%<i>The table is set.</i>", @"pat3", null, null);
		yield return new TwineLink(@"%pat_dinner, 3, 3%<i>The table is set.</i>", @"%pat_dinner, 3, 3%<i>The table is set.</i>", @"pat4", null, null);	
	}
    
	// .............
	// #6: Jane.

	void passageInit_6()
	{
		this.Passages["Jane."] = new TwinePassage("Jane.", new string[]{  }, passageExecute_6);
	}

	IEnumerable<TwineOutput> passageExecute_6()
	{
		yield return new TwineText(@"%1, <beau>, <center>, <smile>%");
		yield return new TwineText(@"BEAUREGARD: Miss Jane! Lovely.");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: You dinner for two will be ready momentarily, sire!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"%john_dinner, 0, 0%<i>The table is set.</i>", @"%john_dinner, 0, 0%<i>The table is set.</i>", @"john1", null, null);
		yield return new TwineLink(@"%john_dinner, 1, 1%<i>The table is set.</i>", @"%john_dinner, 1, 1%<i>The table is set.</i>", @"john2", null, null);
		yield return new TwineLink(@"%john_dinner, 2, 2%<i>The table is set.</i>", @"%john_dinner, 2, 2%<i>The table is set.</i>", @"john3", null, null);
		yield return new TwineLink(@"%john_dinner, 3, 3%<i>The table is set.</i>", @"%john_dinner, 3, 3%<i>The table is set.</i>", @"john4", null, null);	
	}
    
	// .............
	// #7: hen1

	void passageInit_7()
	{
		this.Passages["hen1"] = new TwinePassage("hen1", new string[]{  }, passageExecute_7);
	}

	IEnumerable<TwineOutput> passageExecute_7()
	{
		yield return new TwineText(@"#hen_dinner, +1#");
		yield return new TwineText(@"#hen_approval, +5#");
		yield return new TwineText(@"%1, <hen>, <center>, <neutral>%");
		yield return new TwineText(@"<i>The evening is calm, and pleasant. The dining room's comfortable silence is broken only by the rhythmic sounds of a cow chewing her cud.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>You might be imagining it, but there seems to be a happy gleam to Miss Henrietta's eyes.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>You walk Henrietta back to the pastures outside as gallantly as a beast walking alongside a cow can.</i>");	
	}
    
	// .............
	// #8: lucy1

	void passageInit_8()
	{
		this.Passages["lucy1"] = new TwinePassage("lucy1", new string[]{  }, passageExecute_8);
	}

	IEnumerable<TwineOutput> passageExecute_8()
	{
		yield return new TwineText(@"#lucy_dinner, +1#");
		yield return new TwineText(@"#lucy_approval, +5#");
		yield return new TwineText(@"%1, <lucy>, <center>, <smile>%");
		yield return new TwineText(@"<i>It's a good thing Beauregard provided plenty of wine--Lucille goes straight for the glass bottles and starts knocking back drink after drink.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>As expected, her conversation is dry and acerbic--at least, it is at the start of the night. </i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>As the courses progress, you find that her comments have lost their biting edge. </i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Maybe it's just the wine that loosens the tight corners of her mouth, but you dare to think it might actually be your company.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>When you part ways for the night, her insults sound almost fond to your ears.</i>");	
	}
    
	// .............
	// #9: noe1

	void passageInit_9()
	{
		this.Passages["noe1"] = new TwinePassage("noe1", new string[]{  }, passageExecute_9);
	}

	IEnumerable<TwineOutput> passageExecute_9()
	{
		yield return new TwineText(@"#noelle_dinner, +1#");
		yield return new TwineText(@"#noelle_approval, +5#");
		yield return new TwineText(@"%1, <noelle>, <center>, <smile>%");
		yield return new TwineText(@"<i>As usual, the lady Noelle is the very picture of grace and poise. She handles herself with the air of one graciously bestowing her presence upon unworthy surroundings.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Nevertheless, you can't help but think she seems to become more comfortable over the course of the night.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>But then, you suppose making idle conversation about harmless topics while maintaining a comfortable physical distance would put anyone at ease. </i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>At the end of the night, you bid her a gallant farewell, and her smile appears almost genuine.</i>");	
	}
    
	// .............
	// #10: pat1

	void passageInit_10()
	{
		this.Passages["pat1"] = new TwinePassage("pat1", new string[]{  }, passageExecute_10);
	}

	IEnumerable<TwineOutput> passageExecute_10()
	{
		yield return new TwineText(@"#pat_dinner, +1#");
		yield return new TwineText(@"#pat_approval, +5#");
		yield return new TwineText(@"%1, <pat>, <center>, <smile>%");
		yield return new TwineText(@"<i>Pat is as kind and complimentary as always. Each course seems to amaze her more than the last, and it's clear that her pleased exclamations are sincere.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Pat always seems weighed down by something, distanced from the present by a problem no one else knows about. But tonight, bit by bit, her shoulders lift, and her expression lightens. </i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>When Beauregard's fancifully prepared dessert course makes her clap her hands and laugh delightedly, she looks years younger.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>You bow to her before she leaves for bed, and the smile she gives you is that of a bashful young girl.</i>");	
	}
    
	// .............
	// #11: john1

	void passageInit_11()
	{
		this.Passages["john1"] = new TwinePassage("john1", new string[]{  }, passageExecute_11);
	}

	IEnumerable<TwineOutput> passageExecute_11()
	{
		yield return new TwineText(@"#john_dinner, +1#");
		yield return new TwineText(@"#john_approval, +5#");
		yield return new TwineText(@"%1, <john>, <center>, <smile>%");
		yield return new TwineText(@"<i>Jane has the uncanny ability to make even the smallest of things into grand jokes, and over the course of the evening, this ability starts to rub off on you. </i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Eating with your ungainly claws becomes a source of laughter rather than embarrassment. </i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Your struggle with a spoonful of soup makes both ends of the table turn red in the face from laughing--not that your skin is really visible under all the fur.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>You're still laughing as you part ways.</i>");	
	}
    
	// .............
	// #12: hen2

	void passageInit_12()
	{
		this.Passages["hen2"] = new TwinePassage("hen2", new string[]{  }, passageExecute_12);
	}

	IEnumerable<TwineOutput> passageExecute_12()
	{
		yield return new TwineText(@"#hen_dinner, +1#");
		yield return new TwineText(@"#hen_approval, +5#");
		yield return new TwineText(@"%1, <hen>, <center>, <neutral>%");
		yield return new TwineText(@"<i>The evening is calm, and pleasant. The dining room's comfortable silence is broken only by the rhythmic sounds of a cow chewing her cud.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Henrietta gives a soft, grateful moo when you pile more hay and oats onto her plate.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Without Beauregard watching, you dare to pat her on the head before bidding her goodnight.</i>");	
	}
    
	// .............
	// #13: lucy2

	void passageInit_13()
	{
		this.Passages["lucy2"] = new TwinePassage("lucy2", new string[]{  }, passageExecute_13);
	}

	IEnumerable<TwineOutput> passageExecute_13()
	{
		yield return new TwineText(@"#lucy_dinner, +1#");
		yield return new TwineText(@"#lucy_approval, +5#");
		yield return new TwineText(@"%1, <lucy>, <center>, <smile>%");
		yield return new TwineText(@"<i>As expected, Lucille heads straight for the wine again. This time, at least, she pours it into a glass instead of drinking straight from the bottle.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>The conversation this time is much less biting on her end--maybe even something approaching casual, or fond.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>She might just be happily drunk, but the smile she gives you when you part ways is fond enough to make you feel pleasantly warm inside anyway.</i>");	
	}
    
	// .............
	// #14: noe2

	void passageInit_14()
	{
		this.Passages["noe2"] = new TwinePassage("noe2", new string[]{  }, passageExecute_14);
	}

	IEnumerable<TwineOutput> passageExecute_14()
	{
		yield return new TwineText(@"#noelle_dinner, +1#");
		yield return new TwineText(@"#noelle_approval, +5#");
		yield return new TwineText(@"%1, <noelle>, <center>, <smile>%");
		yield return new TwineText(@"<i>Noelle's curtsy is a little less frosty tonight.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>You imagine it must be easier to smile at a monster the more you look at it, and during your last dinner together she looked at you quite a lot.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Her gaze tonight is curious, even confused. Maybe she expects your manners to be more heathenish, or for you to make more difficult conversation. But you strive to be a gentleman.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Your efforts pay off when she offers you a cautious but genuine smile at the end of the night.</i>");	
	}
    
	// .............
	// #15: pat2

	void passageInit_15()
	{
		this.Passages["pat2"] = new TwinePassage("pat2", new string[]{  }, passageExecute_15);
	}

	IEnumerable<TwineOutput> passageExecute_15()
	{
		yield return new TwineText(@"#pat_dinner, +1#");
		yield return new TwineText(@"#pat_approval, +5#");
		yield return new TwineText(@"%1, <pat>, <center>, <smile>%");
		yield return new TwineText(@"<i>This time, with one dinner with you already under her belt, Pat is more comfortable at the start of the evening.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>She makes light but polite conversation during the whole of dinner, occasionally interrupting herself to marvel at the food. </i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>You bow to her before she leaves for bed, and the smile she gives you this time is shy and sweet.</i>");	
	}
    
	// .............
	// #16: john2

	void passageInit_16()
	{
		this.Passages["john2"] = new TwinePassage("john2", new string[]{  }, passageExecute_16);
	}

	IEnumerable<TwineOutput> passageExecute_16()
	{
		yield return new TwineText(@"#john_dinner, +1#");
		yield return new TwineText(@"#john_approval, +5#");
		yield return new TwineText(@"%1, <john>, <center>, <smile>%");
		yield return new TwineText(@"<i>Your second dinner with Jane is as entertaining as the first.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>You're prepared this time; it doesn't take long to slip back into the increasingly-familiar routine of hamming up your inability to eat with grace like a normal, claw-less human.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Jane's hysterical laughter follows you all the way back to your room.</i>");	
	}
    
	// .............
	// #17: hen3

	void passageInit_17()
	{
		this.Passages["hen3"] = new TwinePassage("hen3", new string[]{  }, passageExecute_17);
	}

	IEnumerable<TwineOutput> passageExecute_17()
	{
		yield return new TwineText(@"#hen_dinner, +1#");
		yield return new TwineText(@"#hen_approval, +5#");
		yield return new TwineText(@"%1, <hen>, <center>, <neutral>%");
		yield return new TwineText(@"<i>Henrietta eats with a grace and delicacy you can only dream of possessing. You wish, not for the first time, that you could cut out the middle man and eat straight from your plate, as she does.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Henrietta carries a conversation with you as well as any cow can--maybe even better than some humans. Her coy moos are music to your ears.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>It's a shame Henrietta can't take your arm as you walk her back to the pastures. You rest your hand on her back instead. She doesn't seem to mind.</i>");	
	}
    
	// .............
	// #18: lucy3

	void passageInit_18()
	{
		this.Passages["lucy3"] = new TwinePassage("lucy3", new string[]{  }, passageExecute_18);
	}

	IEnumerable<TwineOutput> passageExecute_18()
	{
		yield return new TwineText(@"#lucy_dinner, +1#");
		yield return new TwineText(@"#lucy_approval, +5#");
		yield return new TwineText(@"%1, <lucy>, <center>, <smile>%");
		yield return new TwineText(@"<i>The wine you've put out tonight is a white rather than the red she prefers, but aside from a raised eyebrow, Lucille downs it without complaint. You take this as a good sign.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>If you didn't know better, you'd say Lucille was almost glad to be dining with you. But you do know better, and so you know to take the pleasant conversation at face value.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Still, no matter the reason, the night is incredibly pleasant. You aren't even offended when she calls you a ""big lug"" during her farewell.</i>");	
	}
    
	// .............
	// #19: noe3

	void passageInit_19()
	{
		this.Passages["noe3"] = new TwinePassage("noe3", new string[]{  }, passageExecute_19);
	}

	IEnumerable<TwineOutput> passageExecute_19()
	{
		yield return new TwineText(@"#noelle_dinner, +1#");
		yield return new TwineText(@"#noelle_approval, +5#");
		yield return new TwineText(@"%1, <noelle>, <center>, <smile>%");
		yield return new TwineText(@"<i>Noelle seems almost comfortable, now. Sharing two dinners with you has done wonders for her tolerance of your appearance.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Still, you take care to keep the conversation light and easy; manners and formalities are clearly where Noelle feels most comfortable, and you would hate to ruin the mood.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>The low, exaggerated bow you give her while parting ways is received by a genuine, eye-sparkling smile.</i>");	
	}
    
	// .............
	// #20: pat3

	void passageInit_20()
	{
		this.Passages["pat3"] = new TwinePassage("pat3", new string[]{  }, passageExecute_20);
	}

	IEnumerable<TwineOutput> passageExecute_20()
	{
		yield return new TwineText(@"#pat_dinner, +1#");
		yield return new TwineText(@"#pat_approval, +5#");
		yield return new TwineText(@"%1, <pat>, <center>, <smile>%");
		yield return new TwineText(@"<i>Patrice smiles at you at the start of the evening, and when you give her a toothy smile in return, she doesn't recoil even a little bit. It's a startling indicator of process.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Conversation through dinner is warm and comfortable, but it's also very clear that you're both keeping the topics light so as not to hit upon any touchy subjects.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>When you part ways for the night, Patrice surprises you by dipping into a low curtsy before you can bow. Her smile is almost cheeky as she turns to leave.</i>");	
	}
    
	// .............
	// #21: john3

	void passageInit_21()
	{
		this.Passages["john3"] = new TwinePassage("john3", new string[]{  }, passageExecute_21);
	}

	IEnumerable<TwineOutput> passageExecute_21()
	{
		yield return new TwineText(@"#john_dinner, +1#");
		yield return new TwineText(@"#john_approval, +5#");
		yield return new TwineText(@"%1, <john>, <center>, <smile>%");
		yield return new TwineText(@"<i>Jane has a particularly playful spark in her eyes this evening, and as the courses are brought out, you understand why.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>It seems that tonight, Jane has made it her business to compete with you for the title of messiest eater. Loud slurps and chewing sounds fill the room.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Beauregard's face is dripping with distaste at your lack of manners, but with Jane's laughter filling your ears, you can't bring yourself to care.</i>");	
	}
    
	// .............
	// #22: john5

	void passageInit_22()
	{
		this.Passages["john5"] = new TwinePassage("john5", new string[]{  }, passageExecute_22);
	}

	IEnumerable<TwineOutput> passageExecute_22()
	{
		yield return new TwineText(@"#john_approval, +5#");
		yield return new TwineText(@"%1, <john>, <center>, <smile>%");
		yield return new TwineText(@"<i>By now, eating with Jane is as comfortable as eating by yourself. She isn't disgusted by your lack of table manners, or put off by your appetite for meat.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>She treats you as an equal at the dinner table, and you couldn't hope for anything better.</i>");	
	}
    
	// .............
	// #23: hen4

	void passageInit_23()
	{
		this.Passages["hen4"] = new TwinePassage("hen4", new string[]{  }, passageExecute_23);
	}

	IEnumerable<TwineOutput> passageExecute_23()
	{
		yield return new TwineText(@"#hen_approval, +5#");
		yield return new TwineText(@"%1, <hen>, <center>, <neutral>%");
		yield return new TwineText(@"<i>How did you even manage when you were unable to have dinner with Henrietta? You can't even imagine how awful it would be to return to such a life.<i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>You feel, once again, that you're the luckiest man in the world to get to enjoy such peaceful and cozy dinners. And with such a polite dinner guest, too.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Your goodbye to Henrietta is a paw softly combing through the hair at the back of her neck. She bats her eyes at you, and you force yourself to part from her and return to your room.</i>");	
	}
    
	// .............
	// #24: lucy4

	void passageInit_24()
	{
		this.Passages["lucy4"] = new TwinePassage("lucy4", new string[]{  }, passageExecute_24);
	}

	IEnumerable<TwineOutput> passageExecute_24()
	{
		yield return new TwineText(@"#lucy_approval, +5#");
		yield return new TwineText(@"%1, <lucy>, <center>, <smile>%");
		yield return new TwineText(@"<i>Lucille goes so far as to tip the wine bottle in your direction tonight, silently offering you the first drink. You decline--alcohol wreaks havoc on your cursed digestive system.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Tonight, Lucille is as light-hearted as you've ever heard her be. She laughs easily, makes several ridiculous toasts, and is generally good company.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>You dare to think, as you head back to your room, that it wasn't because of the wine.</i>");	
	}
    
	// .............
	// #25: noe4

	void passageInit_25()
	{
		this.Passages["noe4"] = new TwinePassage("noe4", new string[]{  }, passageExecute_25);
	}

	IEnumerable<TwineOutput> passageExecute_25()
	{
		yield return new TwineText(@"#noelle_approval, +5#");
		yield return new TwineText(@"%1, <noelle>, <center>, <smile>%");
		yield return new TwineText(@"<i>The Noelle at dinner tonight is almost unrecognizeable when compared to the Noelle you dined with for the first time. She smiles, makes light but witty conversation, and even laughs.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Your careful motions while eating do not go unnoticed; by now Noelle knows that your claws make it difficult for you to eat normally, and that you're making the effort for her.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Your toothy smile at the end of the night doesn't seem to bother her in the least, and that, more than anything, feels like a victory.</i>");	
	}
    
	// .............
	// #26: pat4

	void passageInit_26()
	{
		this.Passages["pat4"] = new TwinePassage("pat4", new string[]{  }, passageExecute_26);
	}

	IEnumerable<TwineOutput> passageExecute_26()
	{
		yield return new TwineText(@"#pat_approval, +5#");
		yield return new TwineText(@"%1, <pat>, <center>, <smile>%");
		yield return new TwineText(@"<i>Patrice smiles, and you smile back as the first course is brought out. Beauregard glances between the two of you in what he probably thinks is a sly manner.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>By now, Patrice is completely at ease during dinner, and you manage to discuss more personal and political topics. She listens and responds with a startling amount of thought.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Parting ways is comfortable, and easy--so comfortable that you go so far as to kiss her hand, in as gentlemanly a fashion as you can manage with a mouthful of fangs.</i>");	
	}
    
	// .............
	// #27: john4

	void passageInit_27()
	{
		this.Passages["john4"] = new TwinePassage("john4", new string[]{  }, passageExecute_27);
	}

	IEnumerable<TwineOutput> passageExecute_27()
	{
		yield return new TwineText(@"#john_approval, +5#");
		yield return new TwineText(@"%1, <john>, <center>, <smile>%");
		yield return new TwineText(@"<i>It's easy to forget your beastly appearance during the hours you spend at the dinner table with Jane.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>As usual, she is completely unfazed by your looks, and you find yourself playing up the growls and slurps you make while eating just to amuse her.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>When you go to bed that night, your cheeks hurt from smiling.</i>");	
	}

}