/*
Generated by UnityTwine on 4/3/2016 9:22:32 PM
https://github.com/daterre/UnityTwine
*/
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UnityTwine;

public class intro_noelle: TwineStory
{
	public override TwineVar this[string name]
	{
		get
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
		set
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
	}


	void Awake() {
		base.Init();
		passageInit_0();
		passageInit_1();
		passageInit_2();
		passageInit_3();
		passageInit_4();
		passageInit_5();
		passageInit_6();
		passageInit_7();
	}
    
	// .............
	// #0: Start

	void passageInit_0()
	{
		this.Passages["Start"] = new TwinePassage("Start", new string[]{  }, passageExecute_0);
	}

	IEnumerable<TwineOutput> passageExecute_0()
	{
		yield return new TwineText(@"%<1>, <noelle>, <center>, <smile>%");
		yield return new TwineText(@"NOELLE: Good morning, sire. My name is Noelle.");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAST: Good morning. You can refer to me as...");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Adam.", @"Adam.", @"Adam.", null, null);
		yield return new TwineLink(@"Prince Adam.", @"Prince Adam.", @"Prince Adam.", null, null);
		yield return new TwineLink(@"The Beast.", @"The Beast.", @"The Beast.", null, null);	
	}
    
	// .............
	// #1: StoryTitle

	void passageInit_1()
	{
		this.Passages["StoryTitle"] = new TwinePassage("StoryTitle", new string[]{  }, passageExecute_1);
	}

	IEnumerable<TwineOutput> passageExecute_1()
	{
		yield return new TwineText(@"Untitled Story");	
	}
    
	// .............
	// #2: Prince Adam.

	void passageInit_2()
	{
		this.Passages["Prince Adam."] = new TwinePassage("Prince Adam.", new string[]{  }, passageExecute_2);
	}

	IEnumerable<TwineOutput> passageExecute_2()
	{
		yield return new TwineText(@"NOELLE: What a lovely name. It's a pleasure to meet you, sire.");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: Thank you for inviting me to the castle. This is all so exciting!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I hope you enjoy yourself.", @"I hope you enjoy yourself.", @"I hope you enjoy yourself.", null, null);
		yield return new TwineLink(@"It wasn't my decision.", @"It wasn't my decision.", @"It wasn't my decision.", null, null);	
	}
    
	// .............
	// #3: Adam.

	void passageInit_3()
	{
		this.Passages["Adam."] = new TwinePassage("Adam.", new string[]{  }, passageExecute_3);
	}

	IEnumerable<TwineOutput> passageExecute_3()
	{
		yield return new TwineText(@"NOELLE: Adam. Lovely.");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: Thank you for inviting me to the castle. This is all so exciting!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I hope you enjoy yourself.", @"I hope you enjoy yourself.", @"I hope you enjoy yourself.", null, null);
		yield return new TwineLink(@"It wasn't my decision.", @"It wasn't my decision.", @"It wasn't my decision.", null, null);	
	}
    
	// .............
	// #4: The Beast.

	void passageInit_4()
	{
		this.Passages["The Beast."] = new TwinePassage("The Beast.", new string[]{  }, passageExecute_4);
	}

	IEnumerable<TwineOutput> passageExecute_4()
	{
		yield return new TwineText(@"#<noelleapproval>, <-5>#");
		yield return new TwineText(@"%<1>, <noelle>, <center>, <scared>%");
		yield return new TwineText(@"NOELLE: O-oh. Alright. Um, yes.");
		yield return new TwineText(@"");
		yield return new TwineText(@"%<1>, <noelle>, <center>, <smile>%");
		yield return new TwineText(@"NOELLE: Thank you for inviting me to the castle. This is all so exciting!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I hope you enjoy yourself.", @"I hope you enjoy yourself.", @"I hope you enjoy yourself.", null, null);
		yield return new TwineLink(@"It wasn't my decision.", @"It wasn't my decision.", @"It wasn't my decision.", null, null);	
	}
    
	// .............
	// #5: StoryAuthor

	void passageInit_5()
	{
		this.Passages["StoryAuthor"] = new TwinePassage("StoryAuthor", new string[]{  }, passageExecute_5);
	}

	IEnumerable<TwineOutput> passageExecute_5()
	{
		yield return new TwineText(@"Anonymous");	
	}
    
	// .............
	// #6: I hope you enjoy yourself.

	void passageInit_6()
	{
		this.Passages["I hope you enjoy yourself."] = new TwinePassage("I hope you enjoy yourself.", new string[]{  }, passageExecute_6);
	}

	IEnumerable<TwineOutput> passageExecute_6()
	{
		yield return new TwineText(@"#<noelleapproval>, <+5>#");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: I'm sure I will, sire. Thank you.");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: I look forward to our next conversation.");	
	}
    
	// .............
	// #7: It wasn't my decision.

	void passageInit_7()
	{
		this.Passages["It wasn't my decision."] = new TwinePassage("It wasn't my decision.", new string[]{  }, passageExecute_7);
	}

	IEnumerable<TwineOutput> passageExecute_7()
	{
		yield return new TwineText(@"#<noelleapproval>, <-5>#");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: ...Well. I'm sorry you feel inconvenienced by our presence, then.");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: If you'll excuse me, I think I need some fresh air.");	
	}

}