/*
Generated by UnityTwine on 04/03/2016 22:40:49
https://github.com/daterre/UnityTwine
*/
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UnityTwine;

public class intro_patrice: TwineStory
{
	public override TwineVar this[string name]
	{
		get
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
		set
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
	}


	void Awake() {
		base.Init();
		passageInit_0();
		passageInit_1();
		passageInit_2();
		passageInit_3();
		passageInit_4();
		passageInit_5();
		passageInit_6();
		passageInit_7();
	}
    
	// .............
	// #0: Start

	void passageInit_0()
	{
		this.Passages["Start"] = new TwinePassage("Start", new string[]{  }, passageExecute_0);
	}

	IEnumerable<TwineOutput> passageExecute_0()
	{
		yield return new TwineText(@"%<1>, <pat>, <center>, <neutral>%");
		yield return new TwineText(@"PATRICE: Good morning, your highness! I'm Patrice. But you can just call me Pat--everyone does.");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAST: You can call me...");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Adam.", @"Adam.", @"Adam.", null, null);
		yield return new TwineLink(@"Prince Adam.", @"Prince Adam.", @"Prince Adam.", null, null);
		yield return new TwineLink(@"The Beast.", @"The Beast.", @"The Beast.", null, null);	
	}
    
	// .............
	// #1: StoryTitle

	void passageInit_1()
	{
		this.Passages["StoryTitle"] = new TwinePassage("StoryTitle", new string[]{  }, passageExecute_1);
	}

	IEnumerable<TwineOutput> passageExecute_1()
	{
		yield return new TwineText(@"Untitled Story");	
	}
    
	// .............
	// #2: Prince Adam.

	void passageInit_2()
	{
		this.Passages["Prince Adam."] = new TwinePassage("Prince Adam.", new string[]{  }, passageExecute_2);
	}

	IEnumerable<TwineOutput> passageExecute_2()
	{
		yield return new TwineText(@"%<1>, <pat>, <center>, <surprise>%");
		yield return new TwineText(@"PATRICE: Oh, of course! I would never presume to call you otherwise.");
		yield return new TwineText(@"");
		yield return new TwineText(@"%<1>, <pat>, <center>, <smile>%");
		yield return new TwineText(@"PATRICE: Thank you for sending me that invitation. Things like this don't often happen to me.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Really? I find that surprising.", @"Really? I find that surprising.", @"Really? I find that surprising.", null, null);
		yield return new TwineLink(@"Of course. I've never found the lives of commoners to be particularly interesting.", @"Of course. I've never found the lives of commoners to be particularly interesting.", @"Of course. I've never found the lives of commoners to be particularly interesting.", null, null);	
	}
    
	// .............
	// #3: Adam.

	void passageInit_3()
	{
		this.Passages["Adam."] = new TwinePassage("Adam.", new string[]{  }, passageExecute_3);
	}

	IEnumerable<TwineOutput> passageExecute_3()
	{
		yield return new TwineText(@"#<patapproval>, <+5>#");
		yield return new TwineText(@"%<1>, <pat>, <center>, <smile>%");
		yield return new TwineText(@"PATRICE: Adam. What a lovely name.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: Thank you for sending me that invitation. Things like this don't often happen to me.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Really? I find that surprising.", @"Really? I find that surprising.", @"Really? I find that surprising.", null, null);
		yield return new TwineLink(@"Of course. I've never found the lives of commoners to be particularly interesting.", @"Of course. I've never found the lives of commoners to be particularly interesting.", @"Of course. I've never found the lives of commoners to be particularly interesting.", null, null);	
	}
    
	// .............
	// #4: The Beast.

	void passageInit_4()
	{
		this.Passages["The Beast."] = new TwinePassage("The Beast.", new string[]{  }, passageExecute_4);
	}

	IEnumerable<TwineOutput> passageExecute_4()
	{
		yield return new TwineText(@"#<patapproval>, <-5>#");
		yield return new TwineText(@"%<1>, <pat>, <center>, <scared>%");
		yield return new TwineText(@"PATRICE: ....Oh.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: Um. Of course, your highness. Er, Beast. Your...beastliness?");
		yield return new TwineText(@"");
		yield return new TwineText(@"%<1>, <pat>, <center>, <neutral>%");
		yield return new TwineText(@"PATRICE: Thank you for sending me that invitation. Things like this don't often happen to me.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Really? I find that surprising.", @"Really? I find that surprising.", @"Really? I find that surprising.", null, null);
		yield return new TwineLink(@"Of course. I've never found the lives of commoners to be particularly interesting.", @"Of course. I've never found the lives of commoners to be particularly interesting.", @"Of course. I've never found the lives of commoners to be particularly interesting.", null, null);	
	}
    
	// .............
	// #5: StoryAuthor

	void passageInit_5()
	{
		this.Passages["StoryAuthor"] = new TwinePassage("StoryAuthor", new string[]{  }, passageExecute_5);
	}

	IEnumerable<TwineOutput> passageExecute_5()
	{
		yield return new TwineText(@"Anonymous");	
	}
    
	// .............
	// #6: Really? I find that surprising.

	void passageInit_6()
	{
		this.Passages["Really? I find that surprising."] = new TwinePassage("Really? I find that surprising.", new string[]{  }, passageExecute_6);
	}

	IEnumerable<TwineOutput> passageExecute_6()
	{
		yield return new TwineText(@"#<patapproval>, <+5>#");
		yield return new TwineText(@"%<1>, <pat>, <center>, <blush>%");
		yield return new TwineText(@"PATRICE: That's very kind of you to say, sire, but I'm afraid my life compared to yours must seem very dull.");
		yield return new TwineText(@"");
		yield return new TwineText(@"%<1>, <pat>, <center>, <smile>%");
		yield return new TwineText(@"PATRICE: This castle is beautiful. I've never seen anything like it!");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: I really am glad to be here, sire. Thank you.");	
	}
    
	// .............
	// #7: Of course. I've never found the lives of commoners to be particularly interesting.

	void passageInit_7()
	{
		this.Passages["Of course. I've never found the lives of commoners to be particularly interesting."] = new TwinePassage("Of course. I've never found the lives of commoners to be particularly interesting.", new string[]{  }, passageExecute_7);
	}

	IEnumerable<TwineOutput> passageExecute_7()
	{
		yield return new TwineText(@"#<patapproval>, <-5>#");
		yield return new TwineText(@"%<1>, <pat>, <center>, <frown>%");
		yield return new TwineText(@"PATRICE: ...Of course, your majesty. I'm sure we must seem very dull in comparison.");
		yield return new TwineText(@"");
		yield return new TwineText(@"%<1>, <pat>, <center>, <neutral>%");
		yield return new TwineText(@"PATRICE: I really am glad to be here, sire. Thank you.");	
	}

}