/*
Generated by UnityTwine on 4/3/2016 8:17:21 PM
https://github.com/daterre/UnityTwine
*/
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UnityTwine;

public class intro_jane: TwineStory
{
	public override TwineVar this[string name]
	{
		get
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
		set
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
	}


	void Awake() {
		base.Init();
		passageInit_0();
		passageInit_1();
		passageInit_2();
		passageInit_3();
		passageInit_4();
		passageInit_5();
		passageInit_6();
		passageInit_7();
	}
    
	// .............
	// #0: Start

	void passageInit_0()
	{
		this.Passages["Start"] = new TwinePassage("Start", new string[]{  }, passageExecute_0);
	}

	IEnumerable<TwineOutput> passageExecute_0()
	{
		yield return new TwineText(@"%<1>, <john>, <center>, <neutral>%");
		yield return new TwineText(@"JANE: Hello, your highness. I'm Jane. ");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAST: Good morning. My name is...");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Adam.", @"Adam.", @"Adam.", null, null);
		yield return new TwineLink(@"Prince Adam.", @"Prince Adam.", @"Prince Adam.", null, null);
		yield return new TwineLink(@"The Beast.", @"The Beast.", @"The Beast.", null, null);	
	}
    
	// .............
	// #1: StoryTitle

	void passageInit_1()
	{
		this.Passages["StoryTitle"] = new TwinePassage("StoryTitle", new string[]{  }, passageExecute_1);
	}

	IEnumerable<TwineOutput> passageExecute_1()
	{
		yield return new TwineText(@"Untitled Story");	
	}
    
	// .............
	// #2: Prince Adam.

	void passageInit_2()
	{
		this.Passages["Prince Adam."] = new TwinePassage("Prince Adam.", new string[]{  }, passageExecute_2);
	}

	IEnumerable<TwineOutput> passageExecute_2()
	{
		yield return new TwineText(@"%<1>, <john>, <center>, <eyebrow>%");
		yield return new TwineText(@"JANE: Prince, huh? I can work with that.");
		yield return new TwineText(@"");
		yield return new TwineText(@"%<1>, <john>, <center>, <neutral>%");
		yield return new TwineText(@"JANE: So what is it you do in a huge castle like this all day, anyway?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Sit around moping, according to my butler.", @"Sit around moping, according to my butler.", @"Sit around moping, according to my butler.", null, null);
		yield return new TwineLink(@"A lot of reading, unfortunately.", @"A lot of reading, unfortunately.", @"A lot of reading, unfortunately.", null, null);	
	}
    
	// .............
	// #3: Adam.

	void passageInit_3()
	{
		this.Passages["Adam."] = new TwinePassage("Adam.", new string[]{  }, passageExecute_3);
	}

	IEnumerable<TwineOutput> passageExecute_3()
	{
		yield return new TwineText(@"#<johnapproval>, <+5>#");
		yield return new TwineText(@"%<1>, <john>, <center>, <eyebrow>%");
		yield return new TwineText(@"JANE: //Adam//. Huh. That's...surprisingly normal, I have to admit.");
		yield return new TwineText(@"");
		yield return new TwineText(@"%<1>, <john>, <center>, <neutral>%");
		yield return new TwineText(@"JANE: So what is it you do in a huge castle like this all day, anyway?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Sit around moping, according to my butler.", @"Sit around moping, according to my butler.", @"Sit around moping, according to my butler.", null, null);
		yield return new TwineLink(@"A lot of reading, unfortunately.", @"A lot of reading, unfortunately.", @"A lot of reading, unfortunately.", null, null);	
	}
    
	// .............
	// #4: The Beast.

	void passageInit_4()
	{
		this.Passages["The Beast."] = new TwinePassage("The Beast.", new string[]{  }, passageExecute_4);
	}

	IEnumerable<TwineOutput> passageExecute_4()
	{
		yield return new TwineText(@"%<1>, <john>, <center>, <eyebrow>%");
		yield return new TwineText(@"JANE: Jeez, okay. That's one way to make an impression.");
		yield return new TwineText(@"");
		yield return new TwineText(@"%<1>, <john>, <center>, <neutral>%");
		yield return new TwineText(@"JANE: So what is it you do in a huge castle like this all day, anyway?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Sit around moping, according to my butler.", @"Sit around moping, according to my butler.", @"Sit around moping, according to my butler.", null, null);
		yield return new TwineLink(@"A lot of reading, unfortunately.", @"A lot of reading, unfortunately.", @"A lot of reading, unfortunately.", null, null);	
	}
    
	// .............
	// #5: StoryAuthor

	void passageInit_5()
	{
		this.Passages["StoryAuthor"] = new TwinePassage("StoryAuthor", new string[]{  }, passageExecute_5);
	}

	IEnumerable<TwineOutput> passageExecute_5()
	{
		yield return new TwineText(@"Anonymous");	
	}
    
	// .............
	// #6: A lot of reading, unfortunately.

	void passageInit_6()
	{
		this.Passages["A lot of reading, unfortunately."] = new TwinePassage("A lot of reading, unfortunately.", new string[]{  }, passageExecute_6);
	}

	IEnumerable<TwineOutput> passageExecute_6()
	{
		yield return new TwineText(@"#<johnapproval>, <+5>#");
		yield return new TwineText(@"%<1>, <john>, <center>, <smile>%");
		yield return new TwineText(@"JOHN: Ha! I hear you. ");
		yield return new TwineText(@"");
		yield return new TwineText(@"JOHN: Well, I won't keep you from your other ladies-in-waiting any longer. It was nice to meet you.");	
	}
    
	// .............
	// #7: Sit around moping, according to my butler.

	void passageInit_7()
	{
		this.Passages["Sit around moping, according to my butler."] = new TwinePassage("Sit around moping, according to my butler.", new string[]{  }, passageExecute_7);
	}

	IEnumerable<TwineOutput> passageExecute_7()
	{
		yield return new TwineText(@"#<johnapproval>, <+5>#");
		yield return new TwineText(@"%<1>, <john>, <center>, <smile>%");
		yield return new TwineText(@"JOHN: Ha! That's a good one. I'll have to remember that. ");
		yield return new TwineText(@"");
		yield return new TwineText(@"JOHN: Well, I won't keep you from your other ladies-in-waiting any longer. It was nice to meet you.");	
	}

}