/*
Generated by UnityTwine on 4/25/2016 5:19:57 PM
https://github.com/daterre/UnityTwine
*/
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UnityTwine;

public class lucille_main: TwineStory
{
	public override TwineVar this[string name]
	{
		get
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
		set
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
	}


	void Awake() {
		base.Init();
		passageInit_0();
		passageInit_1();
		passageInit_2();
		passageInit_3();
		passageInit_4();
		passageInit_5();
		passageInit_6();
		passageInit_7();
		passageInit_8();
		passageInit_9();
		passageInit_10();
		passageInit_11();
		passageInit_12();
		passageInit_13();
		passageInit_14();
		passageInit_15();
		passageInit_16();
		passageInit_17();
		passageInit_18();
		passageInit_19();
		passageInit_20();
		passageInit_21();
		passageInit_22();
		passageInit_23();
		passageInit_24();
		passageInit_25();
		passageInit_26();
		passageInit_27();
		passageInit_28();
		passageInit_29();
		passageInit_30();
		passageInit_31();
		passageInit_32();
		passageInit_33();
		passageInit_34();
		passageInit_35();
		passageInit_36();
		passageInit_37();
		passageInit_38();
		passageInit_39();
		passageInit_40();
		passageInit_41();
		passageInit_42();
		passageInit_43();
		passageInit_44();
		passageInit_45();
		passageInit_46();
		passageInit_47();
		passageInit_48();
		passageInit_49();
		passageInit_50();
		passageInit_51();
		passageInit_52();
		passageInit_53();
		passageInit_54();
		passageInit_55();
		passageInit_56();
		passageInit_57();
		passageInit_58();
		passageInit_59();
		passageInit_60();
		passageInit_61();
		passageInit_62();
		passageInit_63();
		passageInit_64();
		passageInit_65();
		passageInit_66();
		passageInit_67();
		passageInit_68();
		passageInit_69();
		passageInit_70();
		passageInit_71();
		passageInit_72();
		passageInit_73();
		passageInit_74();
	}
    
	// .............
	// #0: stay4

	void passageInit_0()
	{
		this.Passages["stay4"] = new TwinePassage("stay4", new string[]{  }, passageExecute_0);
	}

	IEnumerable<TwineOutput> passageExecute_0()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <smile>%");
		yield return new TwineText(@"LUCILLE: Not sure how you managed it, but I'm...comfortable. Here, I mean.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: Feels wrong to image leaving, now. I suppose that's what you wanted, huh, you sly bastard?");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: What now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I want to hear your opinion of the other women staying in the castle.", @"I want to hear your opinion of the other women staying in the castle.", @"women", null, null);
		yield return new TwineLink(@"convo_points, 1, 2%Let's talk about you.", @"convo_points, 1, 2%Let's talk about you.", @"you", null, null);	
	}
    
	// .............
	// #1: stay3

	void passageInit_1()
	{
		this.Passages["stay3"] = new TwinePassage("stay3", new string[]{  }, passageExecute_1);
	}

	IEnumerable<TwineOutput> passageExecute_1()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: It's honestly starting to feel a little cozy around here. Not something I'm used to, but I could see myself getting used to it. Maybe.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: What now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I want to hear your opinion of the other women staying in the castle.", @"I want to hear your opinion of the other women staying in the castle.", @"women", null, null);
		yield return new TwineLink(@"convo_points, 1, 2%Let's talk about you.", @"convo_points, 1, 2%Let's talk about you.", @"you", null, null);	
	}
    
	// .............
	// #2: stay2

	void passageInit_2()
	{
		this.Passages["stay2"] = new TwinePassage("stay2", new string[]{  }, passageExecute_2);
	}

	IEnumerable<TwineOutput> passageExecute_2()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: I don't hate it as much as I thought I would. And that's as close to a compliment as you'll be getting from me.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: What now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I want to hear your opinion of the other women staying in the castle.", @"I want to hear your opinion of the other women staying in the castle.", @"women", null, null);
		yield return new TwineLink(@"convo_points, 1, 2%Let's talk about you.", @"convo_points, 1, 2%Let's talk about you.", @"you", null, null);	
	}
    
	// .............
	// #3: stay1

	void passageInit_3()
	{
		this.Passages["stay1"] = new TwinePassage("stay1", new string[]{  }, passageExecute_3);
	}

	IEnumerable<TwineOutput> passageExecute_3()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <frown>%");
		yield return new TwineText(@"LUCILLE: The place is certainly poncy enough for a prince to live in. I hate it.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: What now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I want to hear your opinion of the other women staying in the castle.", @"I want to hear your opinion of the other women staying in the castle.", @"women", null, null);
		yield return new TwineLink(@"convo_points, 1, 2%Let's talk about you.", @"convo_points, 1, 2%Let's talk about you.", @"you", null, null);	
	}
    
	// .............
	// #4: Start

	void passageInit_4()
	{
		this.Passages["Start"] = new TwinePassage("Start", new string[]{  }, passageExecute_4);
	}

	IEnumerable<TwineOutput> passageExecute_4()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <frown>%");
		yield return new TwineText(@"LUCILLE: Alright, so you found me. What do you want?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I want to hear your opinion of the other women staying in the castle.", @"I want to hear your opinion of the other women staying in the castle.", @"women", null, null);
		yield return new TwineLink(@"%lucy_approval,-30,0%How are you enjoying your stay here?", @"%lucy_approval,-30,0%How are you enjoying your stay here?", @"stay1", null, null);
		yield return new TwineLink(@"%lucy_approval,1,30%How are you enjoying your stay here?", @"%lucy_approval,1,30%How are you enjoying your stay here?", @"stay2", null, null);
		yield return new TwineLink(@"%lucy_approval,31,50%How are you enjoying your stay here?", @"%lucy_approval,31,50%How are you enjoying your stay here?", @"stay3", null, null);
		yield return new TwineLink(@"%lucy_approval,51,70%How are you enjoying your stay here?", @"%lucy_approval,51,70%How are you enjoying your stay here?", @"stay4", null, null);
		yield return new TwineLink(@"convo_points, 1, 2%Let's talk about you.", @"convo_points, 1, 2%Let's talk about you.", @"you", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}
    
	// .............
	// #5: h1

	void passageInit_5()
	{
		this.Passages["h1"] = new TwinePassage("h1", new string[]{  }, passageExecute_5);
	}

	IEnumerable<TwineOutput> passageExecute_5()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <smile>%");
		yield return new TwineText(@"LUCILLE: The cow? Hah! Yeah, like I spend a lot of time with her.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: What now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I want to hear your opinion of the other women staying in the castle.", @"I want to hear your opinion of the other women staying in the castle.", @"women", null, null);
		yield return new TwineLink(@"%lucy_approval,-30,0%How are you enjoying your stay here?", @"%lucy_approval,-30,0%How are you enjoying your stay here?", @"stay1", null, null);
		yield return new TwineLink(@"%lucy_approval,0,10%How are you enjoying your stay here?", @"%lucy_approval,0,10%How are you enjoying your stay here?", @"stay2", null, null);
		yield return new TwineLink(@"%lucy_approval,10,50%How are you enjoying your stay here?", @"%lucy_approval,10,50%How are you enjoying your stay here?", @"stay3", null, null);
		yield return new TwineLink(@"%lucy_approval,50,70%How are you enjoying your stay here?", @"%lucy_approval,50,70%How are you enjoying your stay here?", @"stay4", null, null);
		yield return new TwineLink(@"convo_points, 1, 2%Let's talk about you.", @"convo_points, 1, 2%Let's talk about you.", @"you", null, null);	
	}
    
	// .............
	// #6: h2

	void passageInit_6()
	{
		this.Passages["h2"] = new TwinePassage("h2", new string[]{  }, passageExecute_6);
	}

	IEnumerable<TwineOutput> passageExecute_6()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: Hen's a good one. A cow, but a good one. Doesn't care how much I swear, unlike some other people I could name.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: What now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I want to hear your opinion of the other women staying in the castle.", @"I want to hear your opinion of the other women staying in the castle.", @"women", null, null);
		yield return new TwineLink(@"%lucy_approval,-30,0%How are you enjoying your stay here?", @"%lucy_approval,-30,0%How are you enjoying your stay here?", @"stay1", null, null);
		yield return new TwineLink(@"%lucy_approval,0,10%How are you enjoying your stay here?", @"%lucy_approval,0,10%How are you enjoying your stay here?", @"stay2", null, null);
		yield return new TwineLink(@"%lucy_approval,10,50%How are you enjoying your stay here?", @"%lucy_approval,10,50%How are you enjoying your stay here?", @"stay3", null, null);
		yield return new TwineLink(@"%lucy_approval,50,70%How are you enjoying your stay here?", @"%lucy_approval,50,70%How are you enjoying your stay here?", @"stay4", null, null);
		yield return new TwineLink(@"convo_points, 1, 2%Let's talk about you.", @"convo_points, 1, 2%Let's talk about you.", @"you", null, null);	
	}
    
	// .............
	// #7: j1

	void passageInit_7()
	{
		this.Passages["j1"] = new TwinePassage("j1", new string[]{  }, passageExecute_7);
	}

	IEnumerable<TwineOutput> passageExecute_7()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: Jane and I haven't talked much yet, but I like her well enough. ");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: What now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I want to hear your opinion of the other women staying in the castle.", @"I want to hear your opinion of the other women staying in the castle.", @"women", null, null);
		yield return new TwineLink(@"%lucy_approval,-30,0%How are you enjoying your stay here?", @"%lucy_approval,-30,0%How are you enjoying your stay here?", @"stay1", null, null);
		yield return new TwineLink(@"%lucy_approval,0,10%How are you enjoying your stay here?", @"%lucy_approval,0,10%How are you enjoying your stay here?", @"stay2", null, null);
		yield return new TwineLink(@"%lucy_approval,10,50%How are you enjoying your stay here?", @"%lucy_approval,10,50%How are you enjoying your stay here?", @"stay3", null, null);
		yield return new TwineLink(@"%lucy_approval,50,70%How are you enjoying your stay here?", @"%lucy_approval,50,70%How are you enjoying your stay here?", @"stay4", null, null);
		yield return new TwineLink(@"convo_points, 1, 2%Let's talk about you.", @"convo_points, 1, 2%Let's talk about you.", @"you", null, null);	
	}
    
	// .............
	// #8: j2

	void passageInit_8()
	{
		this.Passages["j2"] = new TwinePassage("j2", new string[]{  }, passageExecute_8);
	}

	IEnumerable<TwineOutput> passageExecute_8()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <smile>%");
		yield return new TwineText(@"LUCILLE: Jane's great! She's someone who gets it. Really gets it. ");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: Too bad she doesn't have anything from home to remember her family by. Fuck knows I wouldn't want anything to remember mine by, but Jane's family is different. She misses them.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: What now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I want to hear your opinion of the other women staying in the castle.", @"I want to hear your opinion of the other women staying in the castle.", @"women", null, null);
		yield return new TwineLink(@"%lucy_approval,-30,0%How are you enjoying your stay here?", @"%lucy_approval,-30,0%How are you enjoying your stay here?", @"stay1", null, null);
		yield return new TwineLink(@"%lucy_approval,0,10%How are you enjoying your stay here?", @"%lucy_approval,0,10%How are you enjoying your stay here?", @"stay2", null, null);
		yield return new TwineLink(@"%lucy_approval,10,50%How are you enjoying your stay here?", @"%lucy_approval,10,50%How are you enjoying your stay here?", @"stay3", null, null);
		yield return new TwineLink(@"%lucy_approval,50,70%How are you enjoying your stay here?", @"%lucy_approval,50,70%How are you enjoying your stay here?", @"stay4", null, null);
		yield return new TwineLink(@"convo_points, 1, 2%Let's talk about you.", @"convo_points, 1, 2%Let's talk about you.", @"you", null, null);	
	}
    
	// .............
	// #9: women

	void passageInit_9()
	{
		this.Passages["women"] = new TwinePassage("women", new string[]{  }, passageExecute_9);
	}

	IEnumerable<TwineOutput> passageExecute_9()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <frown>%");
		yield return new TwineText(@"LUCILLE: Sure, fine, whatever. Shoot.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"%day, 1, 2%Jane.", @"%day, 1, 2%Jane.", @"j1", null, null);
		yield return new TwineLink(@"%day, 3, 6%Jane.", @"%day, 3, 6%Jane.", @"j2", null, null);
		yield return new TwineLink(@"%day, 1, 2%Pat.", @"%day, 1, 2%Pat.", @"p1", null, null);
		yield return new TwineLink(@"%day, 3, 6%Pat.", @"%day, 3, 6%Pat.", @"p2", null, null);
		yield return new TwineLink(@"%day, 1, 2%Noelle.", @"%day, 1, 2%Noelle.", @"n1", null, null);
		yield return new TwineLink(@"%day, 3, 6%Noelle.", @"%day, 3, 6%Noelle.", @"n2", null, null);
		yield return new TwineLink(@"%day, 1, 2%Henrietta.", @"%day, 1, 2%Henrietta.", @"h1", null, null);
		yield return new TwineLink(@"%day, 3, 6%Henrietta.", @"%day, 3, 6%Henrietta.", @"h2", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}
    
	// .............
	// #10: p1

	void passageInit_10()
	{
		this.Passages["p1"] = new TwinePassage("p1", new string[]{  }, passageExecute_10);
	}

	IEnumerable<TwineOutput> passageExecute_10()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: Pat? She's alright, I guess. Haven't really seen her much. But she always <i>smiles</i> at me. It's...weird.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: What now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I want to hear your opinion of the other women staying in the castle.", @"I want to hear your opinion of the other women staying in the castle.", @"women", null, null);
		yield return new TwineLink(@"%lucy_approval,-30,0%How are you enjoying your stay here?", @"%lucy_approval,-30,0%How are you enjoying your stay here?", @"stay1", null, null);
		yield return new TwineLink(@"%lucy_approval,0,10%How are you enjoying your stay here?", @"%lucy_approval,0,10%How are you enjoying your stay here?", @"stay2", null, null);
		yield return new TwineLink(@"%lucy_approval,10,50%How are you enjoying your stay here?", @"%lucy_approval,10,50%How are you enjoying your stay here?", @"stay3", null, null);
		yield return new TwineLink(@"%lucy_approval,50,70%How are you enjoying your stay here?", @"%lucy_approval,50,70%How are you enjoying your stay here?", @"stay4", null, null);
		yield return new TwineLink(@"convo_points, 1, 2%Let's talk about you.", @"convo_points, 1, 2%Let's talk about you.", @"you", null, null);	
	}
    
	// .............
	// #11: p2

	void passageInit_11()
	{
		this.Passages["p2"] = new TwinePassage("p2", new string[]{  }, passageExecute_11);
	}

	IEnumerable<TwineOutput> passageExecute_11()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: Pat's a good sort. Just...nice. She tries to mother me sometimes, though. I could do without that.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: What now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I want to hear your opinion of the other women staying in the castle.", @"I want to hear your opinion of the other women staying in the castle.", @"women", null, null);
		yield return new TwineLink(@"%lucy_approval,-30,0%How are you enjoying your stay here?", @"%lucy_approval,-30,0%How are you enjoying your stay here?", @"stay1", null, null);
		yield return new TwineLink(@"%lucy_approval,0,10%How are you enjoying your stay here?", @"%lucy_approval,0,10%How are you enjoying your stay here?", @"stay2", null, null);
		yield return new TwineLink(@"%lucy_approval,10,50%How are you enjoying your stay here?", @"%lucy_approval,10,50%How are you enjoying your stay here?", @"stay3", null, null);
		yield return new TwineLink(@"%lucy_approval,50,70%How are you enjoying your stay here?", @"%lucy_approval,50,70%How are you enjoying your stay here?", @"stay4", null, null);
		yield return new TwineLink(@"convo_points, 1, 2%Let's talk about you.", @"convo_points, 1, 2%Let's talk about you.", @"you", null, null);	
	}
    
	// .............
	// #12: n1

	void passageInit_12()
	{
		this.Passages["n1"] = new TwinePassage("n1", new string[]{  }, passageExecute_12);
	}

	IEnumerable<TwineOutput> passageExecute_12()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <frown>%");
		yield return new TwineText(@"LUCILLE: Noelle smiles a lot, but she doesn't mean it. I don't trust her. And her face goes all sharp when I swear around her.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: What now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I want to hear your opinion of the other women staying in the castle.", @"I want to hear your opinion of the other women staying in the castle.", @"women", null, null);
		yield return new TwineLink(@"%lucy_approval,-30,0%How are you enjoying your stay here?", @"%lucy_approval,-30,0%How are you enjoying your stay here?", @"stay1", null, null);
		yield return new TwineLink(@"%lucy_approval,0,10%How are you enjoying your stay here?", @"%lucy_approval,0,10%How are you enjoying your stay here?", @"stay2", null, null);
		yield return new TwineLink(@"%lucy_approval,10,50%How are you enjoying your stay here?", @"%lucy_approval,10,50%How are you enjoying your stay here?", @"stay3", null, null);
		yield return new TwineLink(@"%lucy_approval,50,70%How are you enjoying your stay here?", @"%lucy_approval,50,70%How are you enjoying your stay here?", @"stay4", null, null);
		yield return new TwineLink(@"convo_points, 1, 2%Let's talk about you.", @"convo_points, 1, 2%Let's talk about you.", @"you", null, null);	
	}
    
	// .............
	// #13: n2

	void passageInit_13()
	{
		this.Passages["n2"] = new TwinePassage("n2", new string[]{  }, passageExecute_13);
	}

	IEnumerable<TwineOutput> passageExecute_13()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: Noelle's...I don't know. She's weird. Doesn't mean what she says half the time, but...");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: I don't know. Nevermind.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: What now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I want to hear your opinion of the other women staying in the castle.", @"I want to hear your opinion of the other women staying in the castle.", @"women", null, null);
		yield return new TwineLink(@"%lucy_approval,-30,0%How are you enjoying your stay here?", @"%lucy_approval,-30,0%How are you enjoying your stay here?", @"stay1", null, null);
		yield return new TwineLink(@"%lucy_approval,0,10%How are you enjoying your stay here?", @"%lucy_approval,0,10%How are you enjoying your stay here?", @"stay2", null, null);
		yield return new TwineLink(@"%lucy_approval,10,50%How are you enjoying your stay here?", @"%lucy_approval,10,50%How are you enjoying your stay here?", @"stay3", null, null);
		yield return new TwineLink(@"%lucy_approval,50,70%How are you enjoying your stay here?", @"%lucy_approval,50,70%How are you enjoying your stay here?", @"stay4", null, null);
		yield return new TwineLink(@"convo_points, 1, 2%Let's talk about you.", @"convo_points, 1, 2%Let's talk about you.", @"you", null, null);	
	}
    
	// .............
	// #14: fam

	void passageInit_14()
	{
		this.Passages["fam"] = new TwinePassage("fam", new string[]{  }, passageExecute_14);
	}

	IEnumerable<TwineOutput> passageExecute_14()
	{
		yield return new TwineText(@"#convo_points, -1#");
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: Nothing interesting to say on that subject. I've got a mother and a father, same as most people.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"That's it? No siblings?", @"That's it? No siblings?", @"That's it? No siblings?", null, null);
		yield return new TwineLink(@"That must be nice.", @"That must be nice.", @"That must be nice.", null, null);
		yield return new TwineLink(@"Tell me about them.", @"Tell me about them.", @"Tell me about them.", null, null);	
	}
    
	// .............
	// #15: you

	void passageInit_15()
	{
		this.Passages["you"] = new TwinePassage("you", new string[]{  }, passageExecute_15);
	}

	IEnumerable<TwineOutput> passageExecute_15()
	{
		yield return new TwineText(@"LUCILLE: Alright, fine. But make it quick.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"%lucy_convo, 0, 0%Where are you from?", @"%lucy_convo, 0, 0%Where are you from?", @"from", null, null);
		yield return new TwineLink(@"%lucy_convo, 1, 1%What's your family like?", @"%lucy_convo, 1, 1%What's your family like?", @"fam", null, null);
		yield return new TwineLink(@"%lucy_convo, 2, 2%If you could go anywhere in the world, where would you go?", @"%lucy_convo, 2, 2%If you could go anywhere in the world, where would you go?", @"world", null, null);
		yield return new TwineLink(@"%lucy_convo, 3, 3%Is there a reason you drink so much?", @"%lucy_convo, 3, 3%Is there a reason you drink so much?", @"drink", null, null);
		yield return new TwineLink(@"%lucy_convo, 4, 4%Were you like this as a kid?", @"%lucy_convo, 4, 4%Were you like this as a kid?", @"kid", null, null);
		yield return new TwineLink(@"%lucy_convo, 5, 5%What were your friends like, back home?", @"%lucy_convo, 5, 5%What were your friends like, back home?", @"friends", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}
    
	// .............
	// #16: Tell me about them.

	void passageInit_16()
	{
		this.Passages["Tell me about them."] = new TwinePassage("Tell me about them.", new string[]{  }, passageExecute_16);
	}

	IEnumerable<TwineOutput> passageExecute_16()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: I thought I already had.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: But fine, since you asked--my mum's a nice, upright citizen, and my father's a hard-working farmer.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: What about you, Prince Lonesome?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Wow. You really got me, there.", @"Wow. You really got me, there.", @"sarcasm1", null, null);
		yield return new TwineLink(@"I was just curious.", @"I was just curious.", @"That wasn't an attack. I was just curious.", null, null);
		yield return new TwineLink(@"Do you always have to be so rude?", @"Do you always have to be so rude?", @"Do you always have to be so rude?", null, null);	
	}
    
	// .............
	// #17: That must be nice.

	void passageInit_17()
	{
		this.Passages["That must be nice."] = new TwinePassage("That must be nice.", new string[]{  }, passageExecute_17);
	}

	IEnumerable<TwineOutput> passageExecute_17()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: Oh, did talking about my family hit a sore spot? Maybe you shouldn't have asked, then.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Wow. You really got me, there.", @"Wow. You really got me, there.", @"sarcasm1", null, null);
		yield return new TwineLink(@"I was just curious.", @"I was just curious.", @"That wasn't an attack. I was just curious.", null, null);
		yield return new TwineLink(@"Do you always have to be so rude?", @"Do you always have to be so rude?", @"Do you always have to be so rude?", null, null);	
	}
    
	// .............
	// #18: That's it? No siblings?

	void passageInit_18()
	{
		this.Passages["That's it? No siblings?"] = new TwinePassage("That's it? No siblings?", new string[]{  }, passageExecute_18);
	}

	IEnumerable<TwineOutput> passageExecute_18()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <frown>%");
		yield return new TwineText(@"LUCILLE: Sorry if that seems boring to you. But I haven't seen any other poncy gits running around here, either. So you have no room to talk.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Wow. Bringing up how alone I am. You really got me.", @"Wow. Bringing up how alone I am. You really got me.", @"sarcasm1", null, null);
		yield return new TwineLink(@"That wasn't an attack. I was just curious.", @"That wasn't an attack. I was just curious.", @"That wasn't an attack. I was just curious.", null, null);
		yield return new TwineLink(@"You must be really close to your parents, then.", @"You must be really close to your parents, then.", @"You must be really close to your parents, then.", null, null);	
	}
    
	// .............
	// #19: drink

	void passageInit_19()
	{
		this.Passages["drink"] = new TwinePassage("drink", new string[]{  }, passageExecute_19);
	}

	IEnumerable<TwineOutput> passageExecute_19()
	{
		yield return new TwineText(@"#convo_points, -1#");
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: You mean other than the fact that I'm at the mercy of a complete stranger? No, none at all.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"The sarcasm's a little much, don't you think?", @"The sarcasm's a little much, don't you think?", @"The sarcasm's a little much, don't you think?", null, null);
		yield return new TwineLink(@"A straight answer would be nice.", @"A straight answer would be nice.", @"A straight answer would be nice.", null, null);
		yield return new TwineLink(@"At least my wine cellar is being put to good use.", @"At least my wine cellar is being put to good use.", @"At least my wine cellar is being put to good use.", null, null);	
	}
    
	// .............
	// #20: from

	void passageInit_20()
	{
		this.Passages["from"] = new TwinePassage("from", new string[]{  }, passageExecute_20);
	}

	IEnumerable<TwineOutput> passageExecute_20()
	{
		yield return new TwineText(@"#convo_points, -1#");
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: Oldbridge. You probably haven't heard of it. It's mostly just a bunch of farms.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"You're a farm girl, then!", @"You're a farm girl, then!", @"You're a farm girl, then!", null, null);
		yield return new TwineLink(@"And there's an old bridge somewhere among those farms?", @"And there's an old bridge somewhere among those farms?", @"And there's an old bridge somewhere among those farms?", null, null);
		yield return new TwineLink(@"Have you ever wanted to live anywhere else?", @"Have you ever wanted to live anywhere else?", @"Have you ever wanted to live anywhere else?", null, null);	
	}
    
	// .............
	// #21: At least my wine cellar is being put to good use.

	void passageInit_21()
	{
		this.Passages["At least my wine cellar is being put to good use."] = new TwinePassage("At least my wine cellar is being put to good use.", new string[]{  }, passageExecute_21);
	}

	IEnumerable<TwineOutput> passageExecute_21()
	{
		yield return new TwineText(@"#lucy_approval, +5#");
		yield return new TwineText(@"%1, <lucy>, <center>, <smile>%");
		yield return new TwineText(@"LUCILLE: You're telling me! There are some great vintages in here. ");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: Didn't you ever drink any of this stuff? How long have you been living here?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I tried once. My anatomy doesn't react well to alcohol.", @"I tried once. My anatomy doesn't react well to alcohol.", @"I tried once. My anatomy doesn't react well to alcohol.", null, null);
		yield return new TwineLink(@"Too long.", @"Too long.", @"Too long.", null, null);	
	}
    
	// .............
	// #22: The sarcasm's a little much, don't you think?

	void passageInit_22()
	{
		this.Passages["The sarcasm's a little much, don't you think?"] = new TwinePassage("The sarcasm's a little much, don't you think?", new string[]{  }, passageExecute_22);
	}

	IEnumerable<TwineOutput> passageExecute_22()
	{
		yield return new TwineText(@"#lucy_approval, -5#");
		yield return new TwineText(@"%1, <lucy>, <center>, <frown>%");
		yield return new TwineText(@"LUCILLE: Sorry, is your <i>prisoner's</i> behavior rubbing you the wrong way?");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: If you want to blame someone for my being here, you should try looking in a mirror sometime. Although, I can't blame you for not wanting to.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I've had years to get used to this face.", @"I've had years to get used to this face.", @"Too long.", null, null);
		yield return new TwineLink(@"Actually, my butler's to blame.", @"Actually, my butler's to blame.", @"It was his idea.", null, null);	
	}
    
	// .............
	// #23: A straight answer would be nice.

	void passageInit_23()
	{
		this.Passages["A straight answer would be nice."] = new TwinePassage("A straight answer would be nice.", new string[]{  }, passageExecute_23);
	}

	IEnumerable<TwineOutput> passageExecute_23()
	{
		yield return new TwineText(@"#lucy_approval, -5#");
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: We all want things. Most of us just get used to disappointment.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: After all, not all of us have butlers at our beck and call, ready to grant our every whim.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: Like forcing young women to come to a stranger's castle, for instance.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"It was his idea.]]
		[[It was a rash decision. I've been alone for so long...", @"It was his idea.]]
		[[It was a rash decision. I've been alone for so long...", @"Too long.", null, null);	
	}
    
	// .............
	// #24: Do you always have to be so rude?

	void passageInit_24()
	{
		this.Passages["Do you always have to be so rude?"] = new TwinePassage("Do you always have to be so rude?", new string[]{  }, passageExecute_24);
	}

	IEnumerable<TwineOutput> passageExecute_24()
	{
		yield return new TwineText(@"#lucy_approval, -5#");
		yield return new TwineText(@"%1, <lucy>, <center>, <smile>%");
		yield return new TwineText(@"LUCILLE: Sure do. Someone has to.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: It has the added effect of keeping people the hell away from me.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I can relate to that.]]
		[[So you don't want us to be...closer?", @"I can relate to that.]]
		[[So you don't want us to be...closer?", @"You mean all this time together isn't bringing us...closer?", null, null);	
	}
    
	// .............
	// #25: sarcasm1

	void passageInit_25()
	{
		this.Passages["sarcasm1"] = new TwinePassage("sarcasm1", new string[]{  }, passageExecute_25);
	}

	IEnumerable<TwineOutput> passageExecute_25()
	{
		yield return new TwineText(@"#lucy_approval, +5#");
		yield return new TwineText(@"%1, <lucy>, <center>, <smile>%");
		yield return new TwineText(@"LUCILLE: Hah. So there's a sense of humor under all that fur after all.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Making jokes about my fur, now? Seems like you're getting comfortable.", @"Making jokes about my fur, now? Seems like you're getting comfortable.", @"Making jokes about my fur, now? Seems like you're getting comfortable.", null, null);
		yield return new TwineLink(@"I was afraid I was getting rusty.", @"I was afraid I was getting rusty.", @"I was afraid I was getting rusty.", null, null);	
	}
    
	// .............
	// #26: That wasn't an attack. I was just curious.

	void passageInit_26()
	{
		this.Passages["That wasn't an attack. I was just curious."] = new TwinePassage("That wasn't an attack. I was just curious.", new string[]{  }, passageExecute_26);
	}

	IEnumerable<TwineOutput> passageExecute_26()
	{
		yield return new TwineText(@"#lucy_approval, -5#");
		yield return new TwineText(@"%1, <lucy>, <center>, <frown>%");
		yield return new TwineText(@"LUCILLE: Wow. You're a real buzzkill, huh? My mom'd love you. Well, maybe she would without all the fur.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Making jokes about my fur, now? Seems like you're getting comfortable.]]
		[[I'm not used to talking to people.", @"Making jokes about my fur, now? Seems like you're getting comfortable.]]
		[[I'm not used to talking to people.", @"I was afraid I was getting rusty.", null, null);	
	}
    
	// .............
	// #27: You must be really close to your parents, then.

	void passageInit_27()
	{
		this.Passages["You must be really close to your parents, then."] = new TwinePassage("You must be really close to your parents, then.", new string[]{  }, passageExecute_27);
	}

	IEnumerable<TwineOutput> passageExecute_27()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: As if people stuck alone in one place for years are bound to be best friends? Hmph.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: To answer your not-question: no. I'm not very close to my parents. I like my privacy.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I can relate to that.", @"I can relate to that.", @"I can relate to that.", null, null);
		yield return new TwineLink(@"Must be nice to have parents.", @"Must be nice to have parents.", @"Must be nice to have parents.", null, null);
		yield return new TwineLink(@"You mean all this time together isn't bringing us...closer?", @"You mean all this time together isn't bringing us...closer?", @"You mean all this time together isn't bringing us...closer?", null, null);	
	}
    
	// .............
	// #28: You're a farm girl, then!

	void passageInit_28()
	{
		this.Passages["You're a farm girl, then!"] = new TwinePassage("You're a farm girl, then!", new string[]{  }, passageExecute_28);
	}

	IEnumerable<TwineOutput> passageExecute_28()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <frown>%");
		yield return new TwineText(@"LUCILLE: Oh, yes, ha ha. Laugh all you want. I know it's funny, the idea of me working the fields. I was never suited for it.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: That's why I left home. Or, well, part of the reason.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"What's the rest of the reason?", @"What's the rest of the reason?", @"What's the rest of the reason?", null, null);
		yield return new TwineLink(@"So you <i>never</i> enjoyed life on a farm?", @"So you <i>never</i> enjoyed life on a farm?", @"So you <i>never</i> enjoyed life on a farm?", null, null);
		yield return new TwineLink(@"What would you rather be, then, instead of a farmer?", @"What would you rather be, then, instead of a farmer?", @"What would you rather be, then, instead of a farmer?", null, null);	
	}
    
	// .............
	// #29: And there's an old bridge somewhere among those farms?

	void passageInit_29()
	{
		this.Passages["And there's an old bridge somewhere among those farms?"] = new TwinePassage("And there's an old bridge somewhere among those farms?", new string[]{  }, passageExecute_29);
	}

	IEnumerable<TwineOutput> passageExecute_29()
	{
		yield return new TwineText(@"#lucy_approval, +5#");
		yield return new TwineText(@"%1, <lucy>, <center>, <smile>%");
		yield return new TwineText(@"LUCILLE: Sure enough. A big crumbling wooden thing. Its river is almost all dried up, so now it just sits over a field in the Landburys' fields.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: Made a fine play spot for me as a kid. I never did like farm work.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: That's why I left home. Or, well, part of the reason.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"What's the rest of the reason?", @"What's the rest of the reason?", @"What's the rest of the reason?", null, null);
		yield return new TwineLink(@"So you <i>never</i> enjoyed life on a farm?", @"So you <i>never</i> enjoyed life on a farm?", @"So you <i>never</i> enjoyed life on a farm?", null, null);
		yield return new TwineLink(@"What would you rather be, then, instead of a farmer?", @"What would you rather be, then, instead of a farmer?", @"What would you rather be, then, instead of a farmer?", null, null);	
	}
    
	// .............
	// #30: Have you ever wanted to live anywhere else?

	void passageInit_30()
	{
		this.Passages["Have you ever wanted to live anywhere else?"] = new TwinePassage("Have you ever wanted to live anywhere else?", new string[]{  }, passageExecute_30);
	}

	IEnumerable<TwineOutput> passageExecute_30()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <smile>%");
		yield return new TwineText(@"LUCILLE: Of course. What kid doesn't?");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: I never really fit in on the farm. Wasn't a homebody like all the other kids--most of them, anyway.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: That's why I left home. Or, well, part of the reason.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"What's the rest of the reason?", @"What's the rest of the reason?", @"What's the rest of the reason?", null, null);
		yield return new TwineLink(@"So you <i>never</i> enjoyed life on a farm?", @"So you <i>never</i> enjoyed life on a farm?", @"So you <i>never</i> enjoyed life on a farm?", null, null);
		yield return new TwineLink(@"What would you rather be, then, instead of a farmer?", @"What would you rather be, then, instead of a farmer?", @"What would you rather be, then, instead of a farmer?", null, null);	
	}
    
	// .............
	// #31: else

	void passageInit_31()
	{
		this.Passages["else"] = new TwinePassage("else", new string[]{  }, passageExecute_31);
	}

	IEnumerable<TwineOutput> passageExecute_31()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <smile>%");
		yield return new TwineText(@"LUCILLE: Of course, sire. What would you like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I want to hear your opinion of the other women staying in the castle.", @"I want to hear your opinion of the other women staying in the castle.", @"women", null, null);
		yield return new TwineLink(@"%lucy_approval,-30,0%How are you enjoying your stay here?", @"%lucy_approval,-30,0%How are you enjoying your stay here?", @"stay1", null, null);
		yield return new TwineLink(@"%lucy_approval,1,30%How are you enjoying your stay here?", @"%lucy_approval,1,30%How are you enjoying your stay here?", @"stay2", null, null);
		yield return new TwineLink(@"%lucy_approval,31,50%How are you enjoying your stay here?", @"%lucy_approval,31,50%How are you enjoying your stay here?", @"stay3", null, null);
		yield return new TwineLink(@"%lucy_approval,51,70%How are you enjoying your stay here?", @"%lucy_approval,51,70%How are you enjoying your stay here?", @"stay4", null, null);
		yield return new TwineLink(@"convo_points, 1, 2%Let's talk about you.", @"convo_points, 1, 2%Let's talk about you.", @"you", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}
    
	// .............
	// #32: %lucy_approval, 1, 30%Am I that bad to be around?

	void passageInit_32()
	{
		this.Passages["%lucy_approval, 1, 30%Am I that bad to be around?"] = new TwinePassage("%lucy_approval, 1, 30%Am I that bad to be around?", new string[]{  }, passageExecute_32);
	}

	IEnumerable<TwineOutput> passageExecute_32()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: Alright, fine. Maybe I was a <i>little</i> harsh.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: That doesn't mean I don't pity your butler.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: Can we talk about something else now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Sure.", @"Sure.", @"else", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}
    
	// .............
	// #33: What's the rest of the reason?

	void passageInit_33()
	{
		this.Passages["What's the rest of the reason?"] = new TwinePassage("What's the rest of the reason?", new string[]{  }, passageExecute_33);
	}

	IEnumerable<TwineOutput> passageExecute_33()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: Look at me. I'm not a young little spring chicken any more, and there aren't many eligible men walking around rural towns like Oldbridge.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: I was starting to become a financial sink for my parents to pour their money into. Or, at least, it felt that way.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: Our town had to send a girl, and I volunteered. Seemed like the best thing for everyone.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"No one objected?", @"No one objected?", @"No one objected?", null, null);
		yield return new TwineLink(@"That's awfully altruistic.", @"That's awfully altruistic.", @"That's awfully altruistic.", null, null);
		yield return new TwineLink(@"I'm not sure I could've done that.", @"I'm not sure I could've done that.", @"I'm not sure I could've done that.", null, null);	
	}
    
	// .............
	// #34: So you <i>never</i> enjoyed life on a farm?

	void passageInit_34()
	{
		this.Passages["So you <i>never</i> enjoyed life on a farm?"] = new TwinePassage("So you <i>never</i> enjoyed life on a farm?", new string[]{  }, passageExecute_34);
	}

	IEnumerable<TwineOutput> passageExecute_34()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <frown>%");
		yield return new TwineText(@"LUCILLE: Well...");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: Maybe once or twice. The sky out there...it's amazing. Stretches on for miles.");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <lucy>, <center>, <frown>%");
		yield return new TwineText(@"LUCILLE: Of course, then I had to volunteer to come to this shithole. It's impossible to find your way outside. This place is like a maze.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"No one objected to you volunteering?", @"No one objected to you volunteering?", @"No one objected?", null, null);
		yield return new TwineLink(@"You volunteered? That's awfully altruistic.", @"You volunteered? That's awfully altruistic.", @"That's awfully altruistic.", null, null);
		yield return new TwineLink(@"I'm not sure if I would've volunteered, in your position.", @"I'm not sure if I would've volunteered, in your position.", @"I'm not sure I could've done that.", null, null);	
	}
    
	// .............
	// #35: What would you rather be, then, instead of a farmer?

	void passageInit_35()
	{
		this.Passages["What would you rather be, then, instead of a farmer?"] = new TwinePassage("What would you rather be, then, instead of a farmer?", new string[]{  }, passageExecute_35);
	}

	IEnumerable<TwineOutput> passageExecute_35()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: Who knows?");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: I never really had high goals like the few other people who left Oldbridge did. Maybe that's why I didn't make it out until now.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: Or maybe I was just lazy enough to volunteer so I could get out of doing farmwork for a week. Either way, I'm here.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"No one objected to you volunteering?", @"No one objected to you volunteering?", @"No one objected?", null, null);
		yield return new TwineLink(@"You volunteered? That's awfully altruistic.", @"You volunteered? That's awfully altruistic.", @"That's awfully altruistic.", null, null);
		yield return new TwineLink(@"I'm not sure if I would've volunteered, in your position.", @"I'm not sure if I would've volunteered, in your position.", @"I'm not sure I could've done that.", null, null);	
	}
    
	// .............
	// #36: I tried once. My anatomy doesn't react well to alcohol.

	void passageInit_36()
	{
		this.Passages["I tried once. My anatomy doesn't react well to alcohol."] = new TwinePassage("I tried once. My anatomy doesn't react well to alcohol.", new string[]{  }, passageExecute_36);
	}

	IEnumerable<TwineOutput> passageExecute_36()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: Oh, right. You've got...different bits inside. ");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: If you ask me, that's the worst curse imaginable.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"You have no idea.]]
		[[Beauregard makes it easier.", @"You have no idea.]]
		[[Beauregard makes it easier.", @"He does make it easier.", null, null);
		yield return new TwineLink(@"I've missed female company more.", @"I've missed female company more.", @"It's not the same as having...female company.", null, null);	
	}
    
	// .............
	// #37: Too long.

	void passageInit_37()
	{
		this.Passages["Too long."] = new TwinePassage("Too long.", new string[]{  }, passageExecute_37);
	}

	IEnumerable<TwineOutput> passageExecute_37()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: Oh, right. Of course you've spent years alone in this castle, with no one else to talk to.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: Except, oh, I don't know--your butler?");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: Don't try to pull the tragic act when you've had another human literally waiting on you hand and foot. Or paw, whatever.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Beauregard has been my butler since birth.", @"Beauregard has been my butler since birth.", @"Beauregard has been my butler since birth.", null, null);
		yield return new TwineLink(@"He does make it easier.", @"He does make it easier.", @"He does make it easier.", null, null);
		yield return new TwineLink(@"It's not the same as having...female company.", @"It's not the same as having...female company.", @"It's not the same as having...female company.", null, null);	
	}
    
	// .............
	// #38: It was his idea.

	void passageInit_38()
	{
		this.Passages["It was his idea."] = new TwinePassage("It was his idea.", new string[]{  }, passageExecute_38);
	}

	IEnumerable<TwineOutput> passageExecute_38()
	{
		yield return new TwineText(@"#lucy_approval, -5#");
		yield return new TwineText(@"%1, <lucy>, <center>, <frown>%");
		yield return new TwineText(@"LUCILLE: Right, right! And you're just the lucky beneficiary. ");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: Give me a break.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I'm grateful for Beauregard's company every day.", @"I'm grateful for Beauregard's company every day.", @"He does make it easier.", null, null);
		yield return new TwineLink(@"I'm glad he made the decision to bring you here.", @"I'm glad he made the decision to bring you here.", @"It's not the same as having...female company.", null, null);	
	}
    
	// .............
	// #39: You mean all this time together isn't bringing us...closer?

	void passageInit_39()
	{
		this.Passages["You mean all this time together isn't bringing us...closer?"] = new TwinePassage("You mean all this time together isn't bringing us...closer?", new string[]{  }, passageExecute_39);
	}

	IEnumerable<TwineOutput> passageExecute_39()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <smile>%");
		yield return new TwineText(@"LUCILLE: Ha! No. And if that's your idea of a line, you've got a lot of work to do before you have a hope of impressing me.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: It has the added effect of keeping people the hell away from me.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I can relate to that.", @"I can relate to that.", @"I can relate to that.", null, null);
		yield return new TwineLink(@"So I do have a hope of impressing you, eventually.", @"So I do have a hope of impressing you, eventually.", @"So I do have a hope of impressing you, eventually.", null, null);	
	}
    
	// .............
	// #40: Making jokes about my fur, now? Seems like you're getting comfortable.

	void passageInit_40()
	{
		this.Passages["Making jokes about my fur, now? Seems like you're getting comfortable."] = new TwinePassage("Making jokes about my fur, now? Seems like you're getting comfortable.", new string[]{  }, passageExecute_40);
	}

	IEnumerable<TwineOutput> passageExecute_40()
	{
		yield return new TwineText(@"#lucy_approval, +5#");
		yield return new TwineText(@"%1, <lucy>, <center>, <smile>%");
		yield return new TwineText(@"LUCILLE: Despite my better judgement, yeah. I guess I am.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: Can we talk about something else now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Sure.", @"Sure.", @"else", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}
    
	// .............
	// #41: I was afraid I was getting rusty.

	void passageInit_41()
	{
		this.Passages["I was afraid I was getting rusty."] = new TwinePassage("I was afraid I was getting rusty.", new string[]{  }, passageExecute_41);
	}

	IEnumerable<TwineOutput> passageExecute_41()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <smile>%");
		yield return new TwineText(@"LUCILLE: Right, right. Sad little prince all alone in a big empty castle. Sure. I get it. Just keep playing that pity card, you ponce.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: Can we talk about something else now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Sure.", @"Sure.", @"else", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}
    
	// .............
	// #42: I can relate to that.

	void passageInit_42()
	{
		this.Passages["I can relate to that."] = new TwinePassage("I can relate to that.", new string[]{  }, passageExecute_42);
	}

	IEnumerable<TwineOutput> passageExecute_42()
	{
		yield return new TwineText(@"#lucy_approval, +5#");
		yield return new TwineText(@"%1, <lucy>, <center>, <smile>%");
		yield return new TwineText(@"LUCILLE: Ah, right. Big scary beast likes to run around alone in his big empty castle, scaring people away.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: I guess I don't really have any room to judge. Can we talk about something else now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Sure.", @"Sure.", @"else", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}
    
	// .............
	// #43: Must be nice to have parents.

	void passageInit_43()
	{
		this.Passages["Must be nice to have parents."] = new TwinePassage("Must be nice to have parents.", new string[]{  }, passageExecute_43);
	}

	IEnumerable<TwineOutput> passageExecute_43()
	{
		yield return new TwineText(@"#lucy_approval, -10#");
		yield return new TwineText(@"%1, <lucy>, <center>, <frown>%");
		yield return new TwineText(@"LUCILLE: Ugh. Spare me the pity party, will you? I don't have time for a poncy prince's tears.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: Can we talk about something else now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Sure.", @"Sure.", @"else", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}
    
	// .............
	// #44: %lucy_approval, -30, 0%Am I that bad to be around?

	void passageInit_44()
	{
		this.Passages["%lucy_approval, -30, 0%Am I that bad to be around?"] = new TwinePassage("%lucy_approval, -30, 0%Am I that bad to be around?", new string[]{  }, passageExecute_44);
	}

	IEnumerable<TwineOutput> passageExecute_44()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <frown>%");
		yield return new TwineText(@"LUCILLE: The short answer? Yes.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: Can we talk about something else now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Sure.", @"Sure.", @"else", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}
    
	// .............
	// #45: You have no idea.

	void passageInit_45()
	{
		this.Passages["You have no idea."] = new TwinePassage("You have no idea.", new string[]{  }, passageExecute_45);
	}

	IEnumerable<TwineOutput> passageExecute_45()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <frown>%");
		yield return new TwineText(@"LUCILLE: Alright, so clearly there's some layered meaning there that I'm not touching with a ten-foot pole.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: Can we talk about something else now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Sure.", @"Sure.", @"else", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}
    
	// .............
	// #46: It's not the same as having...female company.

	void passageInit_46()
	{
		this.Passages["It's not the same as having...female company."] = new TwinePassage("It's not the same as having...female company.", new string[]{  }, passageExecute_46);
	}

	IEnumerable<TwineOutput> passageExecute_46()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <smile>%");
		yield return new TwineText(@"LUCILLE: Ha! Was that supposed to be a line?");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: Besides, I'm not sure I qualify as ""female company"". None of the boys back home seemed to think so, anyway.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"They were very wrong.", @"They were very wrong.", @"They were very wrong.", null, null);
		yield return new TwineLink(@"And you were alright with that?", @"And you were alright with that?", @"And you were alright with that?", null, null);
		yield return new TwineLink(@"I can't imagine where they got that impression.", @"I can't imagine where they got that impression.", @"I can't imagine where they got that impression.", null, null);	
	}
    
	// .............
	// #47: He does make it easier.

	void passageInit_47()
	{
		this.Passages["He does make it easier."] = new TwinePassage("He does make it easier.", new string[]{  }, passageExecute_47);
	}

	IEnumerable<TwineOutput> passageExecute_47()
	{
		yield return new TwineText(@"#lucy_approval, +5#");
		yield return new TwineText(@"%1, <lucy>, <center>, <frown>%");
		yield return new TwineText(@"LUCILLE: I can only hope he feels the same way about having to spend all his time with you.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: Unlucky sod.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I told him he could leave whenever he wanted.", @"I told him he could leave whenever he wanted.", @"I told him he could leave whenever he wanted.", null, null);
		yield return new TwineLink(@"%lucy_approval, -30, 0%Am I that bad to be around?", @"%lucy_approval, -30, 0%Am I that bad to be around?", @"%lucy_approval, -30, 0%Am I that bad to be around?", null, null);
		yield return new TwineLink(@"%lucy_approval, 1, 30%Am I that bad to be around?", @"%lucy_approval, 1, 30%Am I that bad to be around?", @"%lucy_approval, 1, 30%Am I that bad to be around?", null, null);	
	}
    
	// .............
	// #48: Beauregard has been my butler since birth.

	void passageInit_48()
	{
		this.Passages["Beauregard has been my butler since birth."] = new TwinePassage("Beauregard has been my butler since birth.", new string[]{  }, passageExecute_48);
	}

	IEnumerable<TwineOutput> passageExecute_48()
	{
		yield return new TwineText(@"#lucy_approval, -5#");
		yield return new TwineText(@"%1, <lucy>, <center>, <frown>%");
		yield return new TwineText(@"LUCILLE: And I suppose that makes it all better?");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: I was raised to be a farmer, but look how well that turned out!");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: It doesn't matter what you were raised to do. You should still be able to make your own choices.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I told him he could leave whenever he wanted.", @"I told him he could leave whenever he wanted.", @"I told him he could leave whenever he wanted.", null, null);
		yield return new TwineLink(@"Why? I haven't been able to.", @"Why? I haven't been able to.", @"Why? I haven't been able to.", null, null);	
	}
    
	// .............
	// #49: No one objected?

	void passageInit_49()
	{
		this.Passages["No one objected?"] = new TwinePassage("No one objected?", new string[]{  }, passageExecute_49);
	}

	IEnumerable<TwineOutput> passageExecute_49()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: Not really.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: Look, can we just talk about something else now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Sure.", @"Sure.", @"else", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}
    
	// .............
	// #50: That's awfully altruistic.

	void passageInit_50()
	{
		this.Passages["That's awfully altruistic."] = new TwinePassage("That's awfully altruistic.", new string[]{  }, passageExecute_50);
	}

	IEnumerable<TwineOutput> passageExecute_50()
	{
		yield return new TwineText(@"#lucy_approval, +5#");
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: Yeah, well, don't go telling anyone about it.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: Can we talk about something else now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Sure.", @"Sure.", @"else", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}
    
	// .............
	// #51: I'm not sure I could've done that.

	void passageInit_51()
	{
		this.Passages["I'm not sure I could've done that."] = new TwinePassage("I'm not sure I could've done that.", new string[]{  }, passageExecute_51);
	}

	IEnumerable<TwineOutput> passageExecute_51()
	{
		yield return new TwineText(@"#lucy_approval, +5#");
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: It really wasn't a big deal. Someone had to go, and I was the best option.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: Can we talk about something else now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Sure.", @"Sure.", @"else", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}
    
	// .............
	// #52: So I do have a hope of impressing you, eventually.

	void passageInit_52()
	{
		this.Passages["So I do have a hope of impressing you, eventually."] = new TwinePassage("So I do have a hope of impressing you, eventually.", new string[]{  }, passageExecute_52);
	}

	IEnumerable<TwineOutput> passageExecute_52()
	{
		yield return new TwineText(@"#lucy_approval, +5#");
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: Slow down, there, loverboy. I may have volunteered for this, but that doesn't mean I'm looking forward to getting married.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: Can we talk about something else now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Sure.", @"Sure.", @"else", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}
    
	// .............
	// #53: Actually, I have to leave.

	void passageInit_53()
	{
		this.Passages["Actually, I have to leave."] = new TwinePassage("Actually, I have to leave.", new string[]{  }, passageExecute_53);
	}

	IEnumerable<TwineOutput> passageExecute_53()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <smile>%");
		yield return new TwineText(@"LUCILLE: Of course. I hope you have a pleasant day, sire.");	
	}
    
	// .............
	// #54: And you were alright with that?

	void passageInit_54()
	{
		this.Passages["And you were alright with that?"] = new TwinePassage("And you were alright with that?", new string[]{  }, passageExecute_54);
	}

	IEnumerable<TwineOutput> passageExecute_54()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: Well, sure. I guess.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: I never knew anything different, anyway.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: Can we talk about something else now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Sure.", @"Sure.", @"else", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}
    
	// .............
	// #55: I can't imagine where they got that impression.

	void passageInit_55()
	{
		this.Passages["I can't imagine where they got that impression."] = new TwinePassage("I can't imagine where they got that impression.", new string[]{  }, passageExecute_55);
	}

	IEnumerable<TwineOutput> passageExecute_55()
	{
		yield return new TwineText(@"#lucy_approval, -5#");
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: Ha ha. Yes, I know. I'm not exactly the most feminine person on the earth. Everyone in my life has made that <i>abundantly</i> clear already.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: Can we talk about something else now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Sure.", @"Sure.", @"else", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}
    
	// .............
	// #56: They were very wrong.

	void passageInit_56()
	{
		this.Passages["They were very wrong."] = new TwinePassage("They were very wrong.", new string[]{  }, passageExecute_56);
	}

	IEnumerable<TwineOutput> passageExecute_56()
	{
		yield return new TwineText(@"#lucy_approval, +5#");
		yield return new TwineText(@"%1, <lucy>, <center>, <blush>%");
		yield return new TwineText(@"LUCILLE: Alright, calm down. There's no need for you to spout vapid flattery.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: Can we talk about something else now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Sure.", @"Sure.", @"else", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}
    
	// .............
	// #57: I told him he could leave whenever he wanted.

	void passageInit_57()
	{
		this.Passages["I told him he could leave whenever he wanted."] = new TwinePassage("I told him he could leave whenever he wanted.", new string[]{  }, passageExecute_57);
	}

	IEnumerable<TwineOutput> passageExecute_57()
	{
		yield return new TwineText(@"#lucy_approval, +5#");
		yield return new TwineText(@"%1, <lucy>, <center>, <frown>%");
		yield return new TwineText(@"LUCILLE: And he chose to stay, hm?");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: Well. I guess there must be more to you than I thought.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: Can we talk about something else now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Sure.", @"Sure.", @"else", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}
    
	// .............
	// #58: Why? I haven't been able to.

	void passageInit_58()
	{
		this.Passages["Why? I haven't been able to."] = new TwinePassage("Why? I haven't been able to.", new string[]{  }, passageExecute_58);
	}

	IEnumerable<TwineOutput> passageExecute_58()
	{
		yield return new TwineText(@"#lucy_approval, -5#");
		yield return new TwineText(@"%1, <lucy>, <center>, <frown>%");
		yield return new TwineText(@"LUCILLE: Oh, lord. Please uninvite me from this pity party already.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: Can we <i>please</i> talk about something other than your bruised ego now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Sure.", @"Sure.", @"else", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}
    
	// .............
	// #59: world

	void passageInit_59()
	{
		this.Passages["world"] = new TwinePassage("world", new string[]{  }, passageExecute_59);
	}

	IEnumerable<TwineOutput> passageExecute_59()
	{
		yield return new TwineText(@"#convo_points, -1#");
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: Are you kidding? Anywhere but here!");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: No offense. I just mean...well, exactly what I said.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: To be clear, though, ""here"" includes my farm, too.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: If I had my way, I'd never go back there. Ever.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Really? You <i>never</i> want to go back?", @"Really? You <i>never</i> want to go back?", @"Really? You <i>never</i> want to go back?", null, null);
		yield return new TwineLink(@"There must be somewhere specific you'd like to go.", @"There must be somewhere specific you'd like to go.", @"There must be somewhere specific you'd like to go.", null, null);
		yield return new TwineLink(@"Such harsh words! I'm almost offended.", @"Such harsh words! I'm almost offended.", @"Such harsh words! I'm almost offended.", null, null);	
	}
    
	// .............
	// #60: Really? You <i>never</i> want to go back?

	void passageInit_60()
	{
		this.Passages["Really? You <i>never</i> want to go back?"] = new TwinePassage("Really? You <i>never</i> want to go back?", new string[]{  }, passageExecute_60);
	}

	IEnumerable<TwineOutput> passageExecute_60()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #61: There must be somewhere specific you'd like to go.

	void passageInit_61()
	{
		this.Passages["There must be somewhere specific you'd like to go."] = new TwinePassage("There must be somewhere specific you'd like to go.", new string[]{  }, passageExecute_61);
	}

	IEnumerable<TwineOutput> passageExecute_61()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #62: Such harsh words! I'm almost offended.

	void passageInit_62()
	{
		this.Passages["Such harsh words! I'm almost offended."] = new TwinePassage("Such harsh words! I'm almost offended.", new string[]{  }, passageExecute_62);
	}

	IEnumerable<TwineOutput> passageExecute_62()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #63: kid

	void passageInit_63()
	{
		this.Passages["kid"] = new TwinePassage("kid", new string[]{  }, passageExecute_63);
	}

	IEnumerable<TwineOutput> passageExecute_63()
	{
		yield return new TwineText(@"#convo_points, -1#");
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: Like what?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Drunk.", @"Drunk.", @"Drunk.", null, null);
		yield return new TwineLink(@"Rude.", @"Rude.", @"Rude.", null, null);
		yield return new TwineLink(@"Sad.", @"Sad.", @"Sad.", null, null);	
	}
    
	// .............
	// #64: You look the same way I feel.

	void passageInit_64()
	{
		this.Passages["You look the same way I feel."] = new TwinePassage("You look the same way I feel.", new string[]{  }, passageExecute_64);
	}

	IEnumerable<TwineOutput> passageExecute_64()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #65: friends

	void passageInit_65()
	{
		this.Passages["friends"] = new TwinePassage("friends", new string[]{  }, passageExecute_65);
	}

	IEnumerable<TwineOutput> passageExecute_65()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #66: Sad.

	void passageInit_66()
	{
		this.Passages["Sad."] = new TwinePassage("Sad.", new string[]{  }, passageExecute_66);
	}

	IEnumerable<TwineOutput> passageExecute_66()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <angry>%");
		yield return new TwineText(@"LUCILLE: I'm not--!");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <lucy>, <center>, <neutral>%");
		yield return new TwineText(@"LUCILLE: ...I mean, I'm not sad. Why would you think that?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"You look the same way I feel.", @"You look the same way I feel.", @"You look the same way I feel.", null, null);
		yield return new TwineLink(@"Excuse me for trying to get personal.", @"Excuse me for trying to get personal.", @"Excuse me for trying to get personal.", null, null);	
	}
    
	// .............
	// #67: Rude.

	void passageInit_67()
	{
		this.Passages["Rude."] = new TwinePassage("Rude.", new string[]{  }, passageExecute_67);
	}

	IEnumerable<TwineOutput> passageExecute_67()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <smile>%");
		yield return new TwineText(@"LUCILLE: Ha! Good one.");
		yield return new TwineText(@"");
		yield return new TwineText(@"LUCILLE: Can you even imagine? A tiny little kid, with all this sass? I'd have exploded!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I'm glad you didn't.", @"I'm glad you didn't.", @"I'm glad you didn't.", null, null);
		yield return new TwineLink(@"That would've been a sight.", @"That would've been a sight.", @"That would've been a sight.", null, null);
		yield return new TwineLink(@"How did you get this way, then?", @"How did you get this way, then?", @"How did you get this way, then?", null, null);	
	}
    
	// .............
	// #68: Drunk.

	void passageInit_68()
	{
		this.Passages["Drunk."] = new TwinePassage("Drunk.", new string[]{  }, passageExecute_68);
	}

	IEnumerable<TwineOutput> passageExecute_68()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #69: Excuse me for trying to get personal.

	void passageInit_69()
	{
		this.Passages["Excuse me for trying to get personal."] = new TwinePassage("Excuse me for trying to get personal.", new string[]{  }, passageExecute_69);
	}

	IEnumerable<TwineOutput> passageExecute_69()
	{
		yield return new TwineText(@"%1, <lucy>, <center>, <angry>%");
		yield return new TwineText(@"LUCILLE: You're not excused. Not at all.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I just want to get to know you.", @"I just want to get to know you.", @"I just want to get to know you.", null, null);
		yield return new TwineLink(@"You want to push me away? Fine. You've done it.", @"You want to push me away? Fine. You've done it.", @"You want to push me away? Fine. You've done it.", null, null);	
	}
    
	// .............
	// #70: That would've been a sight.

	void passageInit_70()
	{
		this.Passages["That would've been a sight."] = new TwinePassage("That would've been a sight.", new string[]{  }, passageExecute_70);
	}

	IEnumerable<TwineOutput> passageExecute_70()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #71: How did you get this way, then?

	void passageInit_71()
	{
		this.Passages["How did you get this way, then?"] = new TwinePassage("How did you get this way, then?", new string[]{  }, passageExecute_71);
	}

	IEnumerable<TwineOutput> passageExecute_71()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #72: I'm glad you didn't.

	void passageInit_72()
	{
		this.Passages["I'm glad you didn't."] = new TwinePassage("I'm glad you didn't.", new string[]{  }, passageExecute_72);
	}

	IEnumerable<TwineOutput> passageExecute_72()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #73: I just want to get to know you.

	void passageInit_73()
	{
		this.Passages["I just want to get to know you."] = new TwinePassage("I just want to get to know you.", new string[]{  }, passageExecute_73);
	}

	IEnumerable<TwineOutput> passageExecute_73()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #74: You want to push me away? Fine. You've done it.

	void passageInit_74()
	{
		this.Passages["You want to push me away? Fine. You've done it."] = new TwinePassage("You want to push me away? Fine. You've done it.", new string[]{  }, passageExecute_74);
	}

	IEnumerable<TwineOutput> passageExecute_74()
	{
		yield return new TwineText(@"");	
	}

}