/*
Generated by UnityTwine on 4/21/2016 11:06:42 PM
https://github.com/daterre/UnityTwine
*/
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UnityTwine;

public class morning: TwineStory
{
	public override TwineVar this[string name]
	{
		get
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
		set
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
	}


	void Awake() {
		base.Init();
		passageInit_0();
		passageInit_1();
		passageInit_2();
		passageInit_3();
		passageInit_4();
		passageInit_5();
		passageInit_6();
		passageInit_7();
		passageInit_8();
		passageInit_9();
		passageInit_10();
		passageInit_11();
		passageInit_12();
		passageInit_13();
		passageInit_14();
		passageInit_15();
		passageInit_16();
		passageInit_17();
		passageInit_18();
		passageInit_19();
		passageInit_20();
		passageInit_21();
		passageInit_22();
		passageInit_23();
		passageInit_24();
	}
    
	// .............
	// #0: j1

	void passageInit_0()
	{
		this.Passages["j1"] = new TwinePassage("j1", new string[]{  }, passageExecute_0);
	}

	IEnumerable<TwineOutput> passageExecute_0()
	{
		yield return new TwineText(@"BEAUREGARD: She doesn't appear very impressed with you yet, sire, but I'm sure that'll change. Might I recommend trying a more humorous approach? <b>The lady Jane loves to laugh.</b>");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: Is there anyone else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Yes.", @"Yes.", @"women", null, null);
		yield return new TwineLink(@"No.", @"No.", @"No.", null, null);	
	}
    
	// .............
	// #1: n1

	void passageInit_1()
	{
		this.Passages["n1"] = new TwinePassage("n1", new string[]{  }, passageExecute_1);
	}

	IEnumerable<TwineOutput> passageExecute_1()
	{
		yield return new TwineText(@"BEAUREGARD: I dont think she likes you very much, sire. But I wouldn't take it to heart; she just seems to be that sort of person. Very guarded, behind that becoming smile. <b>A gentler touch might be help endear you to her.</b>");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: Is there anyone else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Yes.", @"Yes.", @"women", null, null);
		yield return new TwineLink(@"No.", @"No.", @"No.", null, null);	
	}
    
	// .............
	// #2: p1

	void passageInit_2()
	{
		this.Passages["p1"] = new TwinePassage("p1", new string[]{  }, passageExecute_2);
	}

	IEnumerable<TwineOutput> passageExecute_2()
	{
		yield return new TwineText(@"BEAUREGARD: I'm not sure how you've managed it, considering her gentle demeanor, but the lady Patrice doesn't seem particularly interested in you. <b>Please, just try not to scare her.</b> She's really very easy to get along with when she's not terrified.");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: Is there anyone else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Yes.", @"Yes.", @"women", null, null);
		yield return new TwineLink(@"No.", @"No.", @"No.", null, null);	
	}
    
	// .............
	// #3: n_i

	void passageInit_3()
	{
		this.Passages["n_i"] = new TwinePassage("n_i", new string[]{  }, passageExecute_3);
	}

	IEnumerable<TwineOutput> passageExecute_3()
	{
		yield return new TwineText(@"#noelle_item, +1#");
		yield return new TwineText(@"BEAUREGARD: As you wish. Everything should be ready tomorrow morning.");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: Is there anything else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Yes. One of the women in the castle.", @"Yes. One of the women in the castle.", @"women", null, null);
		yield return new TwineLink(@"No.", @"No.", @"no", null, null);	
	}
    
	// .............
	// #4: Start

	void passageInit_4()
	{
		this.Passages["Start"] = new TwinePassage("Start", new string[]{  }, passageExecute_4);
	}

	IEnumerable<TwineOutput> passageExecute_4()
	{
		yield return new TwineText(@"%1, <beau>, <center>, <smile>%");
		yield return new TwineText(@"BEAUREGARD: Good morning, sire!");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: Is there anything you require of me this morning?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I'd like to ask about one of the women in the castle.", @"I'd like to ask about one of the women in the castle.", @"women", null, null);
		yield return new TwineLink(@"There's something I'd like you to get for me.]]
		[[No, thank you Beauregard. You're free to go.", @"There's something I'd like you to get for me.]]
		[[No, thank you Beauregard. You're free to go.", @"no", null, null);	
	}
    
	// .............
	// #5: j2

	void passageInit_5()
	{
		this.Passages["j2"] = new TwinePassage("j2", new string[]{  }, passageExecute_5);
	}

	IEnumerable<TwineOutput> passageExecute_5()
	{
		yield return new TwineText(@"BEAUREGARD: You're getting quite friendly with her, sire! I must say I'm quite proud of you.");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: Is there anyone else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Yes.", @"Yes.", @"women", null, null);
		yield return new TwineLink(@"No.", @"No.", @"No.", null, null);	
	}
    
	// .............
	// #6: n2

	void passageInit_6()
	{
		this.Passages["n2"] = new TwinePassage("n2", new string[]{  }, passageExecute_6);
	}

	IEnumerable<TwineOutput> passageExecute_6()
	{
		yield return new TwineText(@"BEAUREGARD: She seems to really be warming up to you! It appears those good manners are finally paying off.");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: Is there anyone else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Yes.", @"Yes.", @"women", null, null);
		yield return new TwineLink(@"No.", @"No.", @"No.", null, null);	
	}
    
	// .............
	// #7: p2

	void passageInit_7()
	{
		this.Passages["p2"] = new TwinePassage("p2", new string[]{  }, passageExecute_7);
	}

	IEnumerable<TwineOutput> passageExecute_7()
	{
		yield return new TwineText(@"BEAUREGARD: You and the lady Patrice seem to be getting along quite nicely! I like her very much indeed, sire. You've done well.");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: Is there anyone else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Yes.", @"Yes.", @"women", null, null);
		yield return new TwineLink(@"No.", @"No.", @"No.", null, null);	
	}
    
	// .............
	// #8: p_i

	void passageInit_8()
	{
		this.Passages["p_i"] = new TwinePassage("p_i", new string[]{  }, passageExecute_8);
	}

	IEnumerable<TwineOutput> passageExecute_8()
	{
		yield return new TwineText(@"#pat_item, +1#");
		yield return new TwineText(@"BEAUREGARD: As you wish. Everything should be ready tomorrow morning.");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: Is there anything else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Yes. One of the women in the castle.", @"Yes. One of the women in the castle.", @"women", null, null);
		yield return new TwineLink(@"No.", @"No.", @"no", null, null);	
	}
    
	// .............
	// #9: women

	void passageInit_9()
	{
		this.Passages["women"] = new TwinePassage("women", new string[]{  }, passageExecute_9);
	}

	IEnumerable<TwineOutput> passageExecute_9()
	{
		yield return new TwineText(@"%1, <beau>, <center>, <smile>%");
		yield return new TwineText(@"BEAUREGARD: Of course, sire. Who is it you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"%noelle_approval,0,10%Noelle.", @"%noelle_approval,0,10%Noelle.", @"n1", null, null);
		yield return new TwineLink(@"%noelle_approval,10,30%Noelle.", @"%noelle_approval,10,30%Noelle.", @"n2", null, null);
		yield return new TwineLink(@"%noelle_approval,30,70%Noelle.", @"%noelle_approval,30,70%Noelle.", @"n3", null, null);
		yield return new TwineLink(@"%jane_approval,0,10%Jane.", @"%jane_approval,0,10%Jane.", @"j1", null, null);
		yield return new TwineLink(@"%jane_approval,10,30%Jane.", @"%jane_approval,10,30%Jane.", @"j2", null, null);
		yield return new TwineLink(@"%jane_approval,30,70%Jane.", @"%jane_approval,30,70%Jane.", @"j3", null, null);
		yield return new TwineLink(@"%pat_approval,0,10%Pat.", @"%pat_approval,0,10%Pat.", @"p1", null, null);
		yield return new TwineLink(@"%pat_approval,10,30%Pat.", @"%pat_approval,10,30%Pat.", @"p2", null, null);
		yield return new TwineLink(@"%pat_approval,30,70%Pat.", @"%pat_approval,30,70%Pat.", @"p3", null, null);
		yield return new TwineLink(@"%lucy_approval,0,10%Lucille.", @"%lucy_approval,0,10%Lucille.", @"l1", null, null);
		yield return new TwineLink(@"%lucy_approval,10,30%Lucille.", @"%lucy_approval,10,30%Lucille.", @"l2", null, null);
		yield return new TwineLink(@"%lucy_approval,30,70%Lucille.", @"%lucy_approval,30,70%Lucille.", @"l3", null, null);
		yield return new TwineLink(@"%hen_approval,0,10%Henrietta.", @"%hen_approval,0,10%Henrietta.", @"h1", null, null);
		yield return new TwineLink(@"%hen_approval,10,30%Henrietta.", @"%hen_approval,10,30%Henrietta.", @"h2", null, null);
		yield return new TwineLink(@"%hen_approval,30,70%Henrietta.", @"%hen_approval,30,70%Henrietta.", @"h3", null, null);	
	}
    
	// .............
	// #10: no

	void passageInit_10()
	{
		this.Passages["no"] = new TwinePassage("no", new string[]{  }, passageExecute_10);
	}

	IEnumerable<TwineOutput> passageExecute_10()
	{
		yield return new TwineText(@"BEAUREGARD: Very well, sire. I wish you a good day, and good luck!");	
	}
    
	// .............
	// #11: There's something I'd like you to get for me.

	void passageInit_11()
	{
		this.Passages["There's something I'd like you to get for me."] = new TwinePassage("There's something I'd like you to get for me.", new string[]{  }, passageExecute_11);
	}

	IEnumerable<TwineOutput> passageExecute_11()
	{
		yield return new TwineText(@"BEAUREGARD: Of course, sire. What in particular did you have in mind?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"%noelle_gift, 1, 1%Noelle's mother's will. Her father is keeping it hidden somewhere.", @"%noelle_gift, 1, 1%Noelle's mother's will. Her father is keeping it hidden somewhere.", @"n_i", null, null);
		yield return new TwineLink(@"%jane_gift, 1, 1%A picture of Jane's family.", @"%jane_gift, 1, 1%A picture of Jane's family.", @"j_i", null, null);
		yield return new TwineLink(@"%pat_gift, 1, 1%Patrice's son is staying with his grandmother, and no letters seem to be getting through. Could you check on them? Patrice wold love a letter from her son.", @"%pat_gift, 1, 1%Patrice's son is staying with his grandmother, and no letters seem to be getting through. Could you check on them? Patrice wold love a letter from her son.", @"p_i", null, null);
		yield return new TwineLink(@"%lucy_gift, 1, 1%Lucille had a fight with her best friend before leaving home. Could you persuade her to forgive Lucille? Perhaps in letter form?", @"%lucy_gift, 1, 1%Lucille had a fight with her best friend before leaving home. Could you persuade her to forgive Lucille? Perhaps in letter form?", @"l_i", null, null);
		yield return new TwineLink(@"%hen_gift, 1, 1%Henrietta's old home had pastures with a sweeter type of grass. Would you bring some back to the castle for her?", @"%hen_gift, 1, 1%Henrietta's old home had pastures with a sweeter type of grass. Would you bring some back to the castle for her?", @"h_i", null, null);
		yield return new TwineLink(@"Nevermind.", @"Nevermind.", @"No.", null, null);	
	}
    
	// .............
	// #12: j3

	void passageInit_12()
	{
		this.Passages["j3"] = new TwinePassage("j3", new string[]{  }, passageExecute_12);
	}

	IEnumerable<TwineOutput> passageExecute_12()
	{
		yield return new TwineText(@"BEAUREGARD: I don't mean to push, sire, but if you asked lady Jane to marry you, I don't think she'd say no.");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: Is there anyone else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Yes.", @"Yes.", @"women", null, null);
		yield return new TwineLink(@"No.", @"No.", @"No.", null, null);	
	}
    
	// .............
	// #13: n3

	void passageInit_13()
	{
		this.Passages["n3"] = new TwinePassage("n3", new string[]{  }, passageExecute_13);
	}

	IEnumerable<TwineOutput> passageExecute_13()
	{
		yield return new TwineText(@"BEAUREGARD: She really seems to like you, sire. I'd recommend popping the question soon!");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: Is there anyone else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Yes.", @"Yes.", @"women", null, null);
		yield return new TwineLink(@"No.", @"No.", @"No.", null, null);	
	}
    
	// .............
	// #14: p3

	void passageInit_14()
	{
		this.Passages["p3"] = new TwinePassage("p3", new string[]{  }, passageExecute_14);
	}

	IEnumerable<TwineOutput> passageExecute_14()
	{
		yield return new TwineText(@"BEAUREGARD: The lady Patrice seems quite taken with you! Might I recommend a proposal in the near future?");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: Is there anyone else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Yes.", @"Yes.", @"women", null, null);
		yield return new TwineLink(@"No.", @"No.", @"No.", null, null);	
	}
    
	// .............
	// #15: j_i

	void passageInit_15()
	{
		this.Passages["j_i"] = new TwinePassage("j_i", new string[]{  }, passageExecute_15);
	}

	IEnumerable<TwineOutput> passageExecute_15()
	{
		yield return new TwineText(@"#john_item, +1#");
		yield return new TwineText(@"BEAUREGARD: As you wish. Everything should be ready tomorrow morning.");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: Is there anything else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Yes. One of the women in the castle.", @"Yes. One of the women in the castle.", @"women", null, null);
		yield return new TwineLink(@"No.", @"No.", @"no", null, null);	
	}
    
	// .............
	// #16: No.

	void passageInit_16()
	{
		this.Passages["No."] = new TwinePassage("No.", new string[]{  }, passageExecute_16);
	}

	IEnumerable<TwineOutput> passageExecute_16()
	{
		yield return new TwineText(@"%1, <beau>, <center>, <smile>%");
		yield return new TwineText(@"BEAUREGARD: Very well, sire. Is there anything else I can help with?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I'd like to ask about one of the women in the castle.", @"I'd like to ask about one of the women in the castle.", @"women", null, null);
		yield return new TwineLink(@"There's something I'd like you to get for me.]]
		[[No, thank you Beauregard. You're free to go.", @"There's something I'd like you to get for me.]]
		[[No, thank you Beauregard. You're free to go.", @"no", null, null);	
	}
    
	// .............
	// #17: l_i

	void passageInit_17()
	{
		this.Passages["l_i"] = new TwinePassage("l_i", new string[]{  }, passageExecute_17);
	}

	IEnumerable<TwineOutput> passageExecute_17()
	{
		yield return new TwineText(@"#lucy_item, +1#");
		yield return new TwineText(@"BEAUREGARD: As you wish. Everything should be ready tomorrow morning.");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: Is there anything else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Yes. One of the women in the castle.", @"Yes. One of the women in the castle.", @"women", null, null);
		yield return new TwineLink(@"No.", @"No.", @"no", null, null);	
	}
    
	// .............
	// #18: l1

	void passageInit_18()
	{
		this.Passages["l1"] = new TwinePassage("l1", new string[]{  }, passageExecute_18);
	}

	IEnumerable<TwineOutput> passageExecute_18()
	{
		yield return new TwineText(@"BEAUREGARD: The lady Lucille is rather difficult to get along with, isn't she? Very prickly. Well, I'm sure you'll find a way soon enough. Personally, I've found <b>honesty</b> to be a particularly effective conversation tool when talking with her.");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: Is there anyone else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Yes.", @"Yes.", @"women", null, null);
		yield return new TwineLink(@"No.", @"No.", @"No.", null, null);	
	}
    
	// .............
	// #19: h1

	void passageInit_19()
	{
		this.Passages["h1"] = new TwinePassage("h1", new string[]{  }, passageExecute_19);
	}

	IEnumerable<TwineOutput> passageExecute_19()
	{
		yield return new TwineText(@"BEAUREGARD: Er. She's...she's just a cow, sire. But, if you really are curious, I suppose...she seems to like you about as much as any cow likes a stranger?");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: Is there anyone else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Yes.", @"Yes.", @"women", null, null);
		yield return new TwineLink(@"No.", @"No.", @"No.", null, null);	
	}
    
	// .............
	// #20: h_i

	void passageInit_20()
	{
		this.Passages["h_i"] = new TwinePassage("h_i", new string[]{  }, passageExecute_20);
	}

	IEnumerable<TwineOutput> passageExecute_20()
	{
		yield return new TwineText(@"#hen_item, +1#");
		yield return new TwineText(@"BEAUREGARD: As you wish. Everything should be ready tomorrow morning.");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: Is there anything else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Yes. One of the women in the castle.", @"Yes. One of the women in the castle.", @"women", null, null);
		yield return new TwineLink(@"No.", @"No.", @"no", null, null);	
	}
    
	// .............
	// #21: l2

	void passageInit_21()
	{
		this.Passages["l2"] = new TwinePassage("l2", new string[]{  }, passageExecute_21);
	}

	IEnumerable<TwineOutput> passageExecute_21()
	{
		yield return new TwineText(@"BEAUREGARD: It seems you two are starting to get along quite nicely! Very impressive, if I may say so, sire. Keep it up!");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: Is there anyone else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Yes.", @"Yes.", @"women", null, null);
		yield return new TwineLink(@"No.", @"No.", @"No.", null, null);	
	}
    
	// .............
	// #22: h2

	void passageInit_22()
	{
		this.Passages["h2"] = new TwinePassage("h2", new string[]{  }, passageExecute_22);
	}

	IEnumerable<TwineOutput> passageExecute_22()
	{
		yield return new TwineText(@"%1, <beau>, <center>, <neutral>%");
		yield return new TwineText(@"BEAUREGARD: The, erm...<i>lady</i> Henrietta seems to be warming up to you. I'm not sure how, or why, but...keep it up, I suppose?");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: Is there anyone else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Yes.", @"Yes.", @"women", null, null);
		yield return new TwineLink(@"No.", @"No.", @"No.", null, null);	
	}
    
	// .............
	// #23: l3

	void passageInit_23()
	{
		this.Passages["l3"] = new TwinePassage("l3", new string[]{  }, passageExecute_23);
	}

	IEnumerable<TwineOutput> passageExecute_23()
	{
		yield return new TwineText(@"BEAUREGARD: I'm not sure how you've managed it, sire, but the lady Lucille seems quite enamoured of you! Do I see a proposal on the horizon?");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: Is there anyone else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Yes.", @"Yes.", @"women", null, null);
		yield return new TwineLink(@"No.", @"No.", @"No.", null, null);	
	}
    
	// .............
	// #24: h3

	void passageInit_24()
	{
		this.Passages["h3"] = new TwinePassage("h3", new string[]{  }, passageExecute_24);
	}

	IEnumerable<TwineOutput> passageExecute_24()
	{
		yield return new TwineText(@"%1, <beau>, <center>, <frown>%");
		yield return new TwineText(@"BEAUREGARD: I...I'm confused, sire. I don't understand this...<i>thing</i> between you and the, erm, lady Henrietta, but if this is what makes you happy...Well, I suppose the heart wants what the heart wants.");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: Is there anyone else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Yes.", @"Yes.", @"women", null, null);
		yield return new TwineLink(@"No.", @"No.", @"No.", null, null);	
	}

}