/*
Generated by UnityTwine on 04/10/2016 13:23:05
https://github.com/daterre/UnityTwine
*/
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UnityTwine;

public class noelle_main: TwineStory
{
	public override TwineVar this[string name]
	{
		get
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
		set
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
	}


	void Awake() {
		base.Init();
		passageInit_0();
		passageInit_1();
		passageInit_2();
		passageInit_3();
		passageInit_4();
		passageInit_5();
		passageInit_6();
		passageInit_7();
		passageInit_8();
		passageInit_9();
		passageInit_10();
		passageInit_11();
		passageInit_12();
		passageInit_13();
		passageInit_14();
		passageInit_15();
		passageInit_16();
		passageInit_17();
		passageInit_18();
		passageInit_19();
		passageInit_20();
		passageInit_21();
		passageInit_22();
		passageInit_23();
		passageInit_24();
		passageInit_25();
		passageInit_26();
		passageInit_27();
		passageInit_28();
		passageInit_29();
		passageInit_30();
		passageInit_31();
		passageInit_32();
		passageInit_33();
		passageInit_34();
		passageInit_35();
		passageInit_36();
		passageInit_37();
		passageInit_38();
		passageInit_39();
		passageInit_40();
		passageInit_41();
		passageInit_42();
	}
    
	// .............
	// #0: %noelle_approval,50,70%How are you enjoying your stay here?

	void passageInit_0()
	{
		this.Passages["%noelle_approval,50,70%How are you enjoying your stay here?"] = new TwinePassage("%noelle_approval,50,70%How are you enjoying your stay here?", new string[]{  }, passageExecute_0);
	}

	IEnumerable<TwineOutput> passageExecute_0()
	{
		yield return new TwineText(@"NOELLE: You've certainly made me feel at home, sire. Thank you. ");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: I...I never thought I'd be so comfortable here. In a stranger's home. But, then, I suppose we aren't really strangers anymore, are we?");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: Is there anything else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"One of the other women in the castle.", @"One of the other women in the castle.", @"One of the other women in the castle.", null, null);
		yield return new TwineLink(@"Let's talk about you.", @"Let's talk about you.", @"Let's talk about you.", null, null);	
	}
    
	// .............
	// #1: %noelle_approval,10,50%How are you enjoying your stay here?

	void passageInit_1()
	{
		this.Passages["%noelle_approval,10,50%How are you enjoying your stay here?"] = new TwinePassage("%noelle_approval,10,50%How are you enjoying your stay here?", new string[]{  }, passageExecute_1);
	}

	IEnumerable<TwineOutput> passageExecute_1()
	{
		yield return new TwineText(@"NOELLE: I must admit, this place seemed a bit intimidating when I first arrived. But it's starting to feel more...homey.");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: Is there anything else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"One of the other women in the castle.", @"One of the other women in the castle.", @"One of the other women in the castle.", null, null);
		yield return new TwineLink(@"Let's talk about you.", @"Let's talk about you.", @"Let's talk about you.", null, null);	
	}
    
	// .............
	// #2: %noelle_approval,0,10%How are you enjoying your stay here?

	void passageInit_2()
	{
		this.Passages["%noelle_approval,0,10%How are you enjoying your stay here?"] = new TwinePassage("%noelle_approval,0,10%How are you enjoying your stay here?", new string[]{  }, passageExecute_2);
	}

	IEnumerable<TwineOutput> passageExecute_2()
	{
		yield return new TwineText(@"NOELLE: The castle is beautiful. I've never been anywhere so...<i>imposing</i> before.");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: Is there anything else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"One of the other women in the castle.", @"One of the other women in the castle.", @"One of the other women in the castle.", null, null);
		yield return new TwineLink(@"Let's talk about you.", @"Let's talk about you.", @"Let's talk about you.", null, null);	
	}
    
	// .............
	// #3: %noelle_approval,-30,0%How are you enjoying your stay here?

	void passageInit_3()
	{
		this.Passages["%noelle_approval,-30,0%How are you enjoying your stay here?"] = new TwinePassage("%noelle_approval,-30,0%How are you enjoying your stay here?", new string[]{  }, passageExecute_3);
	}

	IEnumerable<TwineOutput> passageExecute_3()
	{
		yield return new TwineText(@"NOELLE: ...I can't think of a <i>single</i> thing to complain about. Staying here has certainly been an...<i>experience</i>, so far. One I don't think I'd care to repeat.");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: Is there anything else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"One of the other women in the castle.", @"One of the other women in the castle.", @"One of the other women in the castle.", null, null);
		yield return new TwineLink(@"Let's talk about you.", @"Let's talk about you.", @"Let's talk about you.", null, null);	
	}
    
	// .............
	// #4: Start

	void passageInit_4()
	{
		this.Passages["Start"] = new TwinePassage("Start", new string[]{  }, passageExecute_4);
	}

	IEnumerable<TwineOutput> passageExecute_4()
	{
		yield return new TwineText(@"%1, <noelle>, <center>, <smile>%");
		yield return new TwineText(@"NOELLE: A pleasure to see you, sire. What would you like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"One of the other women in the castle.", @"One of the other women in the castle.", @"One of the other women in the castle.", null, null);
		yield return new TwineLink(@"%noelle_approval,-30,0%How are you enjoying your stay here?", @"%noelle_approval,-30,0%How are you enjoying your stay here?", @"%noelle_approval,-30,0%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,0,10%How are you enjoying your stay here?", @"%noelle_approval,0,10%How are you enjoying your stay here?", @"%noelle_approval,0,10%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,10,50%How are you enjoying your stay here?", @"%noelle_approval,10,50%How are you enjoying your stay here?", @"%noelle_approval,10,50%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,50,70%How are you enjoying your stay here?", @"%noelle_approval,50,70%How are you enjoying your stay here?", @"%noelle_approval,50,70%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"Let's talk about you.", @"Let's talk about you.", @"Let's talk about you.", null, null);	
	}
    
	// .............
	// #5: h1

	void passageInit_5()
	{
		this.Passages["h1"] = new TwinePassage("h1", new string[]{  }, passageExecute_5);
	}

	IEnumerable<TwineOutput> passageExecute_5()
	{
		yield return new TwineText(@"%1, <noelle>, <center>, <neutral>%");
		yield return new TwineText(@"NOELLE: Well, I, um. She's--she's a cow, sire. There isn't much to say.");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: Is there anything else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"One of the other women in the castle.", @"One of the other women in the castle.", @"One of the other women in the castle.", null, null);
		yield return new TwineLink(@"%noelle_approval,-30,0%How are you enjoying your stay here?", @"%noelle_approval,-30,0%How are you enjoying your stay here?", @"%noelle_approval,-30,0%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,0,10%How are you enjoying your stay here?", @"%noelle_approval,0,10%How are you enjoying your stay here?", @"%noelle_approval,0,10%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,10,50%How are you enjoying your stay here?", @"%noelle_approval,10,50%How are you enjoying your stay here?", @"%noelle_approval,10,50%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,50,70%How are you enjoying your stay here?", @"%noelle_approval,50,70%How are you enjoying your stay here?", @"%noelle_approval,50,70%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"Let's talk about you.", @"Let's talk about you.", @"Let's talk about you.", null, null);	
	}
    
	// .............
	// #6: h2

	void passageInit_6()
	{
		this.Passages["h2"] = new TwinePassage("h2", new string[]{  }, passageExecute_6);
	}

	IEnumerable<TwineOutput> passageExecute_6()
	{
		yield return new TwineText(@"%1, <noelle>, <center>, <neutral>%");
		yield return new TwineText(@"NOELLE: Henrietta may be a cow, but she's a lovely companion. I admit I was wary at first, but I've truly grown to enjoy her company.");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: Is there anything else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"One of the other women in the castle.", @"One of the other women in the castle.", @"One of the other women in the castle.", null, null);
		yield return new TwineLink(@"%noelle_approval,-30,0%How are you enjoying your stay here?", @"%noelle_approval,-30,0%How are you enjoying your stay here?", @"%noelle_approval,-30,0%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,0,10%How are you enjoying your stay here?", @"%noelle_approval,0,10%How are you enjoying your stay here?", @"%noelle_approval,0,10%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,10,50%How are you enjoying your stay here?", @"%noelle_approval,10,50%How are you enjoying your stay here?", @"%noelle_approval,10,50%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,50,70%How are you enjoying your stay here?", @"%noelle_approval,50,70%How are you enjoying your stay here?", @"%noelle_approval,50,70%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"Let's talk about you.", @"Let's talk about you.", @"Let's talk about you.", null, null);	
	}
    
	// .............
	// #7: j1

	void passageInit_7()
	{
		this.Passages["j1"] = new TwinePassage("j1", new string[]{  }, passageExecute_7);
	}

	IEnumerable<TwineOutput> passageExecute_7()
	{
		yield return new TwineText(@"%1, <noelle>, <center>, <neutral>%");
		yield return new TwineText(@"NOELLE: Jane seems a bit odd to me, sire. She doesn't act like any woman I've ever met before.");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: Is there anything else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"One of the other women in the castle.", @"One of the other women in the castle.", @"One of the other women in the castle.", null, null);
		yield return new TwineLink(@"%noelle_approval,-30,0%How are you enjoying your stay here?", @"%noelle_approval,-30,0%How are you enjoying your stay here?", @"%noelle_approval,-30,0%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,0,10%How are you enjoying your stay here?", @"%noelle_approval,0,10%How are you enjoying your stay here?", @"%noelle_approval,0,10%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,10,50%How are you enjoying your stay here?", @"%noelle_approval,10,50%How are you enjoying your stay here?", @"%noelle_approval,10,50%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,50,70%How are you enjoying your stay here?", @"%noelle_approval,50,70%How are you enjoying your stay here?", @"%noelle_approval,50,70%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"Let's talk about you.", @"Let's talk about you.", @"Let's talk about you.", null, null);	
	}
    
	// .............
	// #8: j2

	void passageInit_8()
	{
		this.Passages["j2"] = new TwinePassage("j2", new string[]{  }, passageExecute_8);
	}

	IEnumerable<TwineOutput> passageExecute_8()
	{
		yield return new TwineText(@"%1, <noelle>, <center>, <neutral>%");
		yield return new TwineText(@"NOELLE: Jane seems...sad, sometimes, when she thinks no one is looking. ");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: Is there anything else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"One of the other women in the castle.", @"One of the other women in the castle.", @"One of the other women in the castle.", null, null);
		yield return new TwineLink(@"%noelle_approval,-30,0%How are you enjoying your stay here?", @"%noelle_approval,-30,0%How are you enjoying your stay here?", @"%noelle_approval,-30,0%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,0,10%How are you enjoying your stay here?", @"%noelle_approval,0,10%How are you enjoying your stay here?", @"%noelle_approval,0,10%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,10,50%How are you enjoying your stay here?", @"%noelle_approval,10,50%How are you enjoying your stay here?", @"%noelle_approval,10,50%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,50,70%How are you enjoying your stay here?", @"%noelle_approval,50,70%How are you enjoying your stay here?", @"%noelle_approval,50,70%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"Let's talk about you.", @"Let's talk about you.", @"Let's talk about you.", null, null);	
	}
    
	// .............
	// #9: One of the other women in the castle.

	void passageInit_9()
	{
		this.Passages["One of the other women in the castle."] = new TwinePassage("One of the other women in the castle.", new string[]{  }, passageExecute_9);
	}

	IEnumerable<TwineOutput> passageExecute_9()
	{
		yield return new TwineText(@"%1, <noelle>, <center>, <smile>%");
		yield return new TwineText(@"NOELLE: Who did you have in mind?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"#day, 1, 2#Jane.", @"#day, 1, 2#Jane.", @"j1", null, null);
		yield return new TwineLink(@"#day, 3, 6#Jane.", @"#day, 3, 6#Jane.", @"j2", null, null);
		yield return new TwineLink(@"#day, 1, 2#Pat.", @"#day, 1, 2#Pat.", @"p1", null, null);
		yield return new TwineLink(@"#day, 3, 6#Pat.", @"#day, 3, 6#Pat.", @"p2", null, null);
		yield return new TwineLink(@"#day, 1, 2#Lucille.", @"#day, 1, 2#Lucille.", @"l1", null, null);
		yield return new TwineLink(@"#day, 3, 6#Lucille.", @"#day, 3, 6#Lucille.", @"l2", null, null);
		yield return new TwineLink(@"#day, 1, 2#Henrietta.", @"#day, 1, 2#Henrietta.", @"h1", null, null);
		yield return new TwineLink(@"#day, 3, 6#Henrietta.", @"#day, 3, 6#Henrietta.", @"h2", null, null);	
	}
    
	// .............
	// #10: p1

	void passageInit_10()
	{
		this.Passages["p1"] = new TwinePassage("p1", new string[]{  }, passageExecute_10);
	}

	IEnumerable<TwineOutput> passageExecute_10()
	{
		yield return new TwineText(@"%1, <noelle>, <center>, <smile>%");
		yield return new TwineText(@"NOELLE: I don't know Pat very well yet, but I already feel at ease around her. She's very easy to talk to.");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: Is there anything else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"One of the other women in the castle.", @"One of the other women in the castle.", @"One of the other women in the castle.", null, null);
		yield return new TwineLink(@"%noelle_approval,-30,0%How are you enjoying your stay here?", @"%noelle_approval,-30,0%How are you enjoying your stay here?", @"%noelle_approval,-30,0%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,0,10%How are you enjoying your stay here?", @"%noelle_approval,0,10%How are you enjoying your stay here?", @"%noelle_approval,0,10%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,10,50%How are you enjoying your stay here?", @"%noelle_approval,10,50%How are you enjoying your stay here?", @"%noelle_approval,10,50%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,50,70%How are you enjoying your stay here?", @"%noelle_approval,50,70%How are you enjoying your stay here?", @"%noelle_approval,50,70%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"Let's talk about you.", @"Let's talk about you.", @"Let's talk about you.", null, null);	
	}
    
	// .............
	// #11: p2

	void passageInit_11()
	{
		this.Passages["p2"] = new TwinePassage("p2", new string[]{  }, passageExecute_11);
	}

	IEnumerable<TwineOutput> passageExecute_11()
	{
		yield return new TwineText(@"%1, <noelle>, <center>, <smile>%");
		yield return new TwineText(@"NOELLE: Pat is a wonderful friend. I've rarely felt so safe and comfortable with another person.");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <noelle>, <center>, <frown>%");
		yield return new TwineText(@"NOELLE: Any man who hurts her is less than scum.");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <noelle>, <center>, <smile>%");
		yield return new TwineText(@"NOELLE: Is there anything else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"One of the other women in the castle.", @"One of the other women in the castle.", @"One of the other women in the castle.", null, null);
		yield return new TwineLink(@"%noelle_approval,-30,0%How are you enjoying your stay here?", @"%noelle_approval,-30,0%How are you enjoying your stay here?", @"%noelle_approval,-30,0%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,0,10%How are you enjoying your stay here?", @"%noelle_approval,0,10%How are you enjoying your stay here?", @"%noelle_approval,0,10%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,10,50%How are you enjoying your stay here?", @"%noelle_approval,10,50%How are you enjoying your stay here?", @"%noelle_approval,10,50%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,50,70%How are you enjoying your stay here?", @"%noelle_approval,50,70%How are you enjoying your stay here?", @"%noelle_approval,50,70%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"Let's talk about you.", @"Let's talk about you.", @"Let's talk about you.", null, null);	
	}
    
	// .............
	// #12: l1

	void passageInit_12()
	{
		this.Passages["l1"] = new TwinePassage("l1", new string[]{  }, passageExecute_12);
	}

	IEnumerable<TwineOutput> passageExecute_12()
	{
		yield return new TwineText(@"%1, <noelle>, <center>, <frown>%");
		yield return new TwineText(@"NOELLE: I must admit, I don't really know what to make of Lucille. We're...very different. It makes her hard to understand.");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <noelle>, <center>, <smile>%");
		yield return new TwineText(@"NOELLE: Is there anything else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"One of the other women in the castle.", @"One of the other women in the castle.", @"One of the other women in the castle.", null, null);
		yield return new TwineLink(@"%noelle_approval,-30,0%How are you enjoying your stay here?", @"%noelle_approval,-30,0%How are you enjoying your stay here?", @"%noelle_approval,-30,0%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,0,10%How are you enjoying your stay here?", @"%noelle_approval,0,10%How are you enjoying your stay here?", @"%noelle_approval,0,10%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,10,50%How are you enjoying your stay here?", @"%noelle_approval,10,50%How are you enjoying your stay here?", @"%noelle_approval,10,50%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,50,70%How are you enjoying your stay here?", @"%noelle_approval,50,70%How are you enjoying your stay here?", @"%noelle_approval,50,70%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"Let's talk about you.", @"Let's talk about you.", @"Let's talk about you.", null, null);	
	}
    
	// .............
	// #13: l2

	void passageInit_13()
	{
		this.Passages["l2"] = new TwinePassage("l2", new string[]{  }, passageExecute_13);
	}

	IEnumerable<TwineOutput> passageExecute_13()
	{
		yield return new TwineText(@"%1, <noelle>, <center>, <neutral>%");
		yield return new TwineText(@"NOELLE: Lucille is still bewildering. I don't know if we'll ever find common ground. She's just so...so...");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: ...Anyway.");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <noelle>, <center>, <smile>%");
		yield return new TwineText(@"NOELLE: Is there anything else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"One of the other women in the castle.", @"One of the other women in the castle.", @"One of the other women in the castle.", null, null);
		yield return new TwineLink(@"%noelle_approval,-30,0%How are you enjoying your stay here?", @"%noelle_approval,-30,0%How are you enjoying your stay here?", @"%noelle_approval,-30,0%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,0,10%How are you enjoying your stay here?", @"%noelle_approval,0,10%How are you enjoying your stay here?", @"%noelle_approval,0,10%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,10,50%How are you enjoying your stay here?", @"%noelle_approval,10,50%How are you enjoying your stay here?", @"%noelle_approval,10,50%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,50,70%How are you enjoying your stay here?", @"%noelle_approval,50,70%How are you enjoying your stay here?", @"%noelle_approval,50,70%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"Let's talk about you.", @"Let's talk about you.", @"Let's talk about you.", null, null);	
	}
    
	// .............
	// #14: I suppose it must be easier that way.

	void passageInit_14()
	{
		this.Passages["I suppose it must be easier that way."] = new TwinePassage("I suppose it must be easier that way.", new string[]{  }, passageExecute_14);
	}

	IEnumerable<TwineOutput> passageExecute_14()
	{
		yield return new TwineText(@"#noelle_approval, -5#");
		yield return new TwineText(@"%1, <noelle>, <center>, <frown>%");
		yield return new TwineText(@"NOELLE: Yes. <i>Easier.</i> Of course.");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <noelle>, <center>, <smile>%");
		yield return new TwineText(@"NOELLE: Excuse me, sire, but I'd prefer we didn't discuss this any further. Could we move on to another topic?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Of course. Where are you from?", @"Of course. Where are you from?", @"Where are you from?", null, null);
		yield return new TwineLink(@"I'd like to know more about this, actually.", @"I'd like to know more about this, actually.", @"I'd like to know more about this, actually.", null, null);	
	}
    
	// .............
	// #15: That doesn't mean it isn't awful.

	void passageInit_15()
	{
		this.Passages["That doesn't mean it isn't awful."] = new TwinePassage("That doesn't mean it isn't awful.", new string[]{  }, passageExecute_15);
	}

	IEnumerable<TwineOutput> passageExecute_15()
	{
		yield return new TwineText(@"#noelle_approval, +5#");
		yield return new TwineText(@"%1, <noelle>, <center>, <scared>%");
		yield return new TwineText(@"NOELLE: I...yes. Yes, you're right. ");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <noelle>, <center>, <smile>%");
		yield return new TwineText(@"NOELLE: Still, at least I have my father. He's always done his best to raise me. Or so he tells me.");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: Now if you'll excuse me, sire, I'd prefer we didn't discuss this any further. Could we move on to another topic?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Of course. Where are you from?", @"Of course. Where are you from?", @"Where are you from?", null, null);
		yield return new TwineLink(@"I'd like to know more about this, actually.", @"I'd like to know more about this, actually.", @"I'd like to know more about this, actually.", null, null);	
	}
    
	// .............
	// #16: At least you have your father.

	void passageInit_16()
	{
		this.Passages["At least you have your father."] = new TwinePassage("At least you have your father.", new string[]{  }, passageExecute_16);
	}

	IEnumerable<TwineOutput> passageExecute_16()
	{
		yield return new TwineText(@"%1, <noelle>, <center>, <frown>%");
		yield return new TwineText(@"NOELLE: ...Yes. Yes, I suppose I've been...lucky, in that regard. Things could be...much worse.");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <noelle>, <center>, <smile>%");
		yield return new TwineText(@"NOELLE: He's always done his best to raise me. Or so he tells me.");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <noelle>, <center>, <smile>%");
		yield return new TwineText(@"NOELLE: Excuse me, sire, but I'd prefer we didn't discuss this any further. Could we move on to another topic?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Of course. Where are you from?", @"Of course. Where are you from?", @"Where are you from?", null, null);
		yield return new TwineLink(@"I'd like to know more about this, actually.", @"I'd like to know more about this, actually.", @"I'd like to know more about this, actually.", null, null);	
	}
    
	// .............
	// #17: What's your family like?

	void passageInit_17()
	{
		this.Passages["What's your family like?"] = new TwinePassage("What's your family like?", new string[]{  }, passageExecute_17);
	}

	IEnumerable<TwineOutput> passageExecute_17()
	{
		yield return new TwineText(@"#points, -1#");
		yield return new TwineText(@"%1, <noelle>, <center>, <neutral>%");
		yield return new TwineText(@"NOELLE: There isn't much to tell. My mother died when I was very young, and my father's raised me ever since.");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAST: I'm sorry.");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: Yes, well. Like I said, I was very young. I barely remember her.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"That doesn't mean it isn't awful.", @"That doesn't mean it isn't awful.", @"That doesn't mean it isn't awful.", null, null);
		yield return new TwineLink(@"I suppose it must be easier that way.", @"I suppose it must be easier that way.", @"I suppose it must be easier that way.", null, null);
		yield return new TwineLink(@"At least you have your father.", @"At least you have your father.", @"At least you have your father.", null, null);	
	}
    
	// .............
	// #18: Let's talk about you.

	void passageInit_18()
	{
		this.Passages["Let's talk about you."] = new TwinePassage("Let's talk about you.", new string[]{  }, passageExecute_18);
	}

	IEnumerable<TwineOutput> passageExecute_18()
	{
		yield return new TwineText(@"NOELLE: Certainly. What would you like to know?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Where are you from?", @"Where are you from?", @"Where are you from?", null, null);
		yield return new TwineLink(@"What's your family like?", @"What's your family like?", @"What's your family like?", null, null);	
	}
    
	// .............
	// #19: I'd like to know more about this, actually.

	void passageInit_19()
	{
		this.Passages["I'd like to know more about this, actually."] = new TwinePassage("I'd like to know more about this, actually.", new string[]{  }, passageExecute_19);
	}

	IEnumerable<TwineOutput> passageExecute_19()
	{
		yield return new TwineText(@"#noelle_approval, -5#");
		yield return new TwineText(@"NOELLE: ...Of course, your <i>highness</i>. I am at your disposal as always. We can discuss whatever you wish.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Are you really happy with the way your father's raised you?", @"Are you really happy with the way your father's raised you?", @"Are you really happy with the way your father's raised you?", null, null);
		yield return new TwineLink(@"How did your mother die?", @"How did your mother die?", @"How did your mother die?", null, null);
		yield return new TwineLink(@"I know what it's like to lose your parents.", @"I know what it's like to lose your parents.", @"I know what it's like to lose your parents.", null, null);	
	}
    
	// .............
	// #20: Where are you from?

	void passageInit_20()
	{
		this.Passages["Where are you from?"] = new TwinePassage("Where are you from?", new string[]{  }, passageExecute_20);
	}

	IEnumerable<TwineOutput> passageExecute_20()
	{
		yield return new TwineText(@"#points, -1#");
		yield return new TwineText(@"NOELLE: I'm from Redding, a large town to the north. My father is a merchant, and often travels to the harbor several towns over.");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: It's a beautiful town, Redding. Perfectly charming. Easy to get lost in.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Why would you want to get lost?", @"Why would you want to get lost?", @"Why would you want to get lost?", null, null);
		yield return new TwineLink(@"Have you always lived there?", @"Have you always lived there?", @"Have you always lived there?", null, null);
		yield return new TwineLink(@"Have you ever wanted to live anywhere else?", @"Have you ever wanted to live anywhere else?", @"Have you ever wanted to live anywhere else?", null, null);	
	}
    
	// .............
	// #21: Are you really happy with the way your father's raised you?

	void passageInit_21()
	{
		this.Passages["Are you really happy with the way your father's raised you?"] = new TwinePassage("Are you really happy with the way your father's raised you?", new string[]{  }, passageExecute_21);
	}

	IEnumerable<TwineOutput> passageExecute_21()
	{
		yield return new TwineText(@"#noelle_approval, -5#");
		yield return new TwineText(@"%1, <noelle>, <center>, <frown>%");
		yield return new TwineText(@"NOELLE: I don't really think it's appropriate to ask me such a leading question when we've only just met.");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: I won't be talking about this any more.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Very well. Where are you from?", @"Very well. Where are you from?", @"Where are you from?", null, null);
		yield return new TwineLink(@"I'll be leaving, then.", @"I'll be leaving, then.", @"I'll be leaving, then.", null, null);	
	}
    
	// .............
	// #22: How did your mother die?

	void passageInit_22()
	{
		this.Passages["How did your mother die?"] = new TwinePassage("How did your mother die?", new string[]{  }, passageExecute_22);
	}

	IEnumerable<TwineOutput> passageExecute_22()
	{
		yield return new TwineText(@"#noelle_approval, -10#");
		yield return new TwineText(@"%1, <noelle>, <center>, <angry>%");
		yield return new TwineText(@"NOELLE: How <i>dare</i> you. ");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: We've barely met, and you find it appropriate to ask me such a question?!");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: Either ask me something else, or leave.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Where are you from?", @"Where are you from?", @"Where are you from?", null, null);
		yield return new TwineLink(@"I'll be leaving, then.", @"I'll be leaving, then.", @"I'll be leaving, then.", null, null);	
	}
    
	// .............
	// #23: I know what it's like to lose your parents.

	void passageInit_23()
	{
		this.Passages["I know what it's like to lose your parents."] = new TwinePassage("I know what it's like to lose your parents.", new string[]{  }, passageExecute_23);
	}

	IEnumerable<TwineOutput> passageExecute_23()
	{
		yield return new TwineText(@"#noelle_approval, +10#");
		yield return new TwineText(@"%1, <noelle>, <center>, <scared>%");
		yield return new TwineText(@"NOELLE: O-oh. Forgive me, sire, I had no idea.");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <noelle>, <center>, <neutral>%");
		yield return new TwineText(@"NOELLE: Please, could we discuss something else now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Where are you from?", @"Where are you from?", @"Where are you from?", null, null);
		yield return new TwineLink(@"Actually, I have to go.", @"Actually, I have to go.", @"Actually, I have to go.", null, null);	
	}
    
	// .............
	// #24: Have you ever wanted to live anywhere else?

	void passageInit_24()
	{
		this.Passages["Have you ever wanted to live anywhere else?"] = new TwinePassage("Have you ever wanted to live anywhere else?", new string[]{  }, passageExecute_24);
	}

	IEnumerable<TwineOutput> passageExecute_24()
	{
		yield return new TwineText(@"%1, <noelle>, <center>, <neutral>%");
		yield return new TwineText(@"NOELLE: ...");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: Yes. Sometimes.");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: Sometimes, I imagine myself somewhere completely different, surrounded by people who know nothing about me.");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <noelle>, <center>, <smile>%");
		yield return new TwineText(@"NOELLE: ...But I suppose everyone must have dreams like that. Besides, my life is good enough as it is. I want for very little.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"'Very little' is still something. What is it you want?", @"'Very little' is still something. What is it you want?", @"'Very little' is still something. What is it you want?", null, null);
		yield return new TwineLink(@"I have the same dream. Every day.", @"I have the same dream. Every day.", @"I have the same dream. Every day.", null, null);
		yield return new TwineLink(@"It must be nice, to live so comfortably.", @"It must be nice, to live so comfortably.", @"It must be nice, to live so comfortably.", null, null);	
	}
    
	// .............
	// #25: Have you always lived there?

	void passageInit_25()
	{
		this.Passages["Have you always lived there?"] = new TwinePassage("Have you always lived there?", new string[]{  }, passageExecute_25);
	}

	IEnumerable<TwineOutput> passageExecute_25()
	{
		yield return new TwineText(@"%1, <noelle>, <center>, <neutral>%");
		yield return new TwineText(@"NOELLE: When I was a child, we lived in Nimes, further east. It's a marger larger town--a city, really. I was very young, so I have very few memories of our time there.");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: Will there be anything else, sire?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Let's talk about something else.", @"Let's talk about something else.", @"Very well. Let's talk about something else.", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}
    
	// .............
	// #26: Why would you want to get lost?

	void passageInit_26()
	{
		this.Passages["Why would you want to get lost?"] = new TwinePassage("Why would you want to get lost?", new string[]{  }, passageExecute_26);
	}

	IEnumerable<TwineOutput> passageExecute_26()
	{
		yield return new TwineText(@"%1, <noelle>, <center>, <frown>%");
		yield return new TwineText(@"NOELLE: I didn't mean it like that, sire. It was just a--a figure of speech. ");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <noelle>, <center>, <neutral>%");
		yield return new TwineText(@"NOELLE: I just meant that it's nice to blend into crowds, and not be noticed by anyone. To just be one more face in a crowd.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"That does sound nice.", @"That does sound nice.", @"That does sound nice.", null, null);
		yield return new TwineLink(@"Why would you want to be one of many when you could stand out?", @"Why would you want to be one of many when you could stand out?", @"Why would you want to be one of many when you could stand out?", null, null);
		yield return new TwineLink(@"I wouldn't know what that's like.", @"I wouldn't know what that's like.", @"I wouldn't know what that's like.", null, null);	
	}
    
	// .............
	// #27: I'll be leaving, then.

	void passageInit_27()
	{
		this.Passages["I'll be leaving, then."] = new TwinePassage("I'll be leaving, then.", new string[]{  }, passageExecute_27);
	}

	IEnumerable<TwineOutput> passageExecute_27()
	{
		yield return new TwineText(@"NOELLE: Yes, I think that's for the best. We can both...clear our heads before speaking again.");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: Goodbye for now.");	
	}
    
	// .............
	// #28: Actually, I have to go.

	void passageInit_28()
	{
		this.Passages["Actually, I have to go."] = new TwinePassage("Actually, I have to go.", new string[]{  }, passageExecute_28);
	}

	IEnumerable<TwineOutput> passageExecute_28()
	{
		yield return new TwineText(@"NOELLE: Very well. Goodbye for now.");	
	}
    
	// .............
	// #29: I have the same dream. Every day.

	void passageInit_29()
	{
		this.Passages["I have the same dream. Every day."] = new TwinePassage("I have the same dream. Every day.", new string[]{  }, passageExecute_29);
	}

	IEnumerable<TwineOutput> passageExecute_29()
	{
		yield return new TwineText(@"#noelle_approval, +5#");
		yield return new TwineText(@"%1, <noelle>, <center>, <scared>%");
		yield return new TwineText(@"NOELLE: I...suppose you must.");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: Please, can we talk about something else? This topic is a bit too maudlin for my taste.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Very well. Let's talk about something else.", @"Very well. Let's talk about something else.", @"Very well. Let's talk about something else.", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}
    
	// .............
	// #30: It must be nice, to live so comfortably.

	void passageInit_30()
	{
		this.Passages["It must be nice, to live so comfortably."] = new TwinePassage("It must be nice, to live so comfortably.", new string[]{  }, passageExecute_30);
	}

	IEnumerable<TwineOutput> passageExecute_30()
	{
		yield return new TwineText(@"#noelle_approval, -5#");
		yield return new TwineText(@"%1, <noelle>, <center>, <smile>%");
		yield return new TwineText(@"NOELLE: Yes. Of course. Not that your highness would know anything about that, living in an enormous castle as a prince.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"You have a point.", @"You have a point.", @"You have a point.", null, null);
		yield return new TwineLink(@"I don't think it's the same at all. You aren't a monster.", @"I don't think it's the same at all. You aren't a monster.", @"I don't think it's the same at all. You aren't a monster.", null, null);	
	}
    
	// .............
	// #31: 'Very little' is still something. What is it you want?

	void passageInit_31()
	{
		this.Passages["'Very little' is still something. What is it you want?"] = new TwinePassage("'Very little' is still something. What is it you want?", new string[]{  }, passageExecute_31);
	}

	IEnumerable<TwineOutput> passageExecute_31()
	{
		yield return new TwineText(@"%1, <noelle>, <center>, <frown>%");
		yield return new TwineText(@"NOELLE: ...I don't know. To be someone else, I suppose.");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <noelle>, <center>, <smile>%");
		yield return new TwineText(@"NOELLE: But this is just the silly wish of a sheltered little girl. Don't mind me, sire.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"No, please, tell me more.", @"No, please, tell me more.", @"No, please, tell me more.", null, null);
		yield return new TwineLink(@"I know that feeling very well myself.", @"I know that feeling very well myself.", @"I know that feeling very well myself.", null, null);
		yield return new TwineLink(@"Very well. Let's talk about something else.", @"Very well. Let's talk about something else.", @"Very well. Let's talk about something else.", null, null);	
	}
    
	// .............
	// #32: That does sound nice.

	void passageInit_32()
	{
		this.Passages["That does sound nice."] = new TwinePassage("That does sound nice.", new string[]{  }, passageExecute_32);
	}

	IEnumerable<TwineOutput> passageExecute_32()
	{
		yield return new TwineText(@"#noelle_approval, +5#");
		yield return new TwineText(@"%1, <noelle>, <center>, <smile>%");
		yield return new TwineText(@"NOELLE: I'm glad you see it that way.");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: Is there anything else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Yes, there is.", @"Yes, there is.", @"Very well. Let's talk about something else.", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}
    
	// .............
	// #33: Why would you want to be one of many when you could stand out?

	void passageInit_33()
	{
		this.Passages["Why would you want to be one of many when you could stand out?"] = new TwinePassage("Why would you want to be one of many when you could stand out?", new string[]{  }, passageExecute_33);
	}

	IEnumerable<TwineOutput> passageExecute_33()
	{
		yield return new TwineText(@"#noelle_approval, -5#");
		yield return new TwineText(@"%1, <noelle>, <center>, <smile>%");
		yield return new TwineText(@"NOELLE: An <i>excellent</i> question, sire. So astute. I see now that you have the wit of a philosopher.");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: Will there be anything else, then?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Yes. I'd like to talk about something else.", @"Yes. I'd like to talk about something else.", @"Very well. Let's talk about something else.", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}
    
	// .............
	// #34: I wouldn't know what that's like.

	void passageInit_34()
	{
		this.Passages["I wouldn't know what that's like."] = new TwinePassage("I wouldn't know what that's like.", new string[]{  }, passageExecute_34);
	}

	IEnumerable<TwineOutput> passageExecute_34()
	{
		yield return new TwineText(@"%1, <noelle>, <center>, <scared>%");
		yield return new TwineText(@"NOELLE: ...Oh.");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: Excuse me, sire. I didn't realize.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"It's alright.", @"It's alright.", @"It's alright.", null, null);
		yield return new TwineLink(@"It must be nice to forget how hideous I am.", @"It must be nice to forget how hideous I am.", @"It must be nice to forget how hideous I am.", null, null);	
	}
    
	// .............
	// #35: It's alright.

	void passageInit_35()
	{
		this.Passages["It's alright."] = new TwinePassage("It's alright.", new string[]{  }, passageExecute_35);
	}

	IEnumerable<TwineOutput> passageExecute_35()
	{
		yield return new TwineText(@"#noelle_approval, +5#");
		yield return new TwineText(@"%1, <noelle>, <center>, <smile>%");
		yield return new TwineText(@"NOELLE: Well. I'm glad I haven't offended you overly much.");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: Is there anything else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Yes, there is.", @"Yes, there is.", @"Very well. Let's talk about something else.", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}
    
	// .............
	// #36: It must be nice to forget how hideous I am.

	void passageInit_36()
	{
		this.Passages["It must be nice to forget how hideous I am."] = new TwinePassage("It must be nice to forget how hideous I am.", new string[]{  }, passageExecute_36);
	}

	IEnumerable<TwineOutput> passageExecute_36()
	{
		yield return new TwineText(@"#noelle_approval, -5#");
		yield return new TwineText(@"%1, <noelle>, <center>, <smile>%");
		yield return new TwineText(@"NOELLE: Yes. It is.");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: Thank you, sire, for so conveniently concealing yourself from the women you might marry.");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: Will there be anything else, then?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Yes. I'd like to talk about something else.", @"Yes. I'd like to talk about something else.", @"Very well. Let's talk about something else.", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}
    
	// .............
	// #37: Actually, I have to leave.

	void passageInit_37()
	{
		this.Passages["Actually, I have to leave."] = new TwinePassage("Actually, I have to leave.", new string[]{  }, passageExecute_37);
	}

	IEnumerable<TwineOutput> passageExecute_37()
	{
		yield return new TwineText(@"%1, <noelle>, <center>, <smile>%");
		yield return new TwineText(@"NOELLE: Of course. I hope you have a pleasant day, sire.");	
	}
    
	// .............
	// #38: You have a point.

	void passageInit_38()
	{
		this.Passages["You have a point."] = new TwinePassage("You have a point.", new string[]{  }, passageExecute_38);
	}

	IEnumerable<TwineOutput> passageExecute_38()
	{
		yield return new TwineText(@"#noelle_approval, +5#");
		yield return new TwineText(@"%1, <noelle>, <center>, <frown>%");
		yield return new TwineText(@"NOELLE: Hm. Well. I suppose I do.");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: Men don't often concede to me. I have to admit, it's refreshing to hear.");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <noelle>, <center>, <frown>%");
		yield return new TwineText(@"NOELLE: Could we talk about something else, now? I must admit I think we've exhausted this topic.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Very well. Let's talk about something else.", @"Very well. Let's talk about something else.", @"Very well. Let's talk about something else.", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}
    
	// .............
	// #39: I don't think it's the same at all. You aren't a monster.

	void passageInit_39()
	{
		this.Passages["I don't think it's the same at all. You aren't a monster."] = new TwinePassage("I don't think it's the same at all. You aren't a monster.", new string[]{  }, passageExecute_39);
	}

	IEnumerable<TwineOutput> passageExecute_39()
	{
		yield return new TwineText(@"#noelle_approval, -5#");
		yield return new TwineText(@"%1, <noelle>, <center>, <frown>%");
		yield return new TwineText(@"NOELLE: No. No, I suppose I'm not. ");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: Could we talk about something else now, sire? This subject is a bit too maudlin for my tastes.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Very well. Let's talk about something else.", @"Very well. Let's talk about something else.", @"Very well. Let's talk about something else.", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}
    
	// .............
	// #40: No, please, tell me more.

	void passageInit_40()
	{
		this.Passages["No, please, tell me more."] = new TwinePassage("No, please, tell me more.", new string[]{  }, passageExecute_40);
	}

	IEnumerable<TwineOutput> passageExecute_40()
	{
		yield return new TwineText(@"#noelle_approval, +5#");
		yield return new TwineText(@"%1, <noelle>, <center>, <neutral>%");
		yield return new TwineText(@"NOELLE: There isn't much to say, sire. Although it is...<i>nice</i> to be asked.");
		yield return new TwineText(@"");
		yield return new TwineText(@"NOELLE: Could we talk about something else, now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Very well. Let's talk about something else.", @"Very well. Let's talk about something else.", @"Very well. Let's talk about something else.", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}
    
	// .............
	// #41: Very well. Let's talk about something else.

	void passageInit_41()
	{
		this.Passages["Very well. Let's talk about something else."] = new TwinePassage("Very well. Let's talk about something else.", new string[]{  }, passageExecute_41);
	}

	IEnumerable<TwineOutput> passageExecute_41()
	{
		yield return new TwineText(@"%1, <noelle>, <center>, <smile>%");
		yield return new TwineText(@"NOELLE: Of course, sire. What would you like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"One of the other women in the castle.", @"One of the other women in the castle.", @"One of the other women in the castle.", null, null);
		yield return new TwineLink(@"%noelle_approval,-30,0%How are you enjoying your stay here?", @"%noelle_approval,-30,0%How are you enjoying your stay here?", @"%noelle_approval,-30,0%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,0,10%How are you enjoying your stay here?", @"%noelle_approval,0,10%How are you enjoying your stay here?", @"%noelle_approval,0,10%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,10,50%How are you enjoying your stay here?", @"%noelle_approval,10,50%How are you enjoying your stay here?", @"%noelle_approval,10,50%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"%noelle_approval,50,70%How are you enjoying your stay here?", @"%noelle_approval,50,70%How are you enjoying your stay here?", @"%noelle_approval,50,70%How are you enjoying your stay here?", null, null);
		yield return new TwineLink(@"Let's talk about you.", @"Let's talk about you.", @"Let's talk about you.", null, null);	
	}
    
	// .............
	// #42: I know that feeling very well myself.

	void passageInit_42()
	{
		this.Passages["I know that feeling very well myself."] = new TwinePassage("I know that feeling very well myself.", new string[]{  }, passageExecute_42);
	}

	IEnumerable<TwineOutput> passageExecute_42()
	{
		yield return new TwineText(@"#noelle_approval, +5#");
		yield return new TwineText(@"%1, <noelle>, <center>, <neutral>%");
		yield return new TwineText(@"NOELLE: Oh. I suppose you would.");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <noelle>, <center>, <smile>%");
		yield return new TwineText(@"NOELLE: Could we move on to another subject? I'm starting to feel a bit maudlin.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Very well. Let's talk about something else.", @"Very well. Let's talk about something else.", @"Very well. Let's talk about something else.", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"Actually, I have to leave.", null, null);	
	}

}