/*
Generated by UnityTwine on 4/25/2016 5:19:57 PM
https://github.com/daterre/UnityTwine
*/
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UnityTwine;

public class patrice_main: TwineStory
{
	public override TwineVar this[string name]
	{
		get
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
		set
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
	}


	void Awake() {
		base.Init();
		passageInit_0();
		passageInit_1();
		passageInit_2();
		passageInit_3();
		passageInit_4();
		passageInit_5();
		passageInit_6();
		passageInit_7();
		passageInit_8();
		passageInit_9();
		passageInit_10();
		passageInit_11();
		passageInit_12();
		passageInit_13();
		passageInit_14();
		passageInit_15();
		passageInit_16();
		passageInit_17();
		passageInit_18();
		passageInit_19();
		passageInit_20();
		passageInit_21();
		passageInit_22();
		passageInit_23();
		passageInit_24();
		passageInit_25();
		passageInit_26();
		passageInit_27();
		passageInit_28();
		passageInit_29();
		passageInit_30();
		passageInit_31();
		passageInit_32();
		passageInit_33();
		passageInit_34();
		passageInit_35();
		passageInit_36();
		passageInit_37();
		passageInit_38();
		passageInit_39();
		passageInit_40();
		passageInit_41();
		passageInit_42();
		passageInit_43();
		passageInit_44();
		passageInit_45();
		passageInit_46();
		passageInit_47();
		passageInit_48();
		passageInit_49();
		passageInit_50();
		passageInit_51();
		passageInit_52();
		passageInit_53();
		passageInit_54();
		passageInit_55();
	}
    
	// .............
	// #0: stay4

	void passageInit_0()
	{
		this.Passages["stay4"] = new TwinePassage("stay4", new string[]{  }, passageExecute_0);
	}

	IEnumerable<TwineOutput> passageExecute_0()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <smile>%");
		yield return new TwineText(@"PATRICE: Not sure how you managed it, but I'm...comfortable. Here, I mean.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: Feels wrong to image leaving, now. I suppose that's what you wanted, huh, you sly bastard?");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: What now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I want to hear your opinion of the other women staying in the castle.", @"I want to hear your opinion of the other women staying in the castle.", @"women", null, null);
		yield return new TwineLink(@"Let's talk about you.", @"Let's talk about you.", @"you", null, null);	
	}
    
	// .............
	// #1: stay3

	void passageInit_1()
	{
		this.Passages["stay3"] = new TwinePassage("stay3", new string[]{  }, passageExecute_1);
	}

	IEnumerable<TwineOutput> passageExecute_1()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <neutral>%");
		yield return new TwineText(@"PATRICE: It's honestly starting to feel a little cozy around here. Not something I'm used to, but I could see myself getting used to it. Maybe.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: What now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I want to hear your opinion of the other women staying in the castle.", @"I want to hear your opinion of the other women staying in the castle.", @"women", null, null);
		yield return new TwineLink(@"Let's talk about you.", @"Let's talk about you.", @"you", null, null);	
	}
    
	// .............
	// #2: stay2

	void passageInit_2()
	{
		this.Passages["stay2"] = new TwinePassage("stay2", new string[]{  }, passageExecute_2);
	}

	IEnumerable<TwineOutput> passageExecute_2()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <neutral>%");
		yield return new TwineText(@"PATRICE: I don't hate it as much as I thought I would. And that's as close to a compliment as you'll be getting from me.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: What now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I want to hear your opinion of the other women staying in the castle.", @"I want to hear your opinion of the other women staying in the castle.", @"women", null, null);
		yield return new TwineLink(@"Let's talk about you.", @"Let's talk about you.", @"you", null, null);	
	}
    
	// .............
	// #3: stay1

	void passageInit_3()
	{
		this.Passages["stay1"] = new TwinePassage("stay1", new string[]{  }, passageExecute_3);
	}

	IEnumerable<TwineOutput> passageExecute_3()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <frown>%");
		yield return new TwineText(@"PATRICE: I don't...suppose castles are usually <i>inviting</i>. So I shouldn't be too surprised that this one is so...huge.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: Anything else you'd like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I want to hear your opinion of the other women staying in the castle.", @"I want to hear your opinion of the other women staying in the castle.", @"women", null, null);
		yield return new TwineLink(@"Let's talk about you.", @"Let's talk about you.", @"you", null, null);	
	}
    
	// .............
	// #4: Start

	void passageInit_4()
	{
		this.Passages["Start"] = new TwinePassage("Start", new string[]{  }, passageExecute_4);
	}

	IEnumerable<TwineOutput> passageExecute_4()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <smile>%");
		yield return new TwineText(@"PATRICE: Hello again, sire! Was there something you wanted to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I want to hear your opinion of the other women staying in the castle.", @"I want to hear your opinion of the other women staying in the castle.", @"women", null, null);
		yield return new TwineLink(@"%pat_approval,-30,0%How are you enjoying your stay here?", @"%pat_approval,-30,0%How are you enjoying your stay here?", @"stay1", null, null);
		yield return new TwineLink(@"%pat_approval,1,30%How are you enjoying your stay here?", @"%pat_approval,1,30%How are you enjoying your stay here?", @"stay2", null, null);
		yield return new TwineLink(@"%pat_approval,31,50%How are you enjoying your stay here?", @"%pat_approval,31,50%How are you enjoying your stay here?", @"stay3", null, null);
		yield return new TwineLink(@"%pat_approval,51,70%How are you enjoying your stay here?", @"%pat_approval,51,70%How are you enjoying your stay here?", @"stay4", null, null);
		yield return new TwineLink(@"Let's talk about you.", @"Let's talk about you.", @"you", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"leave", null, null);	
	}
    
	// .............
	// #5: h1

	void passageInit_5()
	{
		this.Passages["h1"] = new TwinePassage("h1", new string[]{  }, passageExecute_5);
	}

	IEnumerable<TwineOutput> passageExecute_5()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <smile>%");
		yield return new TwineText(@"PATRICE: The cow? Hah! Yeah, like I spend a lot of time with her.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: What now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I want to hear your opinion of the other women staying in the castle.", @"I want to hear your opinion of the other women staying in the castle.", @"women", null, null);
		yield return new TwineLink(@"%pat_approval,-30,0%How are you enjoying your stay here?", @"%pat_approval,-30,0%How are you enjoying your stay here?", @"stay1", null, null);
		yield return new TwineLink(@"%pat_approval,1,30%How are you enjoying your stay here?", @"%pat_approval,1,30%How are you enjoying your stay here?", @"stay2", null, null);
		yield return new TwineLink(@"%pat_approval,31,50%How are you enjoying your stay here?", @"%pat_approval,31,50%How are you enjoying your stay here?", @"stay3", null, null);
		yield return new TwineLink(@"%pat_approval,51,70%How are you enjoying your stay here?", @"%pat_approval,51,70%How are you enjoying your stay here?", @"stay4", null, null);
		yield return new TwineLink(@"Let's talk about you.", @"Let's talk about you.", @"you", null, null);	
	}
    
	// .............
	// #6: h2

	void passageInit_6()
	{
		this.Passages["h2"] = new TwinePassage("h2", new string[]{  }, passageExecute_6);
	}

	IEnumerable<TwineOutput> passageExecute_6()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <neutral>%");
		yield return new TwineText(@"PATRICE: Hen's a good one. A cow, but a good one. Doesn't care how much I swear, unlike some other people I could name.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: What now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I want to hear your opinion of the other women staying in the castle.", @"I want to hear your opinion of the other women staying in the castle.", @"women", null, null);
		yield return new TwineLink(@"%pat_approval,-30,0%How are you enjoying your stay here?", @"%pat_approval,-30,0%How are you enjoying your stay here?", @"stay1", null, null);
		yield return new TwineLink(@"%pat_approval,1,30%How are you enjoying your stay here?", @"%pat_approval,1,30%How are you enjoying your stay here?", @"stay2", null, null);
		yield return new TwineLink(@"%pat_approval,31,50%How are you enjoying your stay here?", @"%pat_approval,31,50%How are you enjoying your stay here?", @"stay3", null, null);
		yield return new TwineLink(@"%pat_approval,51,70%How are you enjoying your stay here?", @"%pat_approval,51,70%How are you enjoying your stay here?", @"stay4", null, null);
		yield return new TwineLink(@"Let's talk about you.", @"Let's talk about you.", @"you", null, null);	
	}
    
	// .............
	// #7: j1

	void passageInit_7()
	{
		this.Passages["j1"] = new TwinePassage("j1", new string[]{  }, passageExecute_7);
	}

	IEnumerable<TwineOutput> passageExecute_7()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <neutral>%");
		yield return new TwineText(@"PATRICE: Jane and I haven't talked much yet, but I like her well enough. ");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: What now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I want to hear your opinion of the other women staying in the castle.", @"I want to hear your opinion of the other women staying in the castle.", @"women", null, null);
		yield return new TwineLink(@"%pat_approval,-30,0%How are you enjoying your stay here?", @"%pat_approval,-30,0%How are you enjoying your stay here?", @"stay1", null, null);
		yield return new TwineLink(@"%pat_approval,1,30%How are you enjoying your stay here?", @"%pat_approval,1,30%How are you enjoying your stay here?", @"stay2", null, null);
		yield return new TwineLink(@"%pat_approval,31,50%How are you enjoying your stay here?", @"%pat_approval,31,50%How are you enjoying your stay here?", @"stay3", null, null);
		yield return new TwineLink(@"%pat_approval,51,70%How are you enjoying your stay here?", @"%pat_approval,51,70%How are you enjoying your stay here?", @"stay4", null, null);
		yield return new TwineLink(@"Let's talk about you.", @"Let's talk about you.", @"you", null, null);	
	}
    
	// .............
	// #8: j2

	void passageInit_8()
	{
		this.Passages["j2"] = new TwinePassage("j2", new string[]{  }, passageExecute_8);
	}

	IEnumerable<TwineOutput> passageExecute_8()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <smile>%");
		yield return new TwineText(@"PATRICE: Jane's great! She's someone who gets it. Really gets it. ");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <pat>, <center>, <neutral>%");
		yield return new TwineText(@"PATRICE: Too bad she doesn't have anything from home to remember her family by. Fuck knows I wouldn't want anything to remember mine by, but Jane's family is different. She misses them.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: What now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I want to hear your opinion of the other women staying in the castle.", @"I want to hear your opinion of the other women staying in the castle.", @"women", null, null);
		yield return new TwineLink(@"%pat_approval,-30,0%How are you enjoying your stay here?", @"%pat_approval,-30,0%How are you enjoying your stay here?", @"stay1", null, null);
		yield return new TwineLink(@"%pat_approval,1,30%How are you enjoying your stay here?", @"%pat_approval,1,30%How are you enjoying your stay here?", @"stay2", null, null);
		yield return new TwineLink(@"%pat_approval,31,50%How are you enjoying your stay here?", @"%pat_approval,31,50%How are you enjoying your stay here?", @"stay3", null, null);
		yield return new TwineLink(@"%pat_approval,51,70%How are you enjoying your stay here?", @"%pat_approval,51,70%How are you enjoying your stay here?", @"stay4", null, null);
		yield return new TwineLink(@"Let's talk about you.", @"Let's talk about you.", @"you", null, null);	
	}
    
	// .............
	// #9: women

	void passageInit_9()
	{
		this.Passages["women"] = new TwinePassage("women", new string[]{  }, passageExecute_9);
	}

	IEnumerable<TwineOutput> passageExecute_9()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <frown>%");
		yield return new TwineText(@"PATRICE: Sure, fine, whatever. Shoot.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"%day, 1, 2%Jane.", @"%day, 1, 2%Jane.", @"j1", null, null);
		yield return new TwineLink(@"%day, 3, 6%Jane.", @"%day, 3, 6%Jane.", @"j2", null, null);
		yield return new TwineLink(@"%day, 1, 2%Pat.", @"%day, 1, 2%Pat.", @"p1", null, null);
		yield return new TwineLink(@"%day, 3, 6%Pat.", @"%day, 3, 6%Pat.", @"p2", null, null);
		yield return new TwineLink(@"%day, 1, 2%Noelle.", @"%day, 1, 2%Noelle.", @"n1", null, null);
		yield return new TwineLink(@"%day, 3, 6%Noelle.", @"%day, 3, 6%Noelle.", @"n2", null, null);
		yield return new TwineLink(@"%day, 1, 2%Henrietta.", @"%day, 1, 2%Henrietta.", @"h1", null, null);
		yield return new TwineLink(@"%day, 3, 6%Henrietta.", @"%day, 3, 6%Henrietta.", @"h2", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"leave", null, null);	
	}
    
	// .............
	// #10: p1

	void passageInit_10()
	{
		this.Passages["p1"] = new TwinePassage("p1", new string[]{  }, passageExecute_10);
	}

	IEnumerable<TwineOutput> passageExecute_10()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <neutral>%");
		yield return new TwineText(@"PATRICE: Pat? She's alright, I guess. Haven't really seen her much. But she always <i>smiles</i> at me. It's...weird.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: What now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I want to hear your opinion of the other women staying in the castle.", @"I want to hear your opinion of the other women staying in the castle.", @"women", null, null);
		yield return new TwineLink(@"%pat_approval,-30,0%How are you enjoying your stay here?", @"%pat_approval,-30,0%How are you enjoying your stay here?", @"stay1", null, null);
		yield return new TwineLink(@"%pat_approval,1,30%How are you enjoying your stay here?", @"%pat_approval,1,30%How are you enjoying your stay here?", @"stay2", null, null);
		yield return new TwineLink(@"%pat_approval,31,50%How are you enjoying your stay here?", @"%pat_approval,31,50%How are you enjoying your stay here?", @"stay3", null, null);
		yield return new TwineLink(@"%pat_approval,51,70%How are you enjoying your stay here?", @"%pat_approval,51,70%How are you enjoying your stay here?", @"stay4", null, null);
		yield return new TwineLink(@"Let's talk about you.", @"Let's talk about you.", @"you", null, null);	
	}
    
	// .............
	// #11: p2

	void passageInit_11()
	{
		this.Passages["p2"] = new TwinePassage("p2", new string[]{  }, passageExecute_11);
	}

	IEnumerable<TwineOutput> passageExecute_11()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <neutral>%");
		yield return new TwineText(@"PATRICE: Pat's a good sort. Just...nice. She tries to mother me sometimes, though. I could do without that.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: What now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I want to hear your opinion of the other women staying in the castle.", @"I want to hear your opinion of the other women staying in the castle.", @"women", null, null);
		yield return new TwineLink(@"%pat_approval,-30,0%How are you enjoying your stay here?", @"%pat_approval,-30,0%How are you enjoying your stay here?", @"stay1", null, null);
		yield return new TwineLink(@"%pat_approval,1,30%How are you enjoying your stay here?", @"%pat_approval,1,30%How are you enjoying your stay here?", @"stay2", null, null);
		yield return new TwineLink(@"%pat_approval,31,50%How are you enjoying your stay here?", @"%pat_approval,31,50%How are you enjoying your stay here?", @"stay3", null, null);
		yield return new TwineLink(@"%pat_approval,51,70%How are you enjoying your stay here?", @"%pat_approval,51,70%How are you enjoying your stay here?", @"stay4", null, null);
		yield return new TwineLink(@"Let's talk about you.", @"Let's talk about you.", @"you", null, null);	
	}
    
	// .............
	// #12: n1

	void passageInit_12()
	{
		this.Passages["n1"] = new TwinePassage("n1", new string[]{  }, passageExecute_12);
	}

	IEnumerable<TwineOutput> passageExecute_12()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <frown>%");
		yield return new TwineText(@"PATRICE: Noelle smiles a lot, but she doesn't mean it. I don't trust her. And her face goes all sharp when I swear around her.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: What now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I want to hear your opinion of the other women staying in the castle.", @"I want to hear your opinion of the other women staying in the castle.", @"women", null, null);
		yield return new TwineLink(@"%pat_approval,-30,0%How are you enjoying your stay here?", @"%pat_approval,-30,0%How are you enjoying your stay here?", @"stay1", null, null);
		yield return new TwineLink(@"%pat_approval,1,30%How are you enjoying your stay here?", @"%pat_approval,1,30%How are you enjoying your stay here?", @"stay2", null, null);
		yield return new TwineLink(@"%pat_approval,31,50%How are you enjoying your stay here?", @"%pat_approval,31,50%How are you enjoying your stay here?", @"stay3", null, null);
		yield return new TwineLink(@"%pat_approval,51,70%How are you enjoying your stay here?", @"%pat_approval,51,70%How are you enjoying your stay here?", @"stay4", null, null);
		yield return new TwineLink(@"Let's talk about you.", @"Let's talk about you.", @"you", null, null);	
	}
    
	// .............
	// #13: n2

	void passageInit_13()
	{
		this.Passages["n2"] = new TwinePassage("n2", new string[]{  }, passageExecute_13);
	}

	IEnumerable<TwineOutput> passageExecute_13()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <neutral>%");
		yield return new TwineText(@"PATRICE: Noelle's...I don't know. She's weird. Doesn't mean what she says half the time, but...");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: I don't know. Nevermind.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: What now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I want to hear your opinion of the other women staying in the castle.", @"I want to hear your opinion of the other women staying in the castle.", @"women", null, null);
		yield return new TwineLink(@"%pat_approval,-30,0%How are you enjoying your stay here?", @"%pat_approval,-30,0%How are you enjoying your stay here?", @"stay1", null, null);
		yield return new TwineLink(@"%pat_approval,1,30%How are you enjoying your stay here?", @"%pat_approval,1,30%How are you enjoying your stay here?", @"stay2", null, null);
		yield return new TwineLink(@"%pat_approval,31,50%How are you enjoying your stay here?", @"%pat_approval,31,50%How are you enjoying your stay here?", @"stay3", null, null);
		yield return new TwineLink(@"%pat_approval,51,70%How are you enjoying your stay here?", @"%pat_approval,51,70%How are you enjoying your stay here?", @"stay4", null, null);
		yield return new TwineLink(@"Let's talk about you.", @"Let's talk about you.", @"you", null, null);	
	}
    
	// .............
	// #14: I'm assuming he's out of the picture now, or you wouldn't be here.

	void passageInit_14()
	{
		this.Passages["I'm assuming he's out of the picture now, or you wouldn't be here."] = new TwinePassage("I'm assuming he's out of the picture now, or you wouldn't be here.", new string[]{  }, passageExecute_14);
	}

	IEnumerable<TwineOutput> passageExecute_14()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <neutral>%");
		yield return new TwineText(@"PATRICE: ...Yes. He died.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I'm so sorry.", @"I'm so sorry.", @"I'm so sorry.", null, null);
		yield return new TwineLink(@"And you haven't moved on since then?", @"And you haven't moved on since then?", @"And you haven't moved on since then?", null, null);
		yield return new TwineLink(@"How long ago was that?", @"How long ago was that?", @"How long ago was that?", null, null);	
	}
    
	// .............
	// #15: You didn't think to mention this earlier?

	void passageInit_15()
	{
		this.Passages["You didn't think to mention this earlier?"] = new TwinePassage("You didn't think to mention this earlier?", new string[]{  }, passageExecute_15);
	}

	IEnumerable<TwineOutput> passageExecute_15()
	{
		yield return new TwineText(@"#pat_approval, -5#");
		yield return new TwineText(@"%1, <pat>, <center>, <neutral>%");
		yield return new TwineText(@"PATRICE: Well...no. It didn't really seem...important.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"You were wrong.", @"You were wrong.", @"You were wrong.", null, null);
		yield return new TwineLink(@"And you haven't moved on since then?", @"And you haven't moved on since then?", @"And you haven't moved on since then?", null, null);
		yield return new TwineLink(@"How long ago was that?", @"How long ago was that?", @"How long ago was that?", null, null);	
	}
    
	// .............
	// #16: What happened?

	void passageInit_16()
	{
		this.Passages["What happened?"] = new TwinePassage("What happened?", new string[]{  }, passageExecute_16);
	}

	IEnumerable<TwineOutput> passageExecute_16()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <neutral>%");
		yield return new TwineText(@"PATRICE: Oh, it just, um.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: He died, your highness. Just after--um. He just died. I would've mentioned it earlier if I thought it was important.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"You should have.", @"You should have.", @"You were wrong.", null, null);
		yield return new TwineLink(@"And you haven't moved on since then?", @"And you haven't moved on since then?", @"And you haven't moved on since then?", null, null);
		yield return new TwineLink(@"How long ago was that?", @"How long ago was that?", @"How long ago was that?", null, null);	
	}
    
	// .............
	// #17: fam

	void passageInit_17()
	{
		this.Passages["fam"] = new TwinePassage("fam", new string[]{  }, passageExecute_17);
	}

	IEnumerable<TwineOutput> passageExecute_17()
	{
		yield return new TwineText(@"#convo_points, -1#");
		yield return new TwineText(@"%1, <pat>, <center>, <neutral>%");
		yield return new TwineText(@"PATRICE: Oh. Um, well. I...I suppose this is as good a time as any to tell you.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: I've been married once before.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"What happened?", @"What happened?", @"What happened?", null, null);
		yield return new TwineLink(@"I'm assuming he's out of the picture now, or you wouldn't be here.", @"I'm assuming he's out of the picture now, or you wouldn't be here.", @"I'm assuming he's out of the picture now, or you wouldn't be here.", null, null);
		yield return new TwineLink(@"You didn't think to mention this earlier?", @"You didn't think to mention this earlier?", @"You didn't think to mention this earlier?", null, null);	
	}
    
	// .............
	// #18: you

	void passageInit_18()
	{
		this.Passages["you"] = new TwinePassage("you", new string[]{  }, passageExecute_18);
	}

	IEnumerable<TwineOutput> passageExecute_18()
	{
		yield return new TwineText(@"PATRICE: Oh! Yes. Yes, right. What would you like to know?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"%pat_convo, 0, 0%Where are you from?", @"%pat_convo, 0, 0%Where are you from?", @"from", null, null);
		yield return new TwineLink(@"%pat_convo, 1, 1%What's your family like?", @"%pat_convo, 1, 1%What's your family like?", @"fam", null, null);
		yield return new TwineLink(@"%pat_convo, 2, 2%If you could go anywhere in the world, where would you go?", @"%pat_convo, 2, 2%If you could go anywhere in the world, where would you go?", @"world", null, null);
		yield return new TwineLink(@"%pat_convo, 3, 3%You don't seem to like to talk about your family.", @"%pat_convo, 3, 3%You don't seem to like to talk about your family.", @"secret", null, null);
		yield return new TwineLink(@"%pat_convo, 4, 4%Why are you always so polite?", @"%pat_convo, 4, 4%Why are you always so polite?", @"polite", null, null);
		yield return new TwineLink(@"%pat_convo, 5, 5%You seem unusually bothered. Is everything alright?", @"%pat_convo, 5, 5%You seem unusually bothered. Is everything alright?", @"trouble", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"leave", null, null);	
	}
    
	// .............
	// #19: I'm so sorry.

	void passageInit_19()
	{
		this.Passages["I'm so sorry."] = new TwinePassage("I'm so sorry.", new string[]{  }, passageExecute_19);
	}

	IEnumerable<TwineOutput> passageExecute_19()
	{
		yield return new TwineText(@"#pat_approval, +10#");
		yield return new TwineText(@"%1, <pat>, <center>, <neutral>%");
		yield return new TwineText(@"PATRICE: Yes, well. Thank you for understanding. It's been very difficult to move on.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: Oh! But, I mean, I'm ready now. I mean--I'm here because--oh, goodness. I'm sorry. I get so flustered.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Relax. I know this isn't an ideal situation.]]
		[[Well, despite the tragedy of the event, I'm glad you're here.", @"Relax. I know this isn't an ideal situation.]]
		[[Well, despite the tragedy of the event, I'm glad you're here.", @"Frankly, I'm glad you're here at all.", null, null);
		yield return new TwineLink(@"No, please. It's nice to hear a new voice.", @"No, please. It's nice to hear a new voice.", @"No, please. It's nice to hear a new voice.", null, null);	
	}
    
	// .............
	// #20: How long ago was that?

	void passageInit_20()
	{
		this.Passages["How long ago was that?"] = new TwinePassage("How long ago was that?", new string[]{  }, passageExecute_20);
	}

	IEnumerable<TwineOutput> passageExecute_20()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <neutral>%");
		yield return new TwineText(@"PATRICE: A few years ago, now. Although, sometimes, it feels like it happened just yesterday.");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <pat>, <center>, <smile>%");
		yield return new TwineText(@"PATRICE: Please excuse me. I didn't mean to go prattling on.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Really? It seems that way.]]
		[[Well, despite the tragedy of the event, I'm glad you're here.", @"Really? It seems that way.]]
		[[Well, despite the tragedy of the event, I'm glad you're here.", @"Frankly, I'm glad you're here at all.", null, null);
		yield return new TwineLink(@"No, please. It's nice to hear a new voice.", @"No, please. It's nice to hear a new voice.", @"No, please. It's nice to hear a new voice.", null, null);	
	}
    
	// .............
	// #21: And you haven't moved on since then?

	void passageInit_21()
	{
		this.Passages["And you haven't moved on since then?"] = new TwinePassage("And you haven't moved on since then?", new string[]{  }, passageExecute_21);
	}

	IEnumerable<TwineOutput> passageExecute_21()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <neutral>%");
		yield return new TwineText(@"PATRICE: I'm afraid not. There hasn't really been much opportunity to, I'm afraid.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: Not--not that I'm here as a last resort!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Really? It seems that way.", @"Really? It seems that way.", @"Really? It seems that way.", null, null);
		yield return new TwineLink(@"Relax. I know this isn't an ideal situation.", @"Relax. I know this isn't an ideal situation.", @"Relax. I know this isn't an ideal situation.", null, null);
		yield return new TwineLink(@"Frankly, I'm glad you're here at all.", @"Frankly, I'm glad you're here at all.", @"Frankly, I'm glad you're here at all.", null, null);	
	}
    
	// .............
	// #22: You were wrong.

	void passageInit_22()
	{
		this.Passages["You were wrong."] = new TwinePassage("You were wrong.", new string[]{  }, passageExecute_22);
	}

	IEnumerable<TwineOutput> passageExecute_22()
	{
		yield return new TwineText(@"#pat_approval, -5#");
		yield return new TwineText(@"%1, <pat>, <center>, <scared>%");
		yield return new TwineText(@"PATRICE: M-my apologies, sire. I didn't mean to offend.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: Would you please excuse me? I think I need some fresh air.");	
	}
    
	// .............
	// #23: from

	void passageInit_23()
	{
		this.Passages["from"] = new TwinePassage("from", new string[]{  }, passageExecute_23);
	}

	IEnumerable<TwineOutput> passageExecute_23()
	{
		yield return new TwineText(@"#convo_points, -1#");
		yield return new TwineText(@"PATRICE: I live in Westham. It's a lovely town, really. Very quiet, peaceful. Full of friendly people who are always eager to help you get back on your feet.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"It sounds like you fit in well there.", @"It sounds like you fit in well there.", @"It sounds like you fit in well there.", null, null);
		yield return new TwineLink(@"You have a lot of experience with getting back on your feet?", @"You have a lot of experience with getting back on your feet?", @"You have a lot of experience with getting back on your feet?", null, null);
		yield return new TwineLink(@"Who do you live with?", @"Who do you live with?", @"Who do you live with?", null, null);	
	}
    
	// .............
	// #24: world

	void passageInit_24()
	{
		this.Passages["world"] = new TwinePassage("world", new string[]{  }, passageExecute_24);
	}

	IEnumerable<TwineOutput> passageExecute_24()
	{
		yield return new TwineText(@"#convo_points, -1#");
		yield return new TwineText(@"%1, <pat>, <center>, <scared>%");
		yield return new TwineText(@"PATRICE: Oh, goodness.");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <pat>, <center>, <neutral>%");
		yield return new TwineText(@"PATRICE: I really don't know. There's no place like home--I don't think I'd want to leave it for very long.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: Not that I'm not happy to be here! I'm just a homebody.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Do you think this castle could ever feel like home to you?", @"Do you think this castle could ever feel like home to you?", @"Do you think this castle could ever feel like home to you?", null, null);
		yield return new TwineLink(@"Well, I'm happy to have you in my home.", @"Well, I'm happy to have you in my home.", @"Well, I'm happy to have you in my home.", null, null);
		yield return new TwineLink(@"Really? There's nowhere you'd like to go?", @"Really? There's nowhere you'd like to go?", @"Really? There's nowhere you'd like to go?", null, null);	
	}
    
	// .............
	// #25: polite

	void passageInit_25()
	{
		this.Passages["polite"] = new TwinePassage("polite", new string[]{  }, passageExecute_25);
	}

	IEnumerable<TwineOutput> passageExecute_25()
	{
		yield return new TwineText(@"#convo_points, -1#");
		yield return new TwineText(@"%1, <pat>, <center>, <scared>%");
		yield return new TwineText(@"PATRICE: I hadn't realized the way I behaved was strange.");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <pat>, <center>, <neutral>%");
		yield return new TwineText(@"PATRICE: I was just raised to behave politely, I suppose.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"That can't be the only reason.", @"That can't be the only reason.", @"That can't be the only reason.", null, null);
		yield return new TwineLink(@"I didn't mean to make you self-conscious.", @"I didn't mean to make you self-conscious.", @"I didn't mean to make you self-conscious.", null, null);
		yield return new TwineLink(@"I could learn a thing or two from you.", @"I could learn a thing or two from you.", @"I could learn a thing or two from you.", null, null);	
	}
    
	// .............
	// #26: No, please. It's nice to hear a new voice.

	void passageInit_26()
	{
		this.Passages["No, please. It's nice to hear a new voice."] = new TwinePassage("No, please. It's nice to hear a new voice.", new string[]{  }, passageExecute_26);
	}

	IEnumerable<TwineOutput> passageExecute_26()
	{
		yield return new TwineText(@"#pat_approval, +5#");
		yield return new TwineText(@"%1, <pat>, <center>, <blush>%");
		yield return new TwineText(@"PATRICE: Right. I suppose I should've known you wouldn't be getting many new people through the castle, what with...");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: Oh, lord. Please, excuse me. Could we talk about something else, please?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Certainly.", @"Certainly.", @"else", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"leave", null, null);	
	}
    
	// .............
	// #27: Frankly, I'm glad you're here at all.

	void passageInit_27()
	{
		this.Passages["Frankly, I'm glad you're here at all."] = new TwinePassage("Frankly, I'm glad you're here at all.", new string[]{  }, passageExecute_27);
	}

	IEnumerable<TwineOutput> passageExecute_27()
	{
		yield return new TwineText(@"#pat_approval, +5#");
		yield return new TwineText(@"%1, <pat>, <center>, <blush>%");
		yield return new TwineText(@"PATRICE: Oh! Well, that's good. Thank you, sire. ");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: Could we talk about something else now, please?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Certainly.", @"Certainly.", @"else", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"leave", null, null);	
	}
    
	// .............
	// #28: Really? It seems that way.

	void passageInit_28()
	{
		this.Passages["Really? It seems that way."] = new TwinePassage("Really? It seems that way.", new string[]{  }, passageExecute_28);
	}

	IEnumerable<TwineOutput> passageExecute_28()
	{
		yield return new TwineText(@"#pat_approval, -5#");
		yield return new TwineText(@"%1, <pat>, <center>, <blush>%");
		yield return new TwineText(@"PATRICE: How mortifying. I'm <i>so</i> sorry, sire. I didn't mean to imply...");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: Oh, goodness. Could we talk about something else, please?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Certainly.", @"Certainly.", @"else", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"leave", null, null);	
	}
    
	// .............
	// #29: Relax. I know this isn't an ideal situation.

	void passageInit_29()
	{
		this.Passages["Relax. I know this isn't an ideal situation."] = new TwinePassage("Relax. I know this isn't an ideal situation.", new string[]{  }, passageExecute_29);
	}

	IEnumerable<TwineOutput> passageExecute_29()
	{
		yield return new TwineText(@"#pat_approval, +5#");
		yield return new TwineText(@"%1, <pat>, <center>, <blush>%");
		yield return new TwineText(@"PATRICE: Thank you for understanding. I really am happy to be here, it's just...");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: A lot to take in.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: Could we talk about something else, please?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Certainly.", @"Certainly.", @"else", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"leave", null, null);	
	}
    
	// .............
	// #30: It sounds like you fit in well there.

	void passageInit_30()
	{
		this.Passages["It sounds like you fit in well there."] = new TwinePassage("It sounds like you fit in well there.", new string[]{  }, passageExecute_30);
	}

	IEnumerable<TwineOutput> passageExecute_30()
	{
		yield return new TwineText(@"#pat_approval, +5#");
		yield return new TwineText(@"%1, <pat>, <center>, <blush>%");
		yield return new TwineText(@"PATRICE: I certainly try to. But it's not easy, what with...");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: ...Well.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: I hope you have people who make you feel like you belong somewhere, too.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Just Beauregard.", @"Just Beauregard.", @"Just Beauregard.", null, null);
		yield return new TwineLink(@"I look out for myself.", @"I look out for myself.", @"I look out for myself.", null, null);	
	}
    
	// .............
	// #31: You have a lot of experience with getting back on your feet?

	void passageInit_31()
	{
		this.Passages["You have a lot of experience with getting back on your feet?"] = new TwinePassage("You have a lot of experience with getting back on your feet?", new string[]{  }, passageExecute_31);
	}

	IEnumerable<TwineOutput> passageExecute_31()
	{
		yield return new TwineText(@"#pat_approval, -5#");
		yield return new TwineText(@"%1, <pat>, <center>, <frown>%");
		yield return new TwineText(@"PATRICE: As much as anyone has, yes, I suppose. ");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: Have you not had people to help you in your life, sire?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Just Beauregard.", @"Just Beauregard.", @"Just Beauregard.", null, null);
		yield return new TwineLink(@"I look out for myself.", @"I look out for myself.", @"I look out for myself.", null, null);	
	}
    
	// .............
	// #32: Who do you live with?

	void passageInit_32()
	{
		this.Passages["Who do you live with?"] = new TwinePassage("Who do you live with?", new string[]{  }, passageExecute_32);
	}

	IEnumerable<TwineOutput> passageExecute_32()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <smile>%");
		yield return new TwineText(@"PATRICE: Oh, just my--");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <pat>, <center>, <scared>%");
		yield return new TwineText(@"PATRICE: --my mother. Just with my mother.");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <pat>, <center>, <neutral>%");
		yield return new TwineText(@"PATRICE: What about you, sire? Is Mr. Beauregard your only companion?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Yes.", @"Yes.", @"Just Beauregard.", null, null);
		yield return new TwineLink(@"Even with him here, I still feel alone.", @"Even with him here, I still feel alone.", @"Even with him here, I still feel alone.", null, null);	
	}
    
	// .............
	// #33: Do you think this castle could ever feel like home to you?

	void passageInit_33()
	{
		this.Passages["Do you think this castle could ever feel like home to you?"] = new TwinePassage("Do you think this castle could ever feel like home to you?", new string[]{  }, passageExecute_33);
	}

	IEnumerable<TwineOutput> passageExecute_33()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <scared>%");
		yield return new TwineText(@"PATRICE: Oh. Well, um.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: Not...Not right now, but maybe, given time...");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <pat>, <center>, <smile>%");
		yield return new TwineText(@"PATRICE: Yes. Yes, I think it could.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: Did you have any other questions for me, sire?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Certainly.", @"Certainly.", @"else", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"leave", null, null);	
	}
    
	// .............
	// #34: Well, I'm happy to have you in my home.

	void passageInit_34()
	{
		this.Passages["Well, I'm happy to have you in my home."] = new TwinePassage("Well, I'm happy to have you in my home.", new string[]{  }, passageExecute_34);
	}

	IEnumerable<TwineOutput> passageExecute_34()
	{
		yield return new TwineText(@"#pat_approval, +5#");
		yield return new TwineText(@"%1, <pat>, <center>, <smile>%");
		yield return new TwineText(@"PATRICE: Thank you, sire. I'm happy to be here for as long as you'll have me. ");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: Did you have any other questions for me, sire?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Certainly.", @"Certainly.", @"else", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"leave", null, null);	
	}
    
	// .............
	// #35: Really? There's nowhere you'd like to go?

	void passageInit_35()
	{
		this.Passages["Really? There's nowhere you'd like to go?"] = new TwinePassage("Really? There's nowhere you'd like to go?", new string[]{  }, passageExecute_35);
	}

	IEnumerable<TwineOutput> passageExecute_35()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <frown>%");
		yield return new TwineText(@"PATRICE: Well...I suppose...");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <pat>, <center>, <smile>%");
		yield return new TwineText(@"PATRICE: I <i>have</i> always wanted to see the ocean.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: Have you ever been there, sire?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Not recently.", @"Not recently.", @"Not recently.", null, null);
		yield return new TwineLink(@"I have. It really is magnificent.", @"I have. It really is magnificent.", @"I have. It really is magnificent.", null, null);	
	}
    
	// .............
	// #36: That can't be the only reason.

	void passageInit_36()
	{
		this.Passages["That can't be the only reason."] = new TwinePassage("That can't be the only reason.", new string[]{  }, passageExecute_36);
	}

	IEnumerable<TwineOutput> passageExecute_36()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <scared>%");
		yield return new TwineText(@"PATRICE: ...");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <pat>, <center>, <neutral>%");
		yield return new TwineText(@"PATRICE: I suppose--");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: I suppose that, after my husband died, I was trying to make up for always being so indebted to people. I mean, what with--");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: --my family--");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: --I mean, my mother, of course--");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: --I needed a lot of help from people to get by. In a way, my trip here is another part of that. I just feel so indebted to my home town.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I didn't mean to make you self-conscious.", @"I didn't mean to make you self-conscious.", @"I didn't mean to make you self-conscious.", null, null);
		yield return new TwineLink(@"I could learn a thing or two from you.", @"I could learn a thing or two from you.", @"I could learn a thing or two from you.", null, null);
		yield return new TwineLink(@"This is the second time you've been uncomfortable discussing your family.", @"This is the second time you've been uncomfortable discussing your family.", @"This is the second time you've been uncomfortable discussing your family.", null, null);	
	}
    
	// .............
	// #37: I didn't mean to make you self-conscious.

	void passageInit_37()
	{
		this.Passages["I didn't mean to make you self-conscious."] = new TwinePassage("I didn't mean to make you self-conscious.", new string[]{  }, passageExecute_37);
	}

	IEnumerable<TwineOutput> passageExecute_37()
	{
		yield return new TwineText(@"#pat_approval, +5#");
		yield return new TwineText(@"%1, <pat>, <center>, <smile>%");
		yield return new TwineText(@"PATRICE: No, no, I'm fine! I'd just never thought about it before.");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <pat>, <center>, <neutral>%");
		yield return new TwineText(@"PATRICE: I suppose, with the changing of the times, people are becoming less formal. Well, we common folk, at least.");	
	}
    
	// .............
	// #38: I could learn a thing or two from you.

	void passageInit_38()
	{
		this.Passages["I could learn a thing or two from you."] = new TwinePassage("I could learn a thing or two from you.", new string[]{  }, passageExecute_38);
	}

	IEnumerable<TwineOutput> passageExecute_38()
	{
		yield return new TwineText(@"#pat_approval, +10#");
		yield return new TwineText(@"%1, <pat>, <center>, <blush>%");
		yield return new TwineText(@"PATRICE: Oh, goodness.");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <pat>, <center>, <smile>%");
		yield return new TwineText(@"PATRICE: I, um. That's very kind of you to say, sire, but I don't see how that could be true.");	
	}
    
	// .............
	// #39: I look out for myself.

	void passageInit_39()
	{
		this.Passages["I look out for myself."] = new TwinePassage("I look out for myself.", new string[]{  }, passageExecute_39);
	}

	IEnumerable<TwineOutput> passageExecute_39()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <frown>%");
		yield return new TwineText(@"PATRICE: That...sounds very lonely, sire. ");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: It must be nice to be independent, but to be all alone in this enormous castle? ");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Beauregard makes it easier.", @"Beauregard makes it easier.", @"He is.", null, null);
		yield return new TwineLink(@"I prefer to be alone.", @"I prefer to be alone.", @"I prefer to be alone.", null, null);	
	}
    
	// .............
	// #40: Just Beauregard.

	void passageInit_40()
	{
		this.Passages["Just Beauregard."] = new TwinePassage("Just Beauregard.", new string[]{  }, passageExecute_40);
	}

	IEnumerable<TwineOutput> passageExecute_40()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <smile>%");
		yield return new TwineText(@"PATRICE: Well, Beauregard certainly seems like a good person to have by your side.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"He is.", @"He is.", @"He is.", null, null);
		yield return new TwineLink(@"He's not perfect. We argue, just like everyone else.", @"He's not perfect. We argue, just like everyone else.", @"He's not perfect. We argue, just like everyone else.", null, null);	
	}
    
	// .............
	// #41: Even with him here, I still feel alone.

	void passageInit_41()
	{
		this.Passages["Even with him here, I still feel alone."] = new TwinePassage("Even with him here, I still feel alone.", new string[]{  }, passageExecute_41);
	}

	IEnumerable<TwineOutput> passageExecute_41()
	{
		yield return new TwineText(@"#pat_approval, +5#");
		yield return new TwineText(@"%1, <pat>, <center>, <sad>%");
		yield return new TwineText(@"PATRICE: That's awful!");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: If that's how it feels to live here all alone, then I think I can understand why you summoned us all here.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I'm sorry about that.]]
		[[Beauregard makes it easier.", @"I'm sorry about that.]]
		[[Beauregard makes it easier.", @"He is.", null, null);	
	}
    
	// .............
	// #42: Not recently.

	void passageInit_42()
	{
		this.Passages["Not recently."] = new TwinePassage("Not recently.", new string[]{  }, passageExecute_42);
	}

	IEnumerable<TwineOutput> passageExecute_42()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <scared>%");
		yield return new TwineText(@"PATRICE: Yes, of course. Of course you couldn't, what with the...yes. Right.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"It's alright. I know what I look like.", @"It's alright. I know what I look like.", @"It's alright. I know what I look like.", null, null);
		yield return new TwineLink(@"I don't need your pity.", @"I don't need your pity.", @"I don't need your pity.", null, null);
		yield return new TwineLink(@"Nothing anyone could say at this point would offend me.", @"Nothing anyone could say at this point would offend me.", @"Nothing anyone could say at this point would offend me.", null, null);	
	}
    
	// .............
	// #43: I have. It really is magnificent.

	void passageInit_43()
	{
		this.Passages["I have. It really is magnificent."] = new TwinePassage("I have. It really is magnificent.", new string[]{  }, passageExecute_43);
	}

	IEnumerable<TwineOutput> passageExecute_43()
	{
		yield return new TwineText(@"#pat_approval, +5#");
		yield return new TwineText(@"%1, <pat>, <center>, <smile>%");
		yield return new TwineText(@"PATRICE: Oh, wonderful. I knew it would be! ");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: How did you manage it, looking like--um. Well. Nevermind!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"It's alright. I know what I look like.", @"It's alright. I know what I look like.", @"It's alright. I know what I look like.", null, null);
		yield return new TwineLink(@"I don't need your pity.", @"I don't need your pity.", @"I don't need your pity.", null, null);
		yield return new TwineLink(@"Nothing anyone could say at this point would offend me.", @"Nothing anyone could say at this point would offend me.", @"Nothing anyone could say at this point would offend me.", null, null);	
	}
    
	// .............
	// #44: This is the second time you've been uncomfortable discussing your family.

	void passageInit_44()
	{
		this.Passages["This is the second time you've been uncomfortable discussing your family."] = new TwinePassage("This is the second time you've been uncomfortable discussing your family.", new string[]{  }, passageExecute_44);
	}

	IEnumerable<TwineOutput> passageExecute_44()
	{
		yield return new TwineText(@"#pat_approval, -5#");
		yield return new TwineText(@"%1, <pat>, <center>, <scared>%");
		yield return new TwineText(@"PATRICE: Oh! Um?");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: I'm--I'm not sure I know what you're talking about--");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: Would you please excuse me? I think I need some fresh air.");	
	}
    
	// .............
	// #45: leave

	void passageInit_45()
	{
		this.Passages["leave"] = new TwinePassage("leave", new string[]{  }, passageExecute_45);
	}

	IEnumerable<TwineOutput> passageExecute_45()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <smile>%");
		yield return new TwineText(@"PATRICE: Of course. I hope you have a pleasant day, sire.");	
	}
    
	// .............
	// #46: I prefer to be alone.

	void passageInit_46()
	{
		this.Passages["I prefer to be alone."] = new TwinePassage("I prefer to be alone.", new string[]{  }, passageExecute_46);
	}

	IEnumerable<TwineOutput> passageExecute_46()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <neutral>%");
		yield return new TwineText(@"PATRICE: ...Oh. I suppose I should be going, then.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: Unless--Do you have any other questions for me, sire?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I do.", @"I do.", @"else", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"leave", null, null);	
	}
    
	// .............
	// #47: He is.

	void passageInit_47()
	{
		this.Passages["He is."] = new TwinePassage("He is.", new string[]{  }, passageExecute_47);
	}

	IEnumerable<TwineOutput> passageExecute_47()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <smile>%");
		yield return new TwineText(@"PATRICE: That's so good to hear!");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: I'm glad you have someone here to support you. It can't be easy, dealing with...the things you have to deal with.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: Did you have any other questions for me, sire?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Certainly.", @"Certainly.", @"else", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"leave", null, null);	
	}
    
	// .............
	// #48: He's not perfect. We argue, just like everyone else.

	void passageInit_48()
	{
		this.Passages["He's not perfect. We argue, just like everyone else."] = new TwinePassage("He's not perfect. We argue, just like everyone else.", new string[]{  }, passageExecute_48);
	}

	IEnumerable<TwineOutput> passageExecute_48()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <neutral>%");
		yield return new TwineText(@"PATRICE: Well, of course you do! ");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: Two men, rattling around in a big castle like this? You're bound to argue sooner or later!");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: What's important is that you always come back to each other.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: Oh, listen to me rattle on. Did you have any other questions for me, sire?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Certainly.", @"Certainly.", @"else", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"leave", null, null);	
	}
    
	// .............
	// #49: I'm sorry about that.

	void passageInit_49()
	{
		this.Passages["I'm sorry about that."] = new TwinePassage("I'm sorry about that.", new string[]{  }, passageExecute_49);
	}

	IEnumerable<TwineOutput> passageExecute_49()
	{
		yield return new TwineText(@"#pat_approval, +5#");
		yield return new TwineText(@"%1, <pat>, <center>, <smile>%");
		yield return new TwineText(@"PATRICE: No, no, it's alright! I can't speak for the other ladies, but personally I feel very...glad to be here. ");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: I've never even <i>seen</i> a castle before. So this is all terribly exciting for me!");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: Did you have any other questions for me, sire?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Certainly.", @"Certainly.", @"else", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"leave", null, null);	
	}
    
	// .............
	// #50: I don't need your pity.

	void passageInit_50()
	{
		this.Passages["I don't need your pity."] = new TwinePassage("I don't need your pity.", new string[]{  }, passageExecute_50);
	}

	IEnumerable<TwineOutput> passageExecute_50()
	{
		yield return new TwineText(@"#pat_approval, -5#");
		yield return new TwineText(@"%1, <pat>, <center>, <scared>%");
		yield return new TwineText(@"PATRICE: No, please, I didn't mean--I mean, I--");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: Could we talk about something else now, please?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Certainly.", @"Certainly.", @"else", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"leave", null, null);	
	}
    
	// .............
	// #51: Nothing anyone could say at this point would offend me.

	void passageInit_51()
	{
		this.Passages["Nothing anyone could say at this point would offend me."] = new TwinePassage("Nothing anyone could say at this point would offend me.", new string[]{  }, passageExecute_51);
	}

	IEnumerable<TwineOutput> passageExecute_51()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <scared>%");
		yield return new TwineText(@"PATRICE: O-oh.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: That's...Excuse me for saying so, but that's very sad. Sire.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: Could we talk about something else now, please?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Certainly.", @"Certainly.", @"else", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"leave", null, null);	
	}
    
	// .............
	// #52: It's alright. I know what I look like.

	void passageInit_52()
	{
		this.Passages["It's alright. I know what I look like."] = new TwinePassage("It's alright. I know what I look like.", new string[]{  }, passageExecute_52);
	}

	IEnumerable<TwineOutput> passageExecute_52()
	{
		yield return new TwineText(@"#pat_approval, +5#");
		yield return new TwineText(@"%1, <pat>, <center>, <scared>%");
		yield return new TwineText(@"PATRICE: Oh. I suppose you do. Well, I'm...I'm grateful for your understanding.");
		yield return new TwineText(@"");
		yield return new TwineText(@"PATRICE: Could we talk about something else now, please?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Certainly.", @"Certainly.", @"else", null, null);
		yield return new TwineLink(@"Actually, I have to leave.", @"Actually, I have to leave.", @"leave", null, null);	
	}
    
	// .............
	// #53: else

	void passageInit_53()
	{
		this.Passages["else"] = new TwinePassage("else", new string[]{  }, passageExecute_53);
	}

	IEnumerable<TwineOutput> passageExecute_53()
	{
		yield return new TwineText(@"%1, <pat>, <center>, <smile>%");
		yield return new TwineText(@"PATRICE: Of course, sire. What would you like to talk about?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I want to hear your opinion of the other women staying in the castle.", @"I want to hear your opinion of the other women staying in the castle.", @"women", null, null);
		yield return new TwineLink(@"%pat_approval,-30,0%How are you enjoying your stay here?", @"%pat_approval,-30,0%How are you enjoying your stay here?", @"stay1", null, null);
		yield return new TwineLink(@"%pat_approval,1,30%How are you enjoying your stay here?", @"%pat_approval,1,30%How are you enjoying your stay here?", @"stay2", null, null);
		yield return new TwineLink(@"%pat_approval,31,50%How are you enjoying your stay here?", @"%pat_approval,31,50%How are you enjoying your stay here?", @"stay3", null, null);
		yield return new TwineLink(@"%pat_approval,51,70%How are you enjoying your stay here?", @"%pat_approval,51,70%How are you enjoying your stay here?", @"stay4", null, null);
		yield return new TwineLink(@"Let's talk about you.", @"Let's talk about you.", @"you", null, null);	
	}
    
	// .............
	// #54: secret

	void passageInit_54()
	{
		this.Passages["secret"] = new TwinePassage("secret", new string[]{  }, passageExecute_54);
	}

	IEnumerable<TwineOutput> passageExecute_54()
	{
		yield return new TwineText(@"#convo_points, -1#");	
	}
    
	// .............
	// #55: trouble

	void passageInit_55()
	{
		this.Passages["trouble"] = new TwinePassage("trouble", new string[]{  }, passageExecute_55);
	}

	IEnumerable<TwineOutput> passageExecute_55()
	{
		yield return new TwineText(@"#convo_points, -1#");	
	}

}