/*
Generated by UnityTwine on 4/28/2016 10:07:43 PM
https://github.com/daterre/UnityTwine
*/
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UnityTwine;

public class beau_marriage: TwineStory
{
	public override TwineVar this[string name]
	{
		get
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
		set
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
	}


	void Awake() {
		base.Init();
		passageInit_0();
	}
    
	// .............
	// #0: Start

	void passageInit_0()
	{
		this.Passages["Start"] = new TwinePassage("Start", new string[]{  }, passageExecute_0);
	}

	IEnumerable<TwineOutput> passageExecute_0()
	{
		yield return new TwineText(@"%1, <beau>, <center>, <marriage>%");
		yield return new TwineText(@"<i>Sure, maybe it isn't what you hoped for. And </i>certainly<i> not what you expected. But it's comforting, in a way, to know that no matter what, Beau will always be with you.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>In hindsight, maybe you should've picked up on Beauregard's feelings sooner. After all, no butler would be considered obligated to stay with his master after said master had been cursed.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>And maybe, if you had known, you might have been able to come to love him in return, and broken the spell. But he didn't say anything, and you didn't realize, and so here you are.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>You'll never be a handsome prince again--that window of opportunity has closed. But maybe, instead, you can become a good husband.</i>");	
	}

}