/*
Generated by UnityTwine on 4/28/2016 10:07:43 PM
https://github.com/daterre/UnityTwine
*/
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UnityTwine;

public class beau_pity: TwineStory
{
	public override TwineVar this[string name]
	{
		get
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
		set
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
	}


	void Awake() {
		base.Init();
		passageInit_0();
	}
    
	// .............
	// #0: Start

	void passageInit_0()
	{
		this.Passages["Start"] = new TwinePassage("Start", new string[]{  }, passageExecute_0);
	}

	IEnumerable<TwineOutput> passageExecute_0()
	{
		yield return new TwineText(@"$BeauSad$");
		yield return new TwineText(@"%1, <beau>, <center>, <sad>%");
		yield return new TwineText(@"BEAUREGARD: Oh, sire. I'm so sorry.");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: I thought you might have a chance, I really did. But maybe I just got your hopes up for nothing.");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAST: It's alright, Beau. ");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAST: You did everything you could. I'm the one who failed here. Please, go and find your own happy ending.");
		yield return new TwineText(@"");
		yield return new TwineText(@"$BeauAngry$");
		yield return new TwineText(@"%1, <beau>, <center>, <angry>%");
		yield return new TwineText(@"BEAUREGARD: Don't be ridiculous, sire! As if my happy ending could be anywhere but here! With you!");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: I didn't stay with you all these years without good reason.");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: I've loved you since we were children, Adam. And I'm not about to give up on you now.");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAST: You...love me?");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <beau>, <center>, <neutral>%");
		yield return new TwineText(@"BEAUREGARD: ...You mean you didn't know?");
		yield return new TwineText(@"");
		yield return new TwineText(@"BEAUREGARD: I...All this time I thought you just didn't want to be with me. But if you didn't even realize that I--");
		yield return new TwineText(@"");
		yield return new TwineText(@"%1, <beau>, <center>, <smile>%");
		yield return new TwineText(@"BEAUREGARD: I love you, Adam. And I would be happy to spend the rest of my life with you.");
		yield return new TwineText(@"");
		yield return new TwineText(@"&Beau&");	
	}

}