/*
Generated by UnityTwine on 4/28/2016 9:41:37 PM
https://github.com/daterre/UnityTwine
*/
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UnityTwine;

public class hen_marriage: TwineStory
{
	public override TwineVar this[string name]
	{
		get
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
		set
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
	}


	void Awake() {
		base.Init();
		passageInit_0();
	}
    
	// .............
	// #0: Start

	void passageInit_0()
	{
		this.Passages["Start"] = new TwinePassage("Start", new string[]{  }, passageExecute_0);
	}

	IEnumerable<TwineOutput> passageExecute_0()
	{
		yield return new TwineText(@"%1, <hen>, <center>, <marriage>%");
		yield return new TwineText(@"<i>The marriage is everything you'd never dared to hope for. Music, good cheer, and a person--er, cow--by your side who actually wants to be there.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>The wedding is small, of course--there's really no one around to celebrate with--but the people who are in attendance are beaming ear to ear. You even notice tears in Beauregard's eyes.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Henrietta is the very picture of grace--cow-eyed and radiant in her crown of flowers. You wonder how you got so lucky.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Dancing with your new wife is obviously not an option, but sitting quietly at the banquet table with her is a joy into itself.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>The reception is over almost too soon, or maybe not soon enough. </i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>As the guests start to file out, and Beauregard congratulates you yet again, you thread your claws tenderly through the hair on Henrietta's sloping back.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>You aren't sure whether a cow's love will be enough to break the curse and turn you back into a human, but you do know that it's enough to make you happy for the rest of your life.</i>");	
	}

}