/*
Generated by UnityTwine on 4/28/2016 9:41:37 PM
https://github.com/daterre/UnityTwine
*/
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UnityTwine;

public class john_marriage: TwineStory
{
	public override TwineVar this[string name]
	{
		get
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
		set
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
	}


	void Awake() {
		base.Init();
		passageInit_0();
	}
    
	// .............
	// #0: Start

	void passageInit_0()
	{
		this.Passages["Start"] = new TwinePassage("Start", new string[]{  }, passageExecute_0);
	}

	IEnumerable<TwineOutput> passageExecute_0()
	{
		yield return new TwineText(@"%1, <john>, <center>, <marriage>%");
		yield return new TwineText(@"<i>The marriage is everything you'd never dared to hope for. Music, good cheer, and a person by your side who actually wants to be there.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>The wedding is small, of course--there's really no one around to celebrate with--but the people who are in attendance are beaming ear to ear. You even notice tears in Beauregard's eyes.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>As the ceremony ends, and your marriage is sealed in a kiss, Jane laughs so loudly and happily that you feel lighter than air.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>However, the crowning glory of the evening is your turn around the dance floor with Jane during the wedding reception.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Your paws aren't meant for light footwork, but Jane only seems to enjoy dancing with you more when you mess up the steps.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Many sly jokes and beaming smiles later, the reception finally comes to an end. Jane thanks Beauregard for all his help, then turns to you with an adoring look.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Jane's smile isn't amused or joking as you link hands to leave the reception. It's soft, and shy, and meant for only you.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Tomorrow, you will wake up with your new wife, human once more--and your new life will begin.</i>");	
	}

}