/*
Generated by UnityTwine on 04/28/2016 21:00:49
https://github.com/daterre/UnityTwine
*/
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UnityTwine;

public class noelle_marriage: TwineStory
{
	public override TwineVar this[string name]
	{
		get
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
		set
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
	}


	void Awake() {
		base.Init();
		passageInit_0();
	}
    
	// .............
	// #0: Start

	void passageInit_0()
	{
		this.Passages["Start"] = new TwinePassage("Start", new string[]{  }, passageExecute_0);
	}

	IEnumerable<TwineOutput> passageExecute_0()
	{
		yield return new TwineText(@"%1, <noelle>, <center>, <marriage>%");
		yield return new TwineText(@"<i>The marriage is everything you'd never dared to hope for. Music, good cheer, and a woman by your side who actually wants to be there.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>The wedding is small, of course--there's really no one around to celebrate with--but the people who are in attendance are beaming ear to ear. You even notice tears in Beauregard's eyes.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>During the wedding ceremony, Noelle seems to be holding back, as if afraid to let herself be happy and in the moment.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>It's only after the vows are said, and you give her an adoring--if toothy--smile, that her shoulders relax. The smile she gives you in return is near-blinding in intensity. </i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>During the reception, Noelle is radiantly happy, talking and laughing openly with everyone.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>It's the most comfortable you've ever seen her, and you promise yourself then and there that you'll try to make her look like this more often.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>When the reception finally ends, Noelle looks at you with an expression you've never seen before--a look of trepidation, but also trust. You leave the reception hand-in-hand.</i>");
		yield return new TwineText(@"");
		yield return new TwineText(@"<i>Tomorrow, you will wake up with your new wife, human once more--and your new life will begin.</i>");	
	}

}