/*
Generated by UnityTwine on 3/31/2016 11:13:09 AM
https://github.com/daterre/UnityTwine
*/
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UnityTwine;

public class BeastlyTutorial: TwineStory
{
	public override TwineVar this[string name]
	{
		get
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
		set
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
	}


	void Awake() {
		base.Init();
		passageInit_0();
		passageInit_1();
		passageInit_2();
		passageInit_3();
		passageInit_4();
		passageInit_5();
		passageInit_6();
		passageInit_7();
		passageInit_8();
		passageInit_9();
		passageInit_10();
		passageInit_11();
		passageInit_12();
	}
    
	// .............
	// #0: Start

	void passageInit_0()
	{
		this.Passages["Start"] = new TwinePassage("Start", new string[]{ "beauFROWN", }, passageExecute_0);
	}

	IEnumerable<TwineOutput> passageExecute_0()
	{
		yield return new TwineText(@"BEAUREGARD: Sire! Sire, they're almost here! You can't keep sulking in your room like this.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"I can try.", @"I can try.", @"I can try.", null, null);	
	}
    
	// .............
	// #1: I can try.

	void passageInit_1()
	{
		this.Passages["I can try."] = new TwinePassage("I can try.", new string[]{ "beauANGRY", }, passageExecute_1);
	}

	IEnumerable<TwineOutput> passageExecute_1()
	{
		yield return new TwineText(@"BEAUREGARD: Oh, please. Sulking won't do you any good. If you hadn't spent all your time moping around the castle yelling at anyone who stopped by, you wouldn't be in this position to begin with!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Look at me, Beauregard. I'm a monster. There's no way any of the women you sent for will want me.", @"Look at me, Beauregard. I'm a monster. There's no way any of the women you sent for will want me.", @"Look at me, Beauregard. I'm a monster. There's no way any of the women you sent for will want me.", null, null);	
	}
    
	// .............
	// #2: Look at me, Beauregard. I'm a monster. There's no way any of the women you sent for will want me.

	void passageInit_2()
	{
		this.Passages["Look at me, Beauregard. I'm a monster. There's no way any of the women you sent for will want me."] = new TwinePassage("Look at me, Beauregard. I'm a monster. There's no way any of the women you sent for will want me.", new string[]{ "beauFROWN", }, passageExecute_2);
	}

	IEnumerable<TwineOutput> passageExecute_2()
	{
		yield return new TwineText(@"BEAUREGARD: Well, not with that attitude. You'll have to be significantly more well-mannered if you want to win their affections. Come, practice on me.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"What?", @"What?", @"What?", null, null);	
	}
    
	// .............
	// #3: What?

	void passageInit_3()
	{
		this.Passages["What?"] = new TwinePassage("What?", new string[]{ "beauSMILE", }, passageExecute_3);
	}

	IEnumerable<TwineOutput> passageExecute_3()
	{
		yield return new TwineText(@"BEAUREGARD: Like this. //I'm a young woman from a small village, here to meet the man who could be my future husband...if he plays his cards right.//");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Beau, this is ridiculous.", @"Beau, this is ridiculous.", @"Beau, this is ridiculous.", null, null);	
	}
    
	// .............
	// #4: Beau, this is ridiculous.

	void passageInit_4()
	{
		this.Passages["Beau, this is ridiculous."] = new TwinePassage("Beau, this is ridiculous.", new string[]{ "beauFROWN", }, passageExecute_4);
	}

	IEnumerable<TwineOutput> passageExecute_4()
	{
		yield return new TwineText(@"BEAUREGARD: We're running out of time, sire! Or would you rather face those women as you are now, having not spoken to a woman in ten years?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"...Fine.", @"...Fine.", @"...Fine.", null, null);	
	}
    
	// .............
	// #5: ...Fine.

	void passageInit_5()
	{
		this.Passages["...Fine."] = new TwinePassage("...Fine.", new string[]{ "beauSMILE", }, passageExecute_5);
	}

	IEnumerable<TwineOutput> passageExecute_5()
	{
		yield return new TwineText(@"BEAUREGARD: Now then. //My name's Olivia. What's yours?//");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Prince Adam.", @"Prince Adam.", @"Prince Adam.", null, null);
		yield return new TwineLink(@"Adam. Just Adam.", @"Adam. Just Adam.", @"Adam. Just Adam.", null, null);
		yield return new TwineLink(@"Beast.", @"Beast.", @"Beast.", null, null);	
	}
    
	// .............
	// #6: Beast.

	void passageInit_6()
	{
		this.Passages["Beast."] = new TwinePassage("Beast.", new string[]{ "beauANGRY", }, passageExecute_6);
	}

	IEnumerable<TwineOutput> passageExecute_6()
	{
		yield return new TwineText(@"BEAUREGARD: Don't be ridiculous, sire! I won't have you introducing yourself with that //silly// nickname you came up with. It's depressing.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Fine. Prince Adam, then.", @"Fine. Prince Adam, then.", @"Prince Adam.", null, null);
		yield return new TwineLink(@"Then my name is Adam. Just Adam.", @"Then my name is Adam. Just Adam.", @"Adam. Just Adam.", null, null);
		yield return new TwineLink(@"Being like this is depressing. The name suits me.", @"Being like this is depressing. The name suits me.", @"Being like this is depressing. The name suits me.", null, null);	
	}
    
	// .............
	// #7: StoryTitle

	void passageInit_7()
	{
		this.Passages["StoryTitle"] = new TwinePassage("StoryTitle", new string[]{  }, passageExecute_7);
	}

	IEnumerable<TwineOutput> passageExecute_7()
	{
		yield return new TwineText(@"Untitled Story");	
	}
    
	// .............
	// #8: Prince Adam.

	void passageInit_8()
	{
		this.Passages["Prince Adam."] = new TwinePassage("Prince Adam.", new string[]{ "beauSMILE", }, passageExecute_8);
	}

	IEnumerable<TwineOutput> passageExecute_8()
	{
		yield return new TwineText(@"BEAUREGARD: //A pleasure to meet you, your majesty!// You're making good progress, sire. Let's continue.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Go on, then.", @"Go on, then.", @"Go on, then.", null, null);	
	}
    
	// .............
	// #9: Adam. Just Adam.

	void passageInit_9()
	{
		this.Passages["Adam. Just Adam."] = new TwinePassage("Adam. Just Adam.", new string[]{ "beauSMILE", }, passageExecute_9);
	}

	IEnumerable<TwineOutput> passageExecute_9()
	{
		yield return new TwineText(@"BEAUREGARD: //Oh, so humble! A pleasure to meet you, Adam.// That was splendid, your majesty. Let's continue!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Go on, then.", @"Go on, then.", @"Go on, then.", null, null);	
	}
    
	// .............
	// #10: Being like this is depressing. The name suits me.

	void passageInit_10()
	{
		this.Passages["Being like this is depressing. The name suits me."] = new TwinePassage("Being like this is depressing. The name suits me.", new string[]{ "beauFROWN", }, passageExecute_10);
	}

	IEnumerable<TwineOutput> passageExecute_10()
	{
		yield return new TwineText(@"BEAUREGARD: Ugh! You're impossible. Let's just keep going.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Go on, then.", @"Go on, then.", @"Go on, then.", null, null);	
	}
    
	// .............
	// #11: StoryAuthor

	void passageInit_11()
	{
		this.Passages["StoryAuthor"] = new TwinePassage("StoryAuthor", new string[]{  }, passageExecute_11);
	}

	IEnumerable<TwineOutput> passageExecute_11()
	{
		yield return new TwineText(@"Anonymous");	
	}
    
	// .............
	// #12: Go on, then.

	void passageInit_12()
	{
		this.Passages["Go on, then."] = new TwinePassage("Go on, then.", new string[]{  }, passageExecute_12);
	}

	IEnumerable<TwineOutput> passageExecute_12()
	{
		yield return new TwineText(@"");	
	}

}